Quotes Language:		german
Base Header Level:	3
latex input:				kleinod-mmd-scrlttr2
MyOptions:					author=schiri, font=droid, layout=infospaltefett
latex input:				kleinod-mmd-style
Title:							**generated documentdata:subject**
MyBetreff:					**generated documentdata:subject**
Date:								**generated documentdata:date:datelong**
MyAnA:							**generated referee:fullname**
MyAnB:							**generated referee:primaryaddress:street** **generated referee:primaryaddress:number**
MyAnC:							**generated referee:primaryaddress:zipcode** **generated referee:primaryaddress:city**
MyAnrede:						**generated documentdata:opening**
MyGruss:						**generated documentdata:closing**
MyUnterschrift:			**generated documentdata:signature**
MyAnlage:						**foreach documentdata:attachment:****separator**, **end separator****generated documentdata:attachment:title****end foreach documentdata:attachment:**
latex input:				kleinod-mmd-begin-lttr
latex footer:				kleinod-mmd-end-lttr

**generated documentdata:body**
