/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables.records;


import de.edgesoft.refereemanager.jooq.tables.ActivityLogs;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * Activity log of selected data tables. Only those tables are  / * comment 
 * truncated * / / *logged that are important to the user.* /
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityLogsRecord extends UpdatableRecordImpl<ActivityLogsRecord> implements Record9<UInteger, UInteger, UInteger, Integer, String, String, UInteger, String, Timestamp> {

    private static final long serialVersionUID = 1773538613;

    /**
     * Setter for <code>refereemanager.rfrmgr_activity_logs.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_activity_logs.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_activity_logs.database_table_id</code>.
     */
    public void setDatabaseTableId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_activity_logs.database_table_id</code>.
     */
    public UInteger getDatabaseTableId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_activity_logs.database_column_id</code>.
     */
    public void setDatabaseColumnId(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_activity_logs.database_column_id</code>.
     */
    public UInteger getDatabaseColumnId() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_activity_logs.row_id</code>.
     */
    public void setRowId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_activity_logs.row_id</code>.
     */
    public Integer getRowId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_activity_logs.old_value</code>.
     */
    public void setOldValue(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_activity_logs.old_value</code>.
     */
    public String getOldValue() {
        return (String) get(4);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_activity_logs.new_value</code>.
     */
    public void setNewValue(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_activity_logs.new_value</code>.
     */
    public String getNewValue() {
        return (String) get(5);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_activity_logs.user_id</code>.
     */
    public void setUserId(UInteger value) {
        set(6, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_activity_logs.user_id</code>.
     */
    public UInteger getUserId() {
        return (UInteger) get(6);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_activity_logs.remark</code>.
     */
    public void setRemark(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_activity_logs.remark</code>.
     */
    public String getRemark() {
        return (String) get(7);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_activity_logs.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_activity_logs.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<UInteger, UInteger, UInteger, Integer, String, String, UInteger, String, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<UInteger, UInteger, UInteger, Integer, String, String, UInteger, String, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return ActivityLogs.ACTIVITY_LOGS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return ActivityLogs.ACTIVITY_LOGS.DATABASE_TABLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return ActivityLogs.ACTIVITY_LOGS.DATABASE_COLUMN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ActivityLogs.ACTIVITY_LOGS.ROW_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ActivityLogs.ACTIVITY_LOGS.OLD_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ActivityLogs.ACTIVITY_LOGS.NEW_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field7() {
        return ActivityLogs.ACTIVITY_LOGS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return ActivityLogs.ACTIVITY_LOGS.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return ActivityLogs.ACTIVITY_LOGS.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getDatabaseTableId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getDatabaseColumnId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getRowId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOldValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getNewValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value7() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityLogsRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityLogsRecord value2(UInteger value) {
        setDatabaseTableId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityLogsRecord value3(UInteger value) {
        setDatabaseColumnId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityLogsRecord value4(Integer value) {
        setRowId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityLogsRecord value5(String value) {
        setOldValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityLogsRecord value6(String value) {
        setNewValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityLogsRecord value7(UInteger value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityLogsRecord value8(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityLogsRecord value9(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityLogsRecord values(UInteger value1, UInteger value2, UInteger value3, Integer value4, String value5, String value6, UInteger value7, String value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActivityLogsRecord
     */
    public ActivityLogsRecord() {
        super(ActivityLogs.ACTIVITY_LOGS);
    }

    /**
     * Create a detached, initialised ActivityLogsRecord
     */
    public ActivityLogsRecord(UInteger id, UInteger databaseTableId, UInteger databaseColumnId, Integer rowId, String oldValue, String newValue, UInteger userId, String remark, Timestamp created) {
        super(ActivityLogs.ACTIVITY_LOGS);

        set(0, id);
        set(1, databaseTableId);
        set(2, databaseColumnId);
        set(3, rowId);
        set(4, oldValue);
        set(5, newValue);
        set(6, userId);
        set(7, remark);
        set(8, created);
    }
}
