/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables.records;


import de.edgesoft.refereemanager.jooq.tables.Addresses;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * All addresses.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressesRecord extends UpdatableRecordImpl<AddressesRecord> implements Record6<UInteger, UInteger, String, String, String, String> {

    private static final long serialVersionUID = 1435851326;

    /**
     * Setter for <code>refereemanager.rfrmgr_addresses.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_addresses.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_addresses.contact_id</code>.
     */
    public void setContactId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_addresses.contact_id</code>.
     */
    public UInteger getContactId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_addresses.street</code>.
     */
    public void setStreet(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_addresses.street</code>.
     */
    public String getStreet() {
        return (String) get(2);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_addresses.number</code>.
     */
    public void setNumber(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_addresses.number</code>.
     */
    public String getNumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_addresses.zip_code</code>.
     */
    public void setZipCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_addresses.zip_code</code>.
     */
    public String getZipCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_addresses.city</code>.
     */
    public void setCity(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_addresses.city</code>.
     */
    public String getCity() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Addresses.RFRMGR_ADDRESSES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Addresses.RFRMGR_ADDRESSES.CONTACT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Addresses.RFRMGR_ADDRESSES.STREET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Addresses.RFRMGR_ADDRESSES.NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Addresses.RFRMGR_ADDRESSES.ZIP_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Addresses.RFRMGR_ADDRESSES.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getContactId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStreet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressesRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressesRecord value2(UInteger value) {
        setContactId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressesRecord value3(String value) {
        setStreet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressesRecord value4(String value) {
        setNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressesRecord value5(String value) {
        setZipCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressesRecord value6(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressesRecord values(UInteger value1, UInteger value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AddressesRecord
     */
    public AddressesRecord() {
        super(Addresses.RFRMGR_ADDRESSES);
    }

    /**
     * Create a detached, initialised AddressesRecord
     */
    public AddressesRecord(UInteger id, UInteger contactId, String street, String number, String zipCode, String city) {
        super(Addresses.RFRMGR_ADDRESSES);

        set(0, id);
        set(1, contactId);
        set(2, street);
        set(3, number);
        set(4, zipCode);
        set(5, city);
    }
}
