/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables.records;


import de.edgesoft.refereemanager.jooq.tables.LeagueGames;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * Assignments for league games.
 * League and season can be deduc / * comment truncated * / / *ed from the 
 * associated teams, they are stored because no team could be specified or 
 * teams of different seasons/leagues (e.g. relegation games).* /
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LeagueGamesRecord extends UpdatableRecordImpl<LeagueGamesRecord> implements Record6<UInteger, UInteger, UInteger, UInteger, UInteger, UInteger> {

    private static final long serialVersionUID = 421125085;

    /**
     * Setter for <code>refereemanager.rfrmgr_league_games.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_league_games.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_league_games.assignment_id</code>.
     */
    public void setAssignmentId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_league_games.assignment_id</code>.
     */
    public UInteger getAssignmentId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_league_games.game_number</code>.
     */
    public void setGameNumber(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_league_games.game_number</code>.
     */
    public UInteger getGameNumber() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_league_games.season_id</code>.
     */
    public void setSeasonId(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_league_games.season_id</code>.
     */
    public UInteger getSeasonId() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_league_games.league_id</code>.
     */
    public void setLeagueId(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_league_games.league_id</code>.
     */
    public UInteger getLeagueId() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_league_games.team_venue_id</code>. Only filled if team plays outside their normal location.
     */
    public void setTeamVenueId(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_league_games.team_venue_id</code>. Only filled if team plays outside their normal location.
     */
    public UInteger getTeamVenueId() {
        return (UInteger) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, UInteger, UInteger, UInteger, UInteger> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, UInteger, UInteger, UInteger, UInteger> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return LeagueGames.LEAGUE_GAMES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return LeagueGames.LEAGUE_GAMES.ASSIGNMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return LeagueGames.LEAGUE_GAMES.GAME_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return LeagueGames.LEAGUE_GAMES.SEASON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return LeagueGames.LEAGUE_GAMES.LEAGUE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field6() {
        return LeagueGames.LEAGUE_GAMES.TEAM_VENUE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getAssignmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getGameNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getSeasonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getLeagueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value6() {
        return getTeamVenueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LeagueGamesRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LeagueGamesRecord value2(UInteger value) {
        setAssignmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LeagueGamesRecord value3(UInteger value) {
        setGameNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LeagueGamesRecord value4(UInteger value) {
        setSeasonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LeagueGamesRecord value5(UInteger value) {
        setLeagueId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LeagueGamesRecord value6(UInteger value) {
        setTeamVenueId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LeagueGamesRecord values(UInteger value1, UInteger value2, UInteger value3, UInteger value4, UInteger value5, UInteger value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LeagueGamesRecord
     */
    public LeagueGamesRecord() {
        super(LeagueGames.LEAGUE_GAMES);
    }

    /**
     * Create a detached, initialised LeagueGamesRecord
     */
    public LeagueGamesRecord(UInteger id, UInteger assignmentId, UInteger gameNumber, UInteger seasonId, UInteger leagueId, UInteger teamVenueId) {
        super(LeagueGames.LEAGUE_GAMES);

        set(0, id);
        set(1, assignmentId);
        set(2, gameNumber);
        set(3, seasonId);
        set(4, leagueId);
        set(5, teamVenueId);
    }
}
