/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables.records;


import de.edgesoft.refereemanager.jooq.tables.RefereeReportRecipients;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * All league types.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RefereeReportRecipientsRecord extends UpdatableRecordImpl<RefereeReportRecipientsRecord> implements Record3<UInteger, Integer, Integer> {

    private static final long serialVersionUID = 142639854;

    /**
     * Setter for <code>refereemanager.rfrmgr_referee_report_recipients.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_referee_report_recipients.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_referee_report_recipients.referee_report_id</code>.
     */
    public void setRefereeReportId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_referee_report_recipients.referee_report_id</code>.
     */
    public Integer getRefereeReportId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_referee_report_recipients.person_id</code>.
     */
    public void setPersonId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_referee_report_recipients.person_id</code>.
     */
    public Integer getPersonId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return RefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS.REFEREE_REPORT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return RefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS.PERSON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRefereeReportId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefereeReportRecipientsRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefereeReportRecipientsRecord value2(Integer value) {
        setRefereeReportId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefereeReportRecipientsRecord value3(Integer value) {
        setPersonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefereeReportRecipientsRecord values(UInteger value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefereeReportRecipientsRecord
     */
    public RefereeReportRecipientsRecord() {
        super(RefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS);
    }

    /**
     * Create a detached, initialised RefereeReportRecipientsRecord
     */
    public RefereeReportRecipientsRecord(UInteger id, Integer refereeReportId, Integer personId) {
        super(RefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS);

        set(0, id);
        set(1, refereeReportId);
        set(2, personId);
    }
}
