/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables.records;


import de.edgesoft.refereemanager.jooq.tables.RefereeAssignments;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * Referee's assignments with their role.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RefereeAssignmentsRecord extends UpdatableRecordImpl<RefereeAssignmentsRecord> implements Record7<UInteger, UInteger, UInteger, UInteger, UInteger, UInteger, String> {

    private static final long serialVersionUID = 1274827313;

    /**
     * Setter for <code>refereemanager.rfrmgr_referee_assignments.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_referee_assignments.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_referee_assignments.assignment_id</code>.
     */
    public void setAssignmentId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_referee_assignments.assignment_id</code>.
     */
    public UInteger getAssignmentId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_referee_assignments.referee_assignment_type_id</code>.
     */
    public void setRefereeAssignmentTypeId(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_referee_assignments.referee_assignment_type_id</code>.
     */
    public UInteger getRefereeAssignmentTypeId() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_referee_assignments.referee_id</code>.
     */
    public void setRefereeId(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_referee_assignments.referee_id</code>.
     */
    public UInteger getRefereeId() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_referee_assignments.referee_assignment_status_type_id</code>.
     */
    public void setRefereeAssignmentStatusTypeId(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_referee_assignments.referee_assignment_status_type_id</code>.
     */
    public UInteger getRefereeAssignmentStatusTypeId() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_referee_assignments.referee_assignment_remark_type_id</code>.
     */
    public void setRefereeAssignmentRemarkTypeId(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_referee_assignments.referee_assignment_remark_type_id</code>.
     */
    public UInteger getRefereeAssignmentRemarkTypeId() {
        return (UInteger) get(5);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_referee_assignments.remark</code>.
     */
    public void setRemark(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_referee_assignments.remark</code>.
     */
    public String getRemark() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, UInteger, UInteger, UInteger, UInteger, UInteger, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, UInteger, UInteger, UInteger, UInteger, UInteger, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return RefereeAssignments.REFEREE_ASSIGNMENTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return RefereeAssignments.REFEREE_ASSIGNMENTS.ASSIGNMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return RefereeAssignments.REFEREE_ASSIGNMENTS.REFEREE_ASSIGNMENT_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return RefereeAssignments.REFEREE_ASSIGNMENTS.REFEREE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return RefereeAssignments.REFEREE_ASSIGNMENTS.REFEREE_ASSIGNMENT_STATUS_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field6() {
        return RefereeAssignments.REFEREE_ASSIGNMENTS.REFEREE_ASSIGNMENT_REMARK_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return RefereeAssignments.REFEREE_ASSIGNMENTS.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getAssignmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getRefereeAssignmentTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getRefereeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getRefereeAssignmentStatusTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value6() {
        return getRefereeAssignmentRemarkTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefereeAssignmentsRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefereeAssignmentsRecord value2(UInteger value) {
        setAssignmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefereeAssignmentsRecord value3(UInteger value) {
        setRefereeAssignmentTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefereeAssignmentsRecord value4(UInteger value) {
        setRefereeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefereeAssignmentsRecord value5(UInteger value) {
        setRefereeAssignmentStatusTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefereeAssignmentsRecord value6(UInteger value) {
        setRefereeAssignmentRemarkTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefereeAssignmentsRecord value7(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefereeAssignmentsRecord values(UInteger value1, UInteger value2, UInteger value3, UInteger value4, UInteger value5, UInteger value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefereeAssignmentsRecord
     */
    public RefereeAssignmentsRecord() {
        super(RefereeAssignments.REFEREE_ASSIGNMENTS);
    }

    /**
     * Create a detached, initialised RefereeAssignmentsRecord
     */
    public RefereeAssignmentsRecord(UInteger id, UInteger assignmentId, UInteger refereeAssignmentTypeId, UInteger refereeId, UInteger refereeAssignmentStatusTypeId, UInteger refereeAssignmentRemarkTypeId, String remark) {
        super(RefereeAssignments.REFEREE_ASSIGNMENTS);

        set(0, id);
        set(1, assignmentId);
        set(2, refereeAssignmentTypeId);
        set(3, refereeId);
        set(4, refereeAssignmentStatusTypeId);
        set(5, refereeAssignmentRemarkTypeId);
        set(6, remark);
    }
}
