/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables.records;


import de.edgesoft.refereemanager.jooq.tables.RfrmgrPersonPreferences;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * Preferences for a person.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RfrmgrPersonPreferencesRecord extends UpdatableRecordImpl<RfrmgrPersonPreferencesRecord> implements Record4<UInteger, UInteger, String, Integer> {

    private static final long serialVersionUID = 51706238;

    /**
     * Setter for <code>refereemanager.rfrmgr_person_preferences.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_person_preferences.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_person_preferences.person_id</code>.
     */
    public void setPersonId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_person_preferences.person_id</code>.
     */
    public UInteger getPersonId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_person_preferences.language</code>.
     */
    public void setLanguage(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_person_preferences.language</code>.
     */
    public String getLanguage() {
        return (String) get(2);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_person_preferences.assignment_notification_interval</code>.
     */
    public void setAssignmentNotificationInterval(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_person_preferences.assignment_notification_interval</code>.
     */
    public Integer getAssignmentNotificationInterval() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, UInteger, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, UInteger, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return RfrmgrPersonPreferences.RFRMGR_PERSON_PREFERENCES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return RfrmgrPersonPreferences.RFRMGR_PERSON_PREFERENCES.PERSON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return RfrmgrPersonPreferences.RFRMGR_PERSON_PREFERENCES.LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return RfrmgrPersonPreferences.RFRMGR_PERSON_PREFERENCES.ASSIGNMENT_NOTIFICATION_INTERVAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAssignmentNotificationInterval();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrPersonPreferencesRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrPersonPreferencesRecord value2(UInteger value) {
        setPersonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrPersonPreferencesRecord value3(String value) {
        setLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrPersonPreferencesRecord value4(Integer value) {
        setAssignmentNotificationInterval(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrPersonPreferencesRecord values(UInteger value1, UInteger value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RfrmgrPersonPreferencesRecord
     */
    public RfrmgrPersonPreferencesRecord() {
        super(RfrmgrPersonPreferences.RFRMGR_PERSON_PREFERENCES);
    }

    /**
     * Create a detached, initialised RfrmgrPersonPreferencesRecord
     */
    public RfrmgrPersonPreferencesRecord(UInteger id, UInteger personId, String language, Integer assignmentNotificationInterval) {
        super(RfrmgrPersonPreferences.RFRMGR_PERSON_PREFERENCES);

        set(0, id);
        set(1, personId);
        set(2, language);
        set(3, assignmentNotificationInterval);
    }
}
