/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables.records;


import de.edgesoft.refereemanager.jooq.tables.RfrmgrTeamVenues;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * Venues of teams in a season.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RfrmgrTeamVenuesRecord extends UpdatableRecordImpl<RfrmgrTeamVenuesRecord> implements Record4<UInteger, UInteger, UInteger, UInteger> {

    private static final long serialVersionUID = 434181182;

    /**
     * Setter for <code>refereemanager.rfrmgr_team_venues.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_team_venues.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_team_venues.team_season_id</code>.
     */
    public void setTeamSeasonId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_team_venues.team_season_id</code>.
     */
    public UInteger getTeamSeasonId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_team_venues.contact_id</code>.
     */
    public void setContactId(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_team_venues.contact_id</code>.
     */
    public UInteger getContactId() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_team_venues.number</code>.
     */
    public void setNumber(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_team_venues.number</code>.
     */
    public UInteger getNumber() {
        return (UInteger) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, UInteger, UInteger, UInteger> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, UInteger, UInteger, UInteger> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return RfrmgrTeamVenues.RFRMGR_TEAM_VENUES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return RfrmgrTeamVenues.RFRMGR_TEAM_VENUES.TEAM_SEASON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return RfrmgrTeamVenues.RFRMGR_TEAM_VENUES.CONTACT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return RfrmgrTeamVenues.RFRMGR_TEAM_VENUES.NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getTeamSeasonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getContactId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrTeamVenuesRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrTeamVenuesRecord value2(UInteger value) {
        setTeamSeasonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrTeamVenuesRecord value3(UInteger value) {
        setContactId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrTeamVenuesRecord value4(UInteger value) {
        setNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrTeamVenuesRecord values(UInteger value1, UInteger value2, UInteger value3, UInteger value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RfrmgrTeamVenuesRecord
     */
    public RfrmgrTeamVenuesRecord() {
        super(RfrmgrTeamVenues.RFRMGR_TEAM_VENUES);
    }

    /**
     * Create a detached, initialised RfrmgrTeamVenuesRecord
     */
    public RfrmgrTeamVenuesRecord(UInteger id, UInteger teamSeasonId, UInteger contactId, UInteger number) {
        super(RfrmgrTeamVenues.RFRMGR_TEAM_VENUES);

        set(0, id);
        set(1, teamSeasonId);
        set(2, contactId);
        set(3, number);
    }
}
