/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables.records;


import de.edgesoft.refereemanager.jooq.tables.RfrmgrRefereeStatuses;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * Referee's status.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RfrmgrRefereeStatusesRecord extends UpdatableRecordImpl<RfrmgrRefereeStatusesRecord> implements Record5<UInteger, UInteger, UInteger, UInteger, String> {

    private static final long serialVersionUID = -21029423;

    /**
     * Setter for <code>refereemanager.rfrmgr_referee_statuses.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_referee_statuses.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_referee_statuses.referee_id</code>.
     */
    public void setRefereeId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_referee_statuses.referee_id</code>.
     */
    public UInteger getRefereeId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_referee_statuses.status_type_id</code>.
     */
    public void setStatusTypeId(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_referee_statuses.status_type_id</code>.
     */
    public UInteger getStatusTypeId() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_referee_statuses.season_id</code>.
     */
    public void setSeasonId(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_referee_statuses.season_id</code>.
     */
    public UInteger getSeasonId() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_referee_statuses.remark</code>.
     */
    public void setRemark(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_referee_statuses.remark</code>.
     */
    public String getRemark() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, UInteger, UInteger, UInteger, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, UInteger, UInteger, UInteger, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return RfrmgrRefereeStatuses.RFRMGR_REFEREE_STATUSES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return RfrmgrRefereeStatuses.RFRMGR_REFEREE_STATUSES.REFEREE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return RfrmgrRefereeStatuses.RFRMGR_REFEREE_STATUSES.STATUS_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return RfrmgrRefereeStatuses.RFRMGR_REFEREE_STATUSES.SEASON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return RfrmgrRefereeStatuses.RFRMGR_REFEREE_STATUSES.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getRefereeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getStatusTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getSeasonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrRefereeStatusesRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrRefereeStatusesRecord value2(UInteger value) {
        setRefereeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrRefereeStatusesRecord value3(UInteger value) {
        setStatusTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrRefereeStatusesRecord value4(UInteger value) {
        setSeasonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrRefereeStatusesRecord value5(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrRefereeStatusesRecord values(UInteger value1, UInteger value2, UInteger value3, UInteger value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RfrmgrRefereeStatusesRecord
     */
    public RfrmgrRefereeStatusesRecord() {
        super(RfrmgrRefereeStatuses.RFRMGR_REFEREE_STATUSES);
    }

    /**
     * Create a detached, initialised RfrmgrRefereeStatusesRecord
     */
    public RfrmgrRefereeStatusesRecord(UInteger id, UInteger refereeId, UInteger statusTypeId, UInteger seasonId, String remark) {
        super(RfrmgrRefereeStatuses.RFRMGR_REFEREE_STATUSES);

        set(0, id);
        set(1, refereeId);
        set(2, statusTypeId);
        set(3, seasonId);
        set(4, remark);
    }
}
