/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables.records;


import de.edgesoft.refereemanager.jooq.tables.RfrmgrDatabaseColumns;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * All database columns that have to be logged,
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RfrmgrDatabaseColumnsRecord extends UpdatableRecordImpl<RfrmgrDatabaseColumnsRecord> implements Record2<UInteger, String> {

    private static final long serialVersionUID = 2066459891;

    /**
     * Setter for <code>refereemanager.rfrmgr_database_columns.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_database_columns.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_database_columns.column_name</code>.
     */
    public void setColumnName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_database_columns.column_name</code>.
     */
    public String getColumnName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UInteger, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UInteger, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return RfrmgrDatabaseColumns.RFRMGR_DATABASE_COLUMNS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return RfrmgrDatabaseColumns.RFRMGR_DATABASE_COLUMNS.COLUMN_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getColumnName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrDatabaseColumnsRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrDatabaseColumnsRecord value2(String value) {
        setColumnName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrDatabaseColumnsRecord values(UInteger value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RfrmgrDatabaseColumnsRecord
     */
    public RfrmgrDatabaseColumnsRecord() {
        super(RfrmgrDatabaseColumns.RFRMGR_DATABASE_COLUMNS);
    }

    /**
     * Create a detached, initialised RfrmgrDatabaseColumnsRecord
     */
    public RfrmgrDatabaseColumnsRecord(UInteger id, String columnName) {
        super(RfrmgrDatabaseColumns.RFRMGR_DATABASE_COLUMNS);

        set(0, id);
        set(1, columnName);
    }
}
