/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables.records;


import de.edgesoft.refereemanager.jooq.tables.TournamentGames;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * Assignments for tournament games.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TournamentGamesRecord extends UpdatableRecordImpl<TournamentGamesRecord> implements Record3<UInteger, UInteger, UInteger> {

    private static final long serialVersionUID = 1514130432;

    /**
     * Setter for <code>refereemanager.rfrmgr_tournament_games.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_tournament_games.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_tournament_games.assignment_id</code>.
     */
    public void setAssignmentId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_tournament_games.assignment_id</code>.
     */
    public UInteger getAssignmentId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>refereemanager.rfrmgr_tournament_games.tournament_id</code>.
     */
    public void setTournamentId(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>refereemanager.rfrmgr_tournament_games.tournament_id</code>.
     */
    public UInteger getTournamentId() {
        return (UInteger) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, UInteger> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, UInteger> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TournamentGames.TOURNAMENT_GAMES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return TournamentGames.TOURNAMENT_GAMES.ASSIGNMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return TournamentGames.TOURNAMENT_GAMES.TOURNAMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getAssignmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getTournamentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TournamentGamesRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TournamentGamesRecord value2(UInteger value) {
        setAssignmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TournamentGamesRecord value3(UInteger value) {
        setTournamentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TournamentGamesRecord values(UInteger value1, UInteger value2, UInteger value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TournamentGamesRecord
     */
    public TournamentGamesRecord() {
        super(TournamentGames.TOURNAMENT_GAMES);
    }

    /**
     * Create a detached, initialised TournamentGamesRecord
     */
    public TournamentGamesRecord(UInteger id, UInteger assignmentId, UInteger tournamentId) {
        super(TournamentGames.TOURNAMENT_GAMES);

        set(0, id);
        set(1, assignmentId);
        set(2, tournamentId);
    }
}
