subject: Übersicht der gespeicherten Daten
subtitle: Saison **generated season:title**
opening: Hi **generated referee:firstname**,
closing: Danke, Gruß,
signature: Ekkart.

<!-- \maketitle -->

Hallo **generated referee:firstname**,

dies ist der jährliche Auszug der über Dich beim Verbandsschiedsrichterausschuss für die Saison **generated season:title** gespeicherten Daten.
Du erhältst den Auszug aus drei Gründen:

1. Damit Du weißt, welche Daten gespeichert sind, wofür sie verwendet werden und wer die Daten sieht.
2. Damit Du kontrollieren kannst, ob die Daten korrekt sind und eventuelle Änderungen mitteilen kannst.
3. Damit Du der Verwendung bestimmter Daten widersprechen kannst, falls Du das möchtest.

Noch ein kurzer Hinweis zu den Kontaktinformationen: ich hätte gerne zwei Möglichkeiten, mit Dir Kontakt aufzunehmen, bevorzugt per E-Mail und Telefon.
Die dritte Möglichkeit ist daher optional.

# Öffentliche Informationen

Diese Informationen sind für jedermann sichtbar.

Nutzungsbeispiel: Einsatzplan.

<!--
\begin{longtabu}[l]{@{}>{\small\sffamily\bfseries}p{.28\textwidth}@{\hspace{.02\textwidth}}p{.7\textwidth}@{}}
	\toprule
	-->Name<!-- & -->**generated referee:tablename**<!-- \\
	-->Ausbildung<!-- & -->**generated referee:highesttraininglevel:type:title** (**generated referee:highesttraininglevel:type:shorttitle**)<!-- \\
	-->Einsatzhäufigkeit<!-- & -->**generated referee:status:title**<!-- \\
	\bottomrule
\end{longtabu}
-->

# Informationen für andere Schiedsrichter

Diese Informationen sind nur für andere Schiedsrichter nach Login und den DTTB sichtbar.

Nutzungsbeispiel: Kontakttabelle der Schiedsrichter.

<!--
\begin{longtabu}[l]{@{}>{\small\sffamily\bfseries}p{.28\textwidth}@{\hspace{.02\textwidth}}p{.7\textwidth}@{}}
	\toprule
	-->E-Mail<!-- & -->**if empty referee:email:**---**end if empty referee:email:****foreach referee:email:****separator**, **end separator****generated referee:email:displaytitle****if notempty referee:email:editoronly** (privat = nur für VSRA sichtbar, nicht für andere Schiedsrichter)**end if notempty referee:email:editoronly****end foreach referee:email:**<!-- \\
	-->Telefon<!-- & -->**if empty referee:phonenumber:**---**end if empty referee:phonenumber:****foreach referee:phonenumber:****separator**, **end separator****generated referee:phonenumber:displaytitle****if notempty referee:phonenumber:editoronly** (privat = nur für VSRA sichtbar, nicht für andere Schiedsrichter)**end if notempty referee:phonenumber:editoronly****end foreach referee:phonenumber:**<!-- \\
	-->Mitglied bei<!-- & -->**generated referee:referee_relation_member**<!-- \\
	**ifnotempty referee:referee_relation_reffor**-->Schiedst für<!-- & -->**generated referee:referee_relation_reffor**<!-- \\**endnotempty referee:referee_relation_reffor**
	\bottomrule
\end{longtabu}
-->

# Informationen für VSRA

Diese Informationen sind nur für den Verbandsschiedsrichterausschuss sichtbar.

Nutzungsbeispiel: Verwaltung der Einsätze.

<!--
\begin{longtabu}[l]{@{}>{\small\sffamily\bfseries}p{.28\textwidth}@{\hspace{.02\textwidth}}p{.7\textwidth}@{}}
	\toprule
	**ifnotempty referee:docs_per_letter**-->Alle Infos per Brief<!-- & -->ja**ifnotempty contacts:emails** *Bitte prüfen, ob die Zusendung per E-Mail nicht doch ausreicht.* **endnotempty contacts:emails**<!-- \\**endnotempty referee:docs_per_letter**
	-->Adresse<!-- & -->**ifempty contacts:addresses_fulladdress**---**endempty contacts:addresses_fulladdress****generated contacts:addresses_fulladdress**<!-- \\
	-->URL<!-- & -->**ifempty contacts:urls**---**endempty contacts:urls****generated contacts:urls**<!-- \\
	-->Geburtstag<!-- & -->**ifempty referee:birthday**---**endempty referee:birthday****generated referee:birthday**<!-- \\
	-->Geschlecht<!-- & -->**generated sextype:title**<!-- \\
	-->Bevorzugt schiedsen<!-- & -->**ifempty referee:referee_relation_prefer**---**endempty referee:referee_relation_prefer****generated referee:referee_relation_prefer**<!-- \\
	-->Nicht schiedsen<!-- & -->**ifempty referee:referee_relation_noassignment**---**endempty referee:referee_relation_noassignment****generated referee:referee_relation_noassignment**<!-- \\
	-->**generated traininglevel:abbreviation** seit<!-- & -->**ifempty traininglevel:since**---**endempty traininglevel:since****generated traininglevel:since**<!-- \\
	-->Letzte Fortbildung<!-- & -->**ifempty traininglevel:lasttrainingupdate**---**endempty traininglevel:lasttrainingupdate****generated traininglevel:lasttrainingupdate**<!-- \\
	-->Nächste Fortbildung<!-- & -->**ifempty traininglevel:nexttrainingupdate**---**endempty traininglevel:nexttrainingupdate****generated traininglevel:nexttrainingupdate**<!-- \\
	-->Anmerkung<!-- & -->**generated referee:remark** **generated refereestatus:**generated season:id**:remark**<!-- \\
	\bottomrule
\end{longtabu}
-->
