/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables;


import de.edgesoft.refereemanager.jooq.Keys;
import de.edgesoft.refereemanager.jooq.Refereemanager;
import de.edgesoft.refereemanager.jooq.tables.records.ContactTypesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * Possible types of contacts, such as private, working.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContactTypes extends TableImpl<ContactTypesRecord> {

    private static final long serialVersionUID = -1481411057;

    /**
     * The reference instance of <code>refereemanager.rfrmgr_contact_types</code>
     */
    public static final ContactTypes CONTACT_TYPES = new ContactTypes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContactTypesRecord> getRecordType() {
        return ContactTypesRecord.class;
    }

    /**
     * The column <code>refereemanager.rfrmgr_contact_types.id</code>.
     */
    public final TableField<ContactTypesRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_contact_types.title</code>.
     */
    public final TableField<ContactTypesRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_contact_types.abbreviation</code>.
     */
    public final TableField<ContactTypesRecord, String> ABBREVIATION = createField("abbreviation", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_contact_types.remark</code>.
     */
    public final TableField<ContactTypesRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>refereemanager.rfrmgr_contact_types</code> table reference
     */
    public ContactTypes() {
        this("rfrmgr_contact_types", null);
    }

    /**
     * Create an aliased <code>refereemanager.rfrmgr_contact_types</code> table reference
     */
    public ContactTypes(String alias) {
        this(alias, CONTACT_TYPES);
    }

    private ContactTypes(String alias, Table<ContactTypesRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContactTypes(String alias, Table<ContactTypesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "Possible types of contacts, such as private, working.");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Refereemanager.REFEREEMANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContactTypesRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_CONTACT_TYPES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContactTypesRecord> getPrimaryKey() {
        return Keys.KEY_RFRMGR_CONTACT_TYPES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContactTypesRecord>> getKeys() {
        return Arrays.<UniqueKey<ContactTypesRecord>>asList(Keys.KEY_RFRMGR_CONTACT_TYPES_PRIMARY, Keys.KEY_RFRMGR_CONTACT_TYPES_ID_UNIQUE, Keys.KEY_RFRMGR_CONTACT_TYPES_SID_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactTypes as(String alias) {
        return new ContactTypes(alias, this);
    }

    /**
     * Rename this table
     */
    public ContactTypes rename(String name) {
        return new ContactTypes(name, null);
    }
}
