/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables;


import de.edgesoft.refereemanager.jooq.Keys;
import de.edgesoft.refereemanager.jooq.Refereemanager;
import de.edgesoft.refereemanager.jooq.tables.records.LeaguesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * All leagues.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Leagues extends TableImpl<LeaguesRecord> {

    private static final long serialVersionUID = 1159004560;

    /**
     * The reference instance of <code>refereemanager.rfrmgr_leagues</code>
     */
    public static final Leagues LEAGUES = new Leagues();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LeaguesRecord> getRecordType() {
        return LeaguesRecord.class;
    }

    /**
     * The column <code>refereemanager.rfrmgr_leagues.id</code>.
     */
    public final TableField<LeaguesRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_leagues.title</code>.
     */
    public final TableField<LeaguesRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_leagues.abbreviation</code>.
     */
    public final TableField<LeaguesRecord, String> ABBREVIATION = createField("abbreviation", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_leagues.league_type_id</code>.
     */
    public final TableField<LeaguesRecord, UInteger> LEAGUE_TYPE_ID = createField("league_type_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_leagues.remark</code>.
     */
    public final TableField<LeaguesRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>refereemanager.rfrmgr_leagues</code> table reference
     */
    public Leagues() {
        this("rfrmgr_leagues", null);
    }

    /**
     * Create an aliased <code>refereemanager.rfrmgr_leagues</code> table reference
     */
    public Leagues(String alias) {
        this(alias, LEAGUES);
    }

    private Leagues(String alias, Table<LeaguesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Leagues(String alias, Table<LeaguesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "All leagues.");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Refereemanager.REFEREEMANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<LeaguesRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_LEAGUES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LeaguesRecord> getPrimaryKey() {
        return Keys.KEY_RFRMGR_LEAGUES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LeaguesRecord>> getKeys() {
        return Arrays.<UniqueKey<LeaguesRecord>>asList(Keys.KEY_RFRMGR_LEAGUES_PRIMARY, Keys.KEY_RFRMGR_LEAGUES_ID_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Leagues as(String alias) {
        return new Leagues(alias, this);
    }

    /**
     * Rename this table
     */
    public Leagues rename(String name) {
        return new Leagues(name, null);
    }
}
