/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables;


import de.edgesoft.refereemanager.jooq.Keys;
import de.edgesoft.refereemanager.jooq.Refereemanager;
import de.edgesoft.refereemanager.jooq.tables.records.PhoneNumbersRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * All phone numbers.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PhoneNumbers extends TableImpl<PhoneNumbersRecord> {

    private static final long serialVersionUID = 1793034820;

    /**
     * The reference instance of <code>refereemanager.rfrmgr_phone_numbers</code>
     */
    public static final PhoneNumbers RFRMGR_PHONE_NUMBERS = new PhoneNumbers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PhoneNumbersRecord> getRecordType() {
        return PhoneNumbersRecord.class;
    }

    /**
     * The column <code>refereemanager.rfrmgr_phone_numbers.id</code>.
     */
    public final TableField<PhoneNumbersRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_phone_numbers.contact_id</code>.
     */
    public final TableField<PhoneNumbersRecord, UInteger> CONTACT_ID = createField("contact_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_phone_numbers.country_code</code>.
     */
    public final TableField<PhoneNumbersRecord, String> COUNTRY_CODE = createField("country_code", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_phone_numbers.area_code</code>.
     */
    public final TableField<PhoneNumbersRecord, String> AREA_CODE = createField("area_code", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_phone_numbers.number</code>.
     */
    public final TableField<PhoneNumbersRecord, String> NUMBER = createField("number", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * Create a <code>refereemanager.rfrmgr_phone_numbers</code> table reference
     */
    public PhoneNumbers() {
        this("rfrmgr_phone_numbers", null);
    }

    /**
     * Create an aliased <code>refereemanager.rfrmgr_phone_numbers</code> table reference
     */
    public PhoneNumbers(String alias) {
        this(alias, RFRMGR_PHONE_NUMBERS);
    }

    private PhoneNumbers(String alias, Table<PhoneNumbersRecord> aliased) {
        this(alias, aliased, null);
    }

    private PhoneNumbers(String alias, Table<PhoneNumbersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "All phone numbers.");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Refereemanager.REFEREEMANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PhoneNumbersRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_RFRMGR_PHONE_NUMBERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PhoneNumbersRecord> getPrimaryKey() {
        return Keys.KEY_RFRMGR_PHONE_NUMBERS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PhoneNumbersRecord>> getKeys() {
        return Arrays.<UniqueKey<PhoneNumbersRecord>>asList(Keys.KEY_RFRMGR_PHONE_NUMBERS_PRIMARY, Keys.KEY_RFRMGR_PHONE_NUMBERS_ID_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhoneNumbers as(String alias) {
        return new PhoneNumbers(alias, this);
    }

    /**
     * Rename this table
     */
    public PhoneNumbers rename(String name) {
        return new PhoneNumbers(name, null);
    }
}
