/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables;


import de.edgesoft.refereemanager.jooq.Keys;
import de.edgesoft.refereemanager.jooq.Refereemanager;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrEmailsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * All email adresses.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RfrmgrEmails extends TableImpl<RfrmgrEmailsRecord> {

    private static final long serialVersionUID = -1298873383;

    /**
     * The reference instance of <code>refereemanager.rfrmgr_emails</code>
     */
    public static final RfrmgrEmails RFRMGR_EMAILS = new RfrmgrEmails();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RfrmgrEmailsRecord> getRecordType() {
        return RfrmgrEmailsRecord.class;
    }

    /**
     * The column <code>refereemanager.rfrmgr_emails.id</code>.
     */
    public final TableField<RfrmgrEmailsRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_emails.contact_id</code>.
     */
    public final TableField<RfrmgrEmailsRecord, UInteger> CONTACT_ID = createField("contact_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_emails.email</code>.
     */
    public final TableField<RfrmgrEmailsRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * Create a <code>refereemanager.rfrmgr_emails</code> table reference
     */
    public RfrmgrEmails() {
        this("rfrmgr_emails", null);
    }

    /**
     * Create an aliased <code>refereemanager.rfrmgr_emails</code> table reference
     */
    public RfrmgrEmails(String alias) {
        this(alias, RFRMGR_EMAILS);
    }

    private RfrmgrEmails(String alias, Table<RfrmgrEmailsRecord> aliased) {
        this(alias, aliased, null);
    }

    private RfrmgrEmails(String alias, Table<RfrmgrEmailsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "All email adresses.");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Refereemanager.REFEREEMANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RfrmgrEmailsRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_RFRMGR_EMAILS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RfrmgrEmailsRecord> getPrimaryKey() {
        return Keys.KEY_RFRMGR_EMAILS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RfrmgrEmailsRecord>> getKeys() {
        return Arrays.<UniqueKey<RfrmgrEmailsRecord>>asList(Keys.KEY_RFRMGR_EMAILS_PRIMARY, Keys.KEY_RFRMGR_EMAILS_ID_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrEmails as(String alias) {
        return new RfrmgrEmails(alias, this);
    }

    /**
     * Rename this table
     */
    public RfrmgrEmails rename(String name) {
        return new RfrmgrEmails(name, null);
    }
}
