/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables;


import de.edgesoft.refereemanager.jooq.Keys;
import de.edgesoft.refereemanager.jooq.Refereemanager;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrRefereesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * Storage of all referees.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RfrmgrReferees extends TableImpl<RfrmgrRefereesRecord> {

    private static final long serialVersionUID = -726420110;

    /**
     * The reference instance of <code>refereemanager.rfrmgr_referees</code>
     */
    public static final RfrmgrReferees RFRMGR_REFEREES = new RfrmgrReferees();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RfrmgrRefereesRecord> getRecordType() {
        return RfrmgrRefereesRecord.class;
    }

    /**
     * The column <code>refereemanager.rfrmgr_referees.id</code>.
     */
    public final TableField<RfrmgrRefereesRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_referees.person_id</code>.
     */
    public final TableField<RfrmgrRefereesRecord, UInteger> PERSON_ID = createField("person_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_referees.docs_per_letter</code>.
     */
    public final TableField<RfrmgrRefereesRecord, Byte> DOCS_PER_LETTER = createField("docs_per_letter", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * Create a <code>refereemanager.rfrmgr_referees</code> table reference
     */
    public RfrmgrReferees() {
        this("rfrmgr_referees", null);
    }

    /**
     * Create an aliased <code>refereemanager.rfrmgr_referees</code> table reference
     */
    public RfrmgrReferees(String alias) {
        this(alias, RFRMGR_REFEREES);
    }

    private RfrmgrReferees(String alias, Table<RfrmgrRefereesRecord> aliased) {
        this(alias, aliased, null);
    }

    private RfrmgrReferees(String alias, Table<RfrmgrRefereesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "Storage of all referees.");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Refereemanager.REFEREEMANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RfrmgrRefereesRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_RFRMGR_REFEREES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RfrmgrRefereesRecord> getPrimaryKey() {
        return Keys.KEY_RFRMGR_REFEREES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RfrmgrRefereesRecord>> getKeys() {
        return Arrays.<UniqueKey<RfrmgrRefereesRecord>>asList(Keys.KEY_RFRMGR_REFEREES_PRIMARY, Keys.KEY_RFRMGR_REFEREES_ID_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrReferees as(String alias) {
        return new RfrmgrReferees(alias, this);
    }

    /**
     * Rename this table
     */
    public RfrmgrReferees rename(String name) {
        return new RfrmgrReferees(name, null);
    }
}
