/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables;


import de.edgesoft.refereemanager.jooq.Keys;
import de.edgesoft.refereemanager.jooq.Refereemanager;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrRefereeReportRecipientsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * All league types.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RfrmgrRefereeReportRecipients extends TableImpl<RfrmgrRefereeReportRecipientsRecord> {

    private static final long serialVersionUID = -514661433;

    /**
     * The reference instance of <code>refereemanager.rfrmgr_referee_report_recipients</code>
     */
    public static final RfrmgrRefereeReportRecipients RFRMGR_REFEREE_REPORT_RECIPIENTS = new RfrmgrRefereeReportRecipients();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RfrmgrRefereeReportRecipientsRecord> getRecordType() {
        return RfrmgrRefereeReportRecipientsRecord.class;
    }

    /**
     * The column <code>refereemanager.rfrmgr_referee_report_recipients.id</code>.
     */
    public final TableField<RfrmgrRefereeReportRecipientsRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_referee_report_recipients.referee_report_id</code>.
     */
    public final TableField<RfrmgrRefereeReportRecipientsRecord, Integer> REFEREE_REPORT_ID = createField("referee_report_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_referee_report_recipients.person_id</code>.
     */
    public final TableField<RfrmgrRefereeReportRecipientsRecord, Integer> PERSON_ID = createField("person_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>refereemanager.rfrmgr_referee_report_recipients</code> table reference
     */
    public RfrmgrRefereeReportRecipients() {
        this("rfrmgr_referee_report_recipients", null);
    }

    /**
     * Create an aliased <code>refereemanager.rfrmgr_referee_report_recipients</code> table reference
     */
    public RfrmgrRefereeReportRecipients(String alias) {
        this(alias, RFRMGR_REFEREE_REPORT_RECIPIENTS);
    }

    private RfrmgrRefereeReportRecipients(String alias, Table<RfrmgrRefereeReportRecipientsRecord> aliased) {
        this(alias, aliased, null);
    }

    private RfrmgrRefereeReportRecipients(String alias, Table<RfrmgrRefereeReportRecipientsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "All league types.");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Refereemanager.REFEREEMANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RfrmgrRefereeReportRecipientsRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_RFRMGR_REFEREE_REPORT_RECIPIENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RfrmgrRefereeReportRecipientsRecord> getPrimaryKey() {
        return Keys.KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RfrmgrRefereeReportRecipientsRecord>> getKeys() {
        return Arrays.<UniqueKey<RfrmgrRefereeReportRecipientsRecord>>asList(Keys.KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_PRIMARY, Keys.KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_ID_UNIQUE, Keys.KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_TITLE_UNIQUE, Keys.KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_PERSON_ID_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrRefereeReportRecipients as(String alias) {
        return new RfrmgrRefereeReportRecipients(alias, this);
    }

    /**
     * Rename this table
     */
    public RfrmgrRefereeReportRecipients rename(String name) {
        return new RfrmgrRefereeReportRecipients(name, null);
    }
}
