/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables;


import de.edgesoft.refereemanager.jooq.Keys;
import de.edgesoft.refereemanager.jooq.Refereemanager;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrTrainingLevelsRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * Achieved training levels for referees.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RfrmgrTrainingLevels extends TableImpl<RfrmgrTrainingLevelsRecord> {

    private static final long serialVersionUID = 574385011;

    /**
     * The reference instance of <code>refereemanager.rfrmgr_training_levels</code>
     */
    public static final RfrmgrTrainingLevels RFRMGR_TRAINING_LEVELS = new RfrmgrTrainingLevels();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RfrmgrTrainingLevelsRecord> getRecordType() {
        return RfrmgrTrainingLevelsRecord.class;
    }

    /**
     * The column <code>refereemanager.rfrmgr_training_levels.id</code>.
     */
    public final TableField<RfrmgrTrainingLevelsRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_training_levels.referee_id</code>.
     */
    public final TableField<RfrmgrTrainingLevelsRecord, UInteger> REFEREE_ID = createField("referee_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_training_levels.training_level_type_id</code>.
     */
    public final TableField<RfrmgrTrainingLevelsRecord, UInteger> TRAINING_LEVEL_TYPE_ID = createField("training_level_type_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_training_levels.since</code>.
     */
    public final TableField<RfrmgrTrainingLevelsRecord, Date> SINCE = createField("since", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * Create a <code>refereemanager.rfrmgr_training_levels</code> table reference
     */
    public RfrmgrTrainingLevels() {
        this("rfrmgr_training_levels", null);
    }

    /**
     * Create an aliased <code>refereemanager.rfrmgr_training_levels</code> table reference
     */
    public RfrmgrTrainingLevels(String alias) {
        this(alias, RFRMGR_TRAINING_LEVELS);
    }

    private RfrmgrTrainingLevels(String alias, Table<RfrmgrTrainingLevelsRecord> aliased) {
        this(alias, aliased, null);
    }

    private RfrmgrTrainingLevels(String alias, Table<RfrmgrTrainingLevelsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "Achieved training levels for referees.");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Refereemanager.REFEREEMANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RfrmgrTrainingLevelsRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_RFRMGR_TRAINING_LEVELS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RfrmgrTrainingLevelsRecord> getPrimaryKey() {
        return Keys.KEY_RFRMGR_TRAINING_LEVELS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RfrmgrTrainingLevelsRecord>> getKeys() {
        return Arrays.<UniqueKey<RfrmgrTrainingLevelsRecord>>asList(Keys.KEY_RFRMGR_TRAINING_LEVELS_PRIMARY, Keys.KEY_RFRMGR_TRAINING_LEVELS_ID_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrTrainingLevels as(String alias) {
        return new RfrmgrTrainingLevels(alias, this);
    }

    /**
     * Rename this table
     */
    public RfrmgrTrainingLevels rename(String name) {
        return new RfrmgrTrainingLevels(name, null);
    }
}
