/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables;


import de.edgesoft.refereemanager.jooq.Keys;
import de.edgesoft.refereemanager.jooq.Refereemanager;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrTrainingLevelTypesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * Possible training levels such as international referee, Germ / * comment 
 * truncated * / / *an referee.* /
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RfrmgrTrainingLevelTypes extends TableImpl<RfrmgrTrainingLevelTypesRecord> {

    private static final long serialVersionUID = -1847232599;

    /**
     * The reference instance of <code>refereemanager.rfrmgr_training_level_types</code>
     */
    public static final RfrmgrTrainingLevelTypes RFRMGR_TRAINING_LEVEL_TYPES = new RfrmgrTrainingLevelTypes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RfrmgrTrainingLevelTypesRecord> getRecordType() {
        return RfrmgrTrainingLevelTypesRecord.class;
    }

    /**
     * The column <code>refereemanager.rfrmgr_training_level_types.id</code>.
     */
    public final TableField<RfrmgrTrainingLevelTypesRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_training_level_types.sid</code>.
     */
    public final TableField<RfrmgrTrainingLevelTypesRecord, String> SID = createField("sid", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_training_level_types.rank</code>.
     */
    public final TableField<RfrmgrTrainingLevelTypesRecord, UInteger> RANK = createField("rank", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_training_level_types.title</code>.
     */
    public final TableField<RfrmgrTrainingLevelTypesRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_training_level_types.abbreviation</code>.
     */
    public final TableField<RfrmgrTrainingLevelTypesRecord, String> ABBREVIATION = createField("abbreviation", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_training_level_types.update_interval</code>.
     */
    public final TableField<RfrmgrTrainingLevelTypesRecord, UInteger> UPDATE_INTERVAL = createField("update_interval", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_training_level_types.remark</code>.
     */
    public final TableField<RfrmgrTrainingLevelTypesRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>refereemanager.rfrmgr_training_level_types</code> table reference
     */
    public RfrmgrTrainingLevelTypes() {
        this("rfrmgr_training_level_types", null);
    }

    /**
     * Create an aliased <code>refereemanager.rfrmgr_training_level_types</code> table reference
     */
    public RfrmgrTrainingLevelTypes(String alias) {
        this(alias, RFRMGR_TRAINING_LEVEL_TYPES);
    }

    private RfrmgrTrainingLevelTypes(String alias, Table<RfrmgrTrainingLevelTypesRecord> aliased) {
        this(alias, aliased, null);
    }

    private RfrmgrTrainingLevelTypes(String alias, Table<RfrmgrTrainingLevelTypesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "Possible training levels such as international referee, Germ /* comment truncated */ /*an referee.*/");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Refereemanager.REFEREEMANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RfrmgrTrainingLevelTypesRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_RFRMGR_TRAINING_LEVEL_TYPES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RfrmgrTrainingLevelTypesRecord> getPrimaryKey() {
        return Keys.KEY_RFRMGR_TRAINING_LEVEL_TYPES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RfrmgrTrainingLevelTypesRecord>> getKeys() {
        return Arrays.<UniqueKey<RfrmgrTrainingLevelTypesRecord>>asList(Keys.KEY_RFRMGR_TRAINING_LEVEL_TYPES_PRIMARY, Keys.KEY_RFRMGR_TRAINING_LEVEL_TYPES_ID_UNIQUE, Keys.KEY_RFRMGR_TRAINING_LEVEL_TYPES_SID_UNIQUE, Keys.KEY_RFRMGR_TRAINING_LEVEL_TYPES_RANK_UNIQUE, Keys.KEY_RFRMGR_TRAINING_LEVEL_TYPES_TITLE_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrTrainingLevelTypes as(String alias) {
        return new RfrmgrTrainingLevelTypes(alias, this);
    }

    /**
     * Rename this table
     */
    public RfrmgrTrainingLevelTypes rename(String name) {
        return new RfrmgrTrainingLevelTypes(name, null);
    }
}
