/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables;


import de.edgesoft.refereemanager.jooq.Keys;
import de.edgesoft.refereemanager.jooq.Refereemanager;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrStatusTypesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * Possible referee statuses such as "interested in many assign / * comment 
 * truncated * / / *ments", "not active", etc.* /
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RfrmgrStatusTypes extends TableImpl<RfrmgrStatusTypesRecord> {

    private static final long serialVersionUID = 324735983;

    /**
     * The reference instance of <code>refereemanager.rfrmgr_status_types</code>
     */
    public static final RfrmgrStatusTypes RFRMGR_STATUS_TYPES = new RfrmgrStatusTypes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RfrmgrStatusTypesRecord> getRecordType() {
        return RfrmgrStatusTypesRecord.class;
    }

    /**
     * The column <code>refereemanager.rfrmgr_status_types.id</code>.
     */
    public final TableField<RfrmgrStatusTypesRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_status_types.sid</code>.
     */
    public final TableField<RfrmgrStatusTypesRecord, String> SID = createField("sid", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_status_types.title</code>.
     */
    public final TableField<RfrmgrStatusTypesRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_status_types.remark</code>.
     */
    public final TableField<RfrmgrStatusTypesRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>refereemanager.rfrmgr_status_types</code> table reference
     */
    public RfrmgrStatusTypes() {
        this("rfrmgr_status_types", null);
    }

    /**
     * Create an aliased <code>refereemanager.rfrmgr_status_types</code> table reference
     */
    public RfrmgrStatusTypes(String alias) {
        this(alias, RFRMGR_STATUS_TYPES);
    }

    private RfrmgrStatusTypes(String alias, Table<RfrmgrStatusTypesRecord> aliased) {
        this(alias, aliased, null);
    }

    private RfrmgrStatusTypes(String alias, Table<RfrmgrStatusTypesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "Possible referee statuses such as \"interested in many assign /* comment truncated */ /*ments\", \"not active\", etc.*/");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Refereemanager.REFEREEMANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RfrmgrStatusTypesRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_RFRMGR_STATUS_TYPES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RfrmgrStatusTypesRecord> getPrimaryKey() {
        return Keys.KEY_RFRMGR_STATUS_TYPES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RfrmgrStatusTypesRecord>> getKeys() {
        return Arrays.<UniqueKey<RfrmgrStatusTypesRecord>>asList(Keys.KEY_RFRMGR_STATUS_TYPES_PRIMARY, Keys.KEY_RFRMGR_STATUS_TYPES_ID_UNIQUE, Keys.KEY_RFRMGR_STATUS_TYPES_SID_UNIQUE, Keys.KEY_RFRMGR_STATUS_TYPES_TITLE_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrStatusTypes as(String alias) {
        return new RfrmgrStatusTypes(alias, this);
    }

    /**
     * Rename this table
     */
    public RfrmgrStatusTypes rename(String name) {
        return new RfrmgrStatusTypes(name, null);
    }
}
