/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables;


import de.edgesoft.refereemanager.jooq.Keys;
import de.edgesoft.refereemanager.jooq.Refereemanager;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrLeaguePlannedRefereesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * Planned numbers of referees by assignment type.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RfrmgrLeaguePlannedReferees extends TableImpl<RfrmgrLeaguePlannedRefereesRecord> {

    private static final long serialVersionUID = 408554042;

    /**
     * The reference instance of <code>refereemanager.rfrmgr_league_planned_referees</code>
     */
    public static final RfrmgrLeaguePlannedReferees RFRMGR_LEAGUE_PLANNED_REFEREES = new RfrmgrLeaguePlannedReferees();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RfrmgrLeaguePlannedRefereesRecord> getRecordType() {
        return RfrmgrLeaguePlannedRefereesRecord.class;
    }

    /**
     * The column <code>refereemanager.rfrmgr_league_planned_referees.id</code>.
     */
    public final TableField<RfrmgrLeaguePlannedRefereesRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_league_planned_referees.league_id</code>.
     */
    public final TableField<RfrmgrLeaguePlannedRefereesRecord, UInteger> LEAGUE_ID = createField("league_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_league_planned_referees.season_id</code>.
     */
    public final TableField<RfrmgrLeaguePlannedRefereesRecord, UInteger> SEASON_ID = createField("season_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_league_planned_referees.referee_assignment_type_id</code>.
     */
    public final TableField<RfrmgrLeaguePlannedRefereesRecord, UInteger> REFEREE_ASSIGNMENT_TYPE_ID = createField("referee_assignment_type_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_league_planned_referees.quantity</code>.
     */
    public final TableField<RfrmgrLeaguePlannedRefereesRecord, UInteger> QUANTITY = createField("quantity", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>refereemanager.rfrmgr_league_planned_referees</code> table reference
     */
    public RfrmgrLeaguePlannedReferees() {
        this("rfrmgr_league_planned_referees", null);
    }

    /**
     * Create an aliased <code>refereemanager.rfrmgr_league_planned_referees</code> table reference
     */
    public RfrmgrLeaguePlannedReferees(String alias) {
        this(alias, RFRMGR_LEAGUE_PLANNED_REFEREES);
    }

    private RfrmgrLeaguePlannedReferees(String alias, Table<RfrmgrLeaguePlannedRefereesRecord> aliased) {
        this(alias, aliased, null);
    }

    private RfrmgrLeaguePlannedReferees(String alias, Table<RfrmgrLeaguePlannedRefereesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "Planned numbers of referees by assignment type.");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Refereemanager.REFEREEMANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RfrmgrLeaguePlannedRefereesRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_RFRMGR_LEAGUE_PLANNED_REFEREES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RfrmgrLeaguePlannedRefereesRecord> getPrimaryKey() {
        return Keys.KEY_RFRMGR_LEAGUE_PLANNED_REFEREES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RfrmgrLeaguePlannedRefereesRecord>> getKeys() {
        return Arrays.<UniqueKey<RfrmgrLeaguePlannedRefereesRecord>>asList(Keys.KEY_RFRMGR_LEAGUE_PLANNED_REFEREES_PRIMARY, Keys.KEY_RFRMGR_LEAGUE_PLANNED_REFEREES_ID_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrLeaguePlannedReferees as(String alias) {
        return new RfrmgrLeaguePlannedReferees(alias, this);
    }

    /**
     * Rename this table
     */
    public RfrmgrLeaguePlannedReferees rename(String name) {
        return new RfrmgrLeaguePlannedReferees(name, null);
    }
}
