/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables;


import de.edgesoft.refereemanager.jooq.Keys;
import de.edgesoft.refereemanager.jooq.Refereemanager;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrLeagueTypesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * All league types.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RfrmgrLeagueTypes extends TableImpl<RfrmgrLeagueTypesRecord> {

    private static final long serialVersionUID = 1373678271;

    /**
     * The reference instance of <code>refereemanager.rfrmgr_league_types</code>
     */
    public static final RfrmgrLeagueTypes RFRMGR_LEAGUE_TYPES = new RfrmgrLeagueTypes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RfrmgrLeagueTypesRecord> getRecordType() {
        return RfrmgrLeagueTypesRecord.class;
    }

    /**
     * The column <code>refereemanager.rfrmgr_league_types.id</code>.
     */
    public final TableField<RfrmgrLeagueTypesRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_league_types.title</code>.
     */
    public final TableField<RfrmgrLeagueTypesRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_league_types.sex_type_id</code>.
     */
    public final TableField<RfrmgrLeagueTypesRecord, UInteger> SEX_TYPE_ID = createField("sex_type_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_league_types.remark</code>.
     */
    public final TableField<RfrmgrLeagueTypesRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>refereemanager.rfrmgr_league_types</code> table reference
     */
    public RfrmgrLeagueTypes() {
        this("rfrmgr_league_types", null);
    }

    /**
     * Create an aliased <code>refereemanager.rfrmgr_league_types</code> table reference
     */
    public RfrmgrLeagueTypes(String alias) {
        this(alias, RFRMGR_LEAGUE_TYPES);
    }

    private RfrmgrLeagueTypes(String alias, Table<RfrmgrLeagueTypesRecord> aliased) {
        this(alias, aliased, null);
    }

    private RfrmgrLeagueTypes(String alias, Table<RfrmgrLeagueTypesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "All league types.");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Refereemanager.REFEREEMANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RfrmgrLeagueTypesRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_RFRMGR_LEAGUE_TYPES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RfrmgrLeagueTypesRecord> getPrimaryKey() {
        return Keys.KEY_RFRMGR_LEAGUE_TYPES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RfrmgrLeagueTypesRecord>> getKeys() {
        return Arrays.<UniqueKey<RfrmgrLeagueTypesRecord>>asList(Keys.KEY_RFRMGR_LEAGUE_TYPES_PRIMARY, Keys.KEY_RFRMGR_LEAGUE_TYPES_ID_UNIQUE, Keys.KEY_RFRMGR_LEAGUE_TYPES_TITLE_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrLeagueTypes as(String alias) {
        return new RfrmgrLeagueTypes(alias, this);
    }

    /**
     * Rename this table
     */
    public RfrmgrLeagueTypes rename(String name) {
        return new RfrmgrLeagueTypes(name, null);
    }
}
