/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables;


import de.edgesoft.refereemanager.jooq.Keys;
import de.edgesoft.refereemanager.jooq.Refereemanager;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrRefereeRelationTypesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * Club relations of a referee: member, reffor.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RfrmgrRefereeRelationTypes extends TableImpl<RfrmgrRefereeRelationTypesRecord> {

    private static final long serialVersionUID = 906741123;

    /**
     * The reference instance of <code>refereemanager.rfrmgr_referee_relation_types</code>
     */
    public static final RfrmgrRefereeRelationTypes RFRMGR_REFEREE_RELATION_TYPES = new RfrmgrRefereeRelationTypes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RfrmgrRefereeRelationTypesRecord> getRecordType() {
        return RfrmgrRefereeRelationTypesRecord.class;
    }

    /**
     * The column <code>refereemanager.rfrmgr_referee_relation_types.id</code>.
     */
    public final TableField<RfrmgrRefereeRelationTypesRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_referee_relation_types.sid</code>.
     */
    public final TableField<RfrmgrRefereeRelationTypesRecord, String> SID = createField("sid", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_referee_relation_types.title</code>.
     */
    public final TableField<RfrmgrRefereeRelationTypesRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_referee_relation_types.remark</code>.
     */
    public final TableField<RfrmgrRefereeRelationTypesRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>refereemanager.rfrmgr_referee_relation_types</code> table reference
     */
    public RfrmgrRefereeRelationTypes() {
        this("rfrmgr_referee_relation_types", null);
    }

    /**
     * Create an aliased <code>refereemanager.rfrmgr_referee_relation_types</code> table reference
     */
    public RfrmgrRefereeRelationTypes(String alias) {
        this(alias, RFRMGR_REFEREE_RELATION_TYPES);
    }

    private RfrmgrRefereeRelationTypes(String alias, Table<RfrmgrRefereeRelationTypesRecord> aliased) {
        this(alias, aliased, null);
    }

    private RfrmgrRefereeRelationTypes(String alias, Table<RfrmgrRefereeRelationTypesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "Club relations of a referee: member, reffor.");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Refereemanager.REFEREEMANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RfrmgrRefereeRelationTypesRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_RFRMGR_REFEREE_RELATION_TYPES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RfrmgrRefereeRelationTypesRecord> getPrimaryKey() {
        return Keys.KEY_RFRMGR_REFEREE_RELATION_TYPES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RfrmgrRefereeRelationTypesRecord>> getKeys() {
        return Arrays.<UniqueKey<RfrmgrRefereeRelationTypesRecord>>asList(Keys.KEY_RFRMGR_REFEREE_RELATION_TYPES_PRIMARY, Keys.KEY_RFRMGR_REFEREE_RELATION_TYPES_ID_UNIQUE, Keys.KEY_RFRMGR_REFEREE_RELATION_TYPES_SID_UNIQUE, Keys.KEY_RFRMGR_REFEREE_RELATION_TYPES_TITLE_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RfrmgrRefereeRelationTypes as(String alias) {
        return new RfrmgrRefereeRelationTypes(alias, this);
    }

    /**
     * Rename this table
     */
    public RfrmgrRefereeRelationTypes rename(String name) {
        return new RfrmgrRefereeRelationTypes(name, null);
    }
}
