/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables;


import de.edgesoft.refereemanager.jooq.Keys;
import de.edgesoft.refereemanager.jooq.Refereemanager;
import de.edgesoft.refereemanager.jooq.tables.records.SpokespeopleRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * Spokespeople of teams and clubs.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Spokespeople extends TableImpl<SpokespeopleRecord> {

    private static final long serialVersionUID = -1533209320;

    /**
     * The reference instance of <code>refereemanager.rfrmgr_spokespeople</code>
     */
    public static final Spokespeople SPOKESPEOPLE = new Spokespeople();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpokespeopleRecord> getRecordType() {
        return SpokespeopleRecord.class;
    }

    /**
     * The column <code>refereemanager.rfrmgr_spokespeople.id</code>.
     */
    public final TableField<SpokespeopleRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_spokespeople.person_id</code>.
     */
    public final TableField<SpokespeopleRecord, UInteger> PERSON_ID = createField("person_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_spokespeople.team_season_id</code>.
     */
    public final TableField<SpokespeopleRecord, UInteger> TEAM_SEASON_ID = createField("team_season_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * The column <code>refereemanager.rfrmgr_spokespeople.club_id</code>.
     */
    public final TableField<SpokespeopleRecord, UInteger> CLUB_ID = createField("club_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * Create a <code>refereemanager.rfrmgr_spokespeople</code> table reference
     */
    public Spokespeople() {
        this("rfrmgr_spokespeople", null);
    }

    /**
     * Create an aliased <code>refereemanager.rfrmgr_spokespeople</code> table reference
     */
    public Spokespeople(String alias) {
        this(alias, SPOKESPEOPLE);
    }

    private Spokespeople(String alias, Table<SpokespeopleRecord> aliased) {
        this(alias, aliased, null);
    }

    private Spokespeople(String alias, Table<SpokespeopleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "Spokespeople of teams and clubs.");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Refereemanager.REFEREEMANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SpokespeopleRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_SPOKESPEOPLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SpokespeopleRecord> getPrimaryKey() {
        return Keys.KEY_RFRMGR_SPOKESPEOPLE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SpokespeopleRecord>> getKeys() {
        return Arrays.<UniqueKey<SpokespeopleRecord>>asList(Keys.KEY_RFRMGR_SPOKESPEOPLE_PRIMARY, Keys.KEY_RFRMGR_SPOKESPEOPLE_ID_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Spokespeople as(String alias) {
        return new Spokespeople(alias, this);
    }

    /**
     * Rename this table
     */
    public Spokespeople rename(String name) {
        return new Spokespeople(name, null);
    }
}
