/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq.tables;


import de.edgesoft.refereemanager.jooq.Keys;
import de.edgesoft.refereemanager.jooq.Refereemanager;
import de.edgesoft.refereemanager.jooq.tables.records.WishesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * Referees' wishes for their assignments.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Wishes extends TableImpl<WishesRecord> {

    private static final long serialVersionUID = 1088894863;

    /**
     * The reference instance of <code>refereemanager.rfrmgr_wishes</code>
     */
    public static final Wishes RFRMGR_WISHES = new Wishes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WishesRecord> getRecordType() {
        return WishesRecord.class;
    }

    /**
     * The column <code>refereemanager.rfrmgr_wishes.id</code>.
     */
    public final TableField<WishesRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_wishes.referee_id</code>.
     */
    public final TableField<WishesRecord, UInteger> REFEREE_ID = createField("referee_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_wishes.wish_type_id</code>.
     */
    public final TableField<WishesRecord, UInteger> WISH_TYPE_ID = createField("wish_type_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>refereemanager.rfrmgr_wishes.club_id</code>.
     */
    public final TableField<WishesRecord, UInteger> CLUB_ID = createField("club_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * The column <code>refereemanager.rfrmgr_wishes.league_id</code>.
     */
    public final TableField<WishesRecord, UInteger> LEAGUE_ID = createField("league_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * The column <code>refereemanager.rfrmgr_wishes.sex_type_id</code>.
     */
    public final TableField<WishesRecord, UInteger> SEX_TYPE_ID = createField("sex_type_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * The column <code>refereemanager.rfrmgr_wishes.saturday</code>.
     */
    public final TableField<WishesRecord, Byte> SATURDAY = createField("saturday", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>refereemanager.rfrmgr_wishes.sunday</code>.
     */
    public final TableField<WishesRecord, Byte> SUNDAY = createField("sunday", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>refereemanager.rfrmgr_wishes.tournament</code>.
     */
    public final TableField<WishesRecord, Byte> TOURNAMENT = createField("tournament", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>refereemanager.rfrmgr_wishes.remark</code>.
     */
    public final TableField<WishesRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>refereemanager.rfrmgr_wishes</code> table reference
     */
    public Wishes() {
        this("rfrmgr_wishes", null);
    }

    /**
     * Create an aliased <code>refereemanager.rfrmgr_wishes</code> table reference
     */
    public Wishes(String alias) {
        this(alias, RFRMGR_WISHES);
    }

    private Wishes(String alias, Table<WishesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Wishes(String alias, Table<WishesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "Referees' wishes for their assignments.");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Refereemanager.REFEREEMANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<WishesRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_RFRMGR_WISHES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WishesRecord> getPrimaryKey() {
        return Keys.KEY_RFRMGR_WISHES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WishesRecord>> getKeys() {
        return Arrays.<UniqueKey<WishesRecord>>asList(Keys.KEY_RFRMGR_WISHES_PRIMARY, Keys.KEY_RFRMGR_WISHES_ID_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Wishes as(String alias) {
        return new Wishes(alias, this);
    }

    /**
     * Rename this table
     */
    public Wishes rename(String name) {
        return new Wishes(name, null);
    }
}
