Quotes Language:		german
Base Header Level:	3
latex input:				kleinod-mmd-scrartcl
MyOptions:					author=schiri, font=droid, notitlepage, noauthor, pagestyle=fuss
latex input:				kleinod-mmd-style
Title:							**generated subject**
MySubTitle:					**generated subtitle**
Date:								**generated :date:long**
latex input:				kleinod-mmd-begin-doc

<!-- \maketitle -->

**generated body**
