Quotes Language:		german
Base Header Level:	3
latex input:				kleinod-mmd-scrartcl
MyOptions:					author=schiri, font=droid, notitlepage, noauthor, pagestyle=fuss
latex input:				kleinod-mmd-style
Title:							**generated documentdata:subject**
MySubTitle:					**generated documentdata:subtitle**
Date:								**generated documentdata:date:datelong**
latex input:				kleinod-mmd-begin-doc

<!-- \maketitle -->

**generated documentdata:body**
