Quotes Language:		german
Base Header Level:	3
latex input:				kleinod-mmd-scrlttr2
MyOptions:					author=schiri, font=droid, layout=infospaltefett
latex input:				kleinod-mmd-style
Title:							**generated subject**
MyBetreff:					**generated subject**
Date:								**generated date:medium**
MyAnA:							**generated person:fullname**
MyAnB:							**generated streetnumber**
MyAnC:							**generated zipcity**
MyAnrede:						**generated opening**
MyGruss:						**generated closing**
MyUnterschrift:			**generated signature**
MyPS:
latex input:				kleinod-mmd-begin-lttr
latex footer:				kleinod-mmd-end-lttr

**generated body**
