Quotes Language:		german
Base Header Level:	3
latex input:				kleinod-mmd-scrlttr2
MyOptions:					author=schiri, font=droid, layout=infospaltefett
latex input:				kleinod-mmd-style
Title:							#fullname#
Date:							#date#
MyAnA:							#fullname#
MyAnB:							#streetnumber#
MyAnC:							#zipcity#
MyBetreff:					Übersicht der gespeicherten Daten Saison #season#
MyAnrede:					Hallo #first_name#,
MyGruss:						Mit sportlichen Grüßen,
MyUnterschrift:		Ekkart.
latex input:				kleinod-mmd-begin-lttr
latex footer:			kleinod-mmd-end-lttr

dies ist der jährliche Auszug der über Dich beim Verbandsschiedsrichterausschuss für die Saison #season# gespeicherten Daten.
Du erhältst den Auszug aus zwei Gründen:

1. damit Du weißt, welche Daten gespeichert sind, wofür sie verwendet werden und wer die Daten sieht
2. damit Du kontrollieren kannst, ob die Daten korrekt sind und eventuelle Änderungen mitteilen kannst

# Öffentliche Informationen

Diese Informationen sind für jedermann sichtbar.
Nutzungsbeispiel: Einsatzplan.

<!--
\begin{longtable}[l]{@{}>{\small\sffamily\bfseries}p{.28\textwidth}@{\hspace{.02\textwidth}}p{.7\textwidth}@{}}
	 -->Titel<!-- & -->#title#<!-- \\
	 -->Vorname<!-- & -->#first_name#<!-- \\
	 -->Name<!-- & -->#name#<!-- \\
	 -->Ausbildung<!-- & -->#training_level# (#training_level_abbr#)<!-- \\
	 -->Einsatzhäufigkeit<!-- & -->#status_type#<!-- \\
\end{longtable}
-->

# Informationen für andere Schiedsrichter

Diese Informationen sind nur für andere Schiedsrichter nach Login sichtbar.
Nutzungsbeispiel: Kontakttabelle der Schiedsrichter.

<!--
\begin{longtable}[l]{@{}>{\small\sffamily\bfseries}p{.28\textwidth}@{\hspace{.02\textwidth}}p{.7\textwidth}@{}}
	 -->E-Mail<!-- & -->#email#<!-- \\
	 -->Telefon<!-- & -->#phone#<!-- \\
	 -->Mitglied bei<!-- & -->#member#<!-- \\
	 -->Schiedst für<!-- & -->#reffor#<!-- \\
\end{longtable}
-->

# Informationen für VSRA

Diese Informationen sind nur für den Verbandsschiedsrichterausschuss sichtbar.
Nutzungsbeispiel: Verwaltung der Einsätze.

<!--
\begin{longtable}[l]{@{}>{\small\sffamily\bfseries}p{.28\textwidth}@{\hspace{.02\textwidth}}p{.7\textwidth}@{}}
	 -->Adresse<!-- & -->#streetnumber#<!-- \newline -->#zipcity#<!-- \\
	 -->Geburtstag<!-- & -->#birthday#<!-- \\
	 -->Geschlecht<!-- & -->#sex_type#<!-- \\
	 -->Bevorzugt schiedsen<!-- & -->#prefer#<!-- \\
	 -->Nicht schiedsen<!-- & -->#noassignment#<!-- \\
	 -->Letzte Ausbildung<!-- & -->#since#<!-- \\
	 -->Letzte Fortbildung<!-- & -->#last_update#<!-- \\
	 -->Nächste Fortbildung<!-- & -->#next_update#<!-- \\
	 -->Anmerkung<!-- & -->#remark#<!-- \\
\end{longtable}
-->

Bitte prüfe die Informationen auf Korrektheit und Unvollständigkeit und gib mir Bescheid, wenn Änderungen nötig sind.

