Quotes Language:		german
Base Header Level:	3
latex input:				kleinod-mmd-scrlttr2
MyOptions:					author=schiri, font=droid, layout=infospaltefett
latex input:				kleinod-mmd-style
Title:							Übersicht der gespeicherten Daten Saison **generated season:title_season**
MyBetreff:					Übersicht der gespeicherten Daten Saison **generated season:title_season**
Date:								**generated date:medium**
MyAnA:							**generated person:fullname**
MyAnB:							**generated person:primary:streetnumber**
MyAnC:							**generated person:primary:zipcity**
MyAnrede:						Hallo **generated person:first_name**,
MyGruss:						Mit sportlichen Grüßen,
MyUnterschrift:			Ekkart.
MyPS:
latex input:				kleinod-mmd-begin-lttr
latex footer:				kleinod-mmd-end-lttr


dies ist der jährliche Auszug der über Dich beim Verbandsschiedsrichterausschuss für die Saison **generated season:title_season** gespeicherten Daten.
Du erhältst den Auszug aus zwei Gründen:

1. Damit Du weißt, welche Daten gespeichert sind, wofür sie verwendet werden und wer die Daten sieht.
2. Damit Du kontrollieren kannst, ob die Daten korrekt sind und eventuelle Änderungen mitteilen kannst.
3. Damit Du der Verwendung bestimmter Daten widersprechen kannst, falls Du das möchtest.

# Öffentliche Informationen

Diese Informationen sind für jedermann sichtbar.
Nutzungsbeispiel: Einsatzplan.

<!--
\begin{longtabu}[l]{@{}>{\small\sffamily\bfseries}p{.28\textwidth}@{\hspace{.02\textwidth}}p{.7\textwidth}@{}}
	\toprule
	-->Name<!-- & -->**generated person:tablename**<!-- \\
	-->Ausbildung<!-- & -->**generated traininglevel:title** (**generated traininglevel:abbreviation**)<!-- \\
	-->Einsatzhäufigkeit<!-- & -->**generated refereestatus:**generated season:id**:title**<!-- \\
	\bottomrule
\end{longtabu}
-->

# Informationen für andere Schiedsrichter

Diese Informationen sind nur für andere Schiedsrichter nach Login und den DTTB sichtbar.
Nutzungsbeispiel: Kontakttabelle der Schiedsrichter.

<!--
\begin{longtabu}[l]{@{}>{\small\sffamily\bfseries}p{.28\textwidth}@{\hspace{.02\textwidth}}p{.7\textwidth}@{}}
	\toprule
	-->E-Mail<!-- & -->**generated person:emails****ifnotempty person:emails:editor_only** (nur für VSRA sichtbar, nicht für andere Schiedsrichter)**endnotempty person:emails:editor_only**<!-- \\
	-->Telefon<!-- & -->**generated person:phone_numbers_national**<!-- \\
	-->Mitglied bei<!-- & -->**generated referee:referee_relation_member**<!-- \\
	-->**ifnotempty referee:referee_relation_reffor**Schiedst**endnotempty referee:referee_relation_reffor** für<!-- & -->**generated referee:referee_relation_reffor**<!-- \\
	\bottomrule
\end{longtabu}
-->

# Informationen für VSRA

Diese Informationen sind nur für den Verbandsschiedsrichterausschuss sichtbar.
Nutzungsbeispiel: Verwaltung der Einsätze.

<!--
\begin{longtabu}[l]{@{}>{\small\sffamily\bfseries}p{.28\textwidth}@{\hspace{.02\textwidth}}p{.7\textwidth}@{}}
	\toprule
	-->Alle Infos per Brief<!-- & -->**generated docs_per_letter****ifnotempty emails** *Bitte prüfen, ob die Zusendung per E-Mail nicht doch ausreicht.* **endnotempty emails**<!-- \\
	-->Adresse<!-- & -->**generated addresses_fulladdress**<!-- \\
	-->URL<!-- & -->**generated urls**<!-- \\
	-->Geburtstag<!-- & -->**generated birthday**<!-- \\
	-->Geschlecht<!-- & -->**generated sextype**<!-- \\
	-->Bevorzugt schiedsen<!-- & -->**generated referee_relation_prefer**<!-- \\
	-->Nicht schiedsen<!-- & -->**generated referee_relation_noassignment**<!-- \\
	-->Wochentag<!-- & -->**generated weekday**<!-- \\
	-->**generated traininglevel_abbreviation** seit<!-- & -->**generated traininglevelsince**<!-- \\
	-->Letzte Fortbildung<!-- & -->**generated lasttrainingupdate**<!-- \\
	-->Nächste Fortbildung<!-- & -->**generated nexttrainingupdate**<!-- \\
	-->Anmerkung<!-- & -->**generated remark** **generated refereestatus:**generated season:id**:remark**<!-- \\
	\bottomrule
\end{longtabu}
-->

Bitte prüfe die Informationen auf Korrektheit und Unvollständigkeit und gib mir Bescheid, wenn Änderungen nötig sind.

