Quotes Language:		german
Base Header Level:	3
latex input:				kleinod-mmd-scrlttr2
MyOptions:					author=schiri, font=droid, layout=infospaltefett
latex input:				kleinod-mmd-style
Title:							Dr. Max Mustermann
Date:								10. Januar 2014
MyAnA:							Dr. Max Mustermann
MyAnB:							Musterstraße 27
MyAnC:							10000 Berlin
MyBetreff:					Übersicht der gespeicherten Daten
MyAnrede:						Hallo Max,
MyGruss:						Mit sportlichen Grüßen,
MyUnterschrift:			Ekkart.
latex input:				kleinod-mmd-begin-lttr
latex footer:				kleinod-mmd-end-lttr

dies ist der jährliche Auszug der über Dich beim Verbandsschiedsrichterausschuss gespeicherten Daten.
Du erhältst den Auszug aus zwei Gründen:

1. damit Du weißt, welche Daten gespeichert sind, wofür sie verwendet werden und wer die Daten sieht
2. damit Du kontrollieren kannst, ob die Daten korrekt sind und eventuelle Änderungen mitteilen kannst

# Öffentliche Informationen

Diese Informationen sind für jedermann sichtbar.
Nutzungsbeispiel: Einsatzplan.

<!--
\begin{longtable}[l]{@{}>{\small\sffamily\bfseries}p{.3\textwidth}@{\hspace{.02\textwidth}}p{.78\textwidth}@{}}
	 -->Titel<!-- & -->Dr.<!-- \\
	 -->Vorname<!-- & -->Max<!-- \\
	 -->Name<!-- & -->Mustermann<!-- \\
	 -->Ausbildung<!-- & -->Verbandsschiedsrichter (VSR)<!-- \\
	 -->Einsatzhäufigkeit<!-- & -->normal<!-- \\
\end{longtable}
-->

# Informationen für andere Schiedsrichter

Diese Informationen sind nur für andere Schiedsrichter nach Login sichtbar.
Nutzungsbeispiel: Kontakttabelle der Schiedsrichter.

<!--
\begin{longtable}[l]{@{}>{\small\sffamily\bfseries}p{.3\textwidth}@{\hspace{.02\textwidth}}p{.78\textwidth}@{}}
	 -->Mitglied bei<!-- & -->TTC Borussia Spandau e.V.<!-- \\
	 -->Schiedst für<!-- & -->Mitgliedsverein<!-- \\
	 -->E-Mail<!-- & -->max.mustermann@beispiel.de<!-- \\
	 -->Telefon<!-- & -->p: 030 1234567<!-- \newline -->p: 0177 1234567<!-- \\
\end{longtable}
-->

# Informationen für VSRA

Diese Informationen sind nur für den Verbandsschiedsrichterausschuss sichtbar.
Nutzungsbeispiel: Verwaltung der Einsätze.

<!--
\begin{longtable}[l]{@{}>{\small\sffamily\bfseries}p{.3\textwidth}@{\hspace{.02\textwidth}}p{.78\textwidth}@{}}
	 -->Adresse<!-- & -->Musterstraße 27<!-- \newline -->10000 Berlin<!-- \\
	 -->Bevorzugt schiedsen bei<!-- & -->TuS Lichterfelde v. 1887 e.V.<!-- \\
	 -->Nicht schiedsen bei<!-- & -->---<!-- \\
	 -->Geschlecht<!-- & -->männlich<!-- \\
	 -->Geburtstag<!-- & -->26.10.1956<!-- \\
	 -->Letzte Fortbildung<!-- & -->01.01.2013<!-- \\
	 -->Nächste Fortbildung<!-- & -->2015<!-- \\
	 -->Anmerkung<!-- & -->Aus gesundheitlichen Gründen vorerst nicht mehr einsetzen.<!-- \\
\end{longtable}
-->

Bitte prüfe die Informationen auf Korrektheit und Unvollständigkeit und gib mir Bescheid, wenn Änderungen nötig sind.

