Quotes Language:		german
Base Header Level:	3
latex input:				kleinod-mmd-scrartcl
MyOptions:					author=schiri, font=droid,notitlepage, pagestyle=fuss
latex input:				kleinod-mmd-style
Title:							#Vorname Name#
Date:								#10. Januar 2014#
MySubtitle:					Übersicht der gespeicherten Daten
MyVersion:
MyAdresszusatz:
MyTitelzusatz:
latex input:				kleinod-mmd-begin-doc

<!-- \maketitle -->

Hallo #Vorname#,

dies ist der jährliche Auszug der über Dich beim Verbandsschiedsrichterausschuss gespeicherten Daten.
Du erhältst den Auszug aus zwei Gründen:

1. damit Du weißt, welche Daten gespeichert sind, wofür sie verwendet werden und wer die Daten sieht
2. damit Du kontrollieren kannst, ob die Daten korrekt sind und eventuelle Änderungen mitteilen kannst

<!--
\begin{longtabu}[l]{@{}>{\bfseries\small\sffamily}lll@{}}
	\toprule
	\textbf{\small\sffamily Art} & \textbf{\small\sffamily Inhalt} & \textbf{\small\sffamily Verwendung} \\
	\midrule
	-->Vorname<!-- & -->#Vorname#<!-- & -->öffentlich, alle Listen<!-- \\
	-->Name<!-- & -->#Name#<!-- & -->öffentlich, alle Listen<!-- \\
	\bottomrule
\end{longtabu}

-->

