/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq;


import de.edgesoft.refereemanager.jooq.tables.ActivityLogs;
import de.edgesoft.refereemanager.jooq.tables.Addresses;
import de.edgesoft.refereemanager.jooq.tables.Assignments;
import de.edgesoft.refereemanager.jooq.tables.Clubs;
import de.edgesoft.refereemanager.jooq.tables.ContactTypes;
import de.edgesoft.refereemanager.jooq.tables.Contacts;
import de.edgesoft.refereemanager.jooq.tables.DatabaseColumns;
import de.edgesoft.refereemanager.jooq.tables.DatabaseTables;
import de.edgesoft.refereemanager.jooq.tables.Emails;
import de.edgesoft.refereemanager.jooq.tables.LeagueGameTeamTypes;
import de.edgesoft.refereemanager.jooq.tables.LeagueGameTeams;
import de.edgesoft.refereemanager.jooq.tables.LeagueGames;
import de.edgesoft.refereemanager.jooq.tables.LeaguePlannedReferees;
import de.edgesoft.refereemanager.jooq.tables.LeagueTypes;
import de.edgesoft.refereemanager.jooq.tables.Leagues;
import de.edgesoft.refereemanager.jooq.tables.People;
import de.edgesoft.refereemanager.jooq.tables.PersonPreferences;
import de.edgesoft.refereemanager.jooq.tables.PhoneNumbers;
import de.edgesoft.refereemanager.jooq.tables.Pictures;
import de.edgesoft.refereemanager.jooq.tables.RefereeAssignmentRemarkTypes;
import de.edgesoft.refereemanager.jooq.tables.RefereeAssignmentStatusTypes;
import de.edgesoft.refereemanager.jooq.tables.RefereeAssignmentTypes;
import de.edgesoft.refereemanager.jooq.tables.RefereeAssignments;
import de.edgesoft.refereemanager.jooq.tables.RefereeRelationTypes;
import de.edgesoft.refereemanager.jooq.tables.RefereeRelations;
import de.edgesoft.refereemanager.jooq.tables.RefereeReportRecipients;
import de.edgesoft.refereemanager.jooq.tables.RefereeReports;
import de.edgesoft.refereemanager.jooq.tables.RefereeStatuses;
import de.edgesoft.refereemanager.jooq.tables.Referees;
import de.edgesoft.refereemanager.jooq.tables.Seasons;
import de.edgesoft.refereemanager.jooq.tables.SexTypes;
import de.edgesoft.refereemanager.jooq.tables.Spokespeople;
import de.edgesoft.refereemanager.jooq.tables.StatusTypes;
import de.edgesoft.refereemanager.jooq.tables.TeamSeasons;
import de.edgesoft.refereemanager.jooq.tables.TeamVenues;
import de.edgesoft.refereemanager.jooq.tables.Teams;
import de.edgesoft.refereemanager.jooq.tables.TournamentGames;
import de.edgesoft.refereemanager.jooq.tables.TournamentVenues;
import de.edgesoft.refereemanager.jooq.tables.Tournaments;
import de.edgesoft.refereemanager.jooq.tables.TrainingLevelTypes;
import de.edgesoft.refereemanager.jooq.tables.TrainingLevels;
import de.edgesoft.refereemanager.jooq.tables.TrainingUpdates;
import de.edgesoft.refereemanager.jooq.tables.Urls;
import de.edgesoft.refereemanager.jooq.tables.UserRoles;
import de.edgesoft.refereemanager.jooq.tables.Users;
import de.edgesoft.refereemanager.jooq.tables.WishTypes;
import de.edgesoft.refereemanager.jooq.tables.Wishes;
import de.edgesoft.refereemanager.jooq.tables.records.ActivityLogsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.AddressesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.AssignmentsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.ClubsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.ContactTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.ContactsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.DatabaseColumnsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.DatabaseTablesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.EmailsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.LeagueGameTeamTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.LeagueGameTeamsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.LeagueGamesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.LeaguePlannedRefereesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.LeagueTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.LeaguesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.PeopleRecord;
import de.edgesoft.refereemanager.jooq.tables.records.PersonPreferencesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.PhoneNumbersRecord;
import de.edgesoft.refereemanager.jooq.tables.records.PicturesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RefereeAssignmentRemarkTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RefereeAssignmentStatusTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RefereeAssignmentTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RefereeAssignmentsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RefereeRelationTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RefereeRelationsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RefereeReportRecipientsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RefereeReportsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RefereeStatusesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RefereesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.SeasonsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.SexTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.SpokespeopleRecord;
import de.edgesoft.refereemanager.jooq.tables.records.StatusTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.TeamSeasonsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.TeamVenuesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.TeamsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.TournamentGamesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.TournamentVenuesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.TournamentsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.TrainingLevelTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.TrainingLevelsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.TrainingUpdatesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.UrlsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.UserRolesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.UsersRecord;
import de.edgesoft.refereemanager.jooq.tables.records.WishTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.WishesRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships between tables of the <code>refereemanager</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ActivityLogsRecord, UInteger> IDENTITY_RFRMGR_ACTIVITY_LOGS = Identities0.IDENTITY_RFRMGR_ACTIVITY_LOGS;
    public static final Identity<AddressesRecord, UInteger> IDENTITY_RFRMGR_ADDRESSES = Identities0.IDENTITY_RFRMGR_ADDRESSES;
    public static final Identity<AssignmentsRecord, UInteger> IDENTITY_RFRMGR_ASSIGNMENTS = Identities0.IDENTITY_RFRMGR_ASSIGNMENTS;
    public static final Identity<ClubsRecord, UInteger> IDENTITY_RFRMGR_CLUBS = Identities0.IDENTITY_RFRMGR_CLUBS;
    public static final Identity<ContactsRecord, UInteger> IDENTITY_RFRMGR_CONTACTS = Identities0.IDENTITY_RFRMGR_CONTACTS;
    public static final Identity<ContactTypesRecord, UInteger> IDENTITY_RFRMGR_CONTACT_TYPES = Identities0.IDENTITY_RFRMGR_CONTACT_TYPES;
    public static final Identity<DatabaseColumnsRecord, UInteger> IDENTITY_RFRMGR_DATABASE_COLUMNS = Identities0.IDENTITY_RFRMGR_DATABASE_COLUMNS;
    public static final Identity<DatabaseTablesRecord, UInteger> IDENTITY_RFRMGR_DATABASE_TABLES = Identities0.IDENTITY_RFRMGR_DATABASE_TABLES;
    public static final Identity<EmailsRecord, UInteger> IDENTITY_RFRMGR_EMAILS = Identities0.IDENTITY_RFRMGR_EMAILS;
    public static final Identity<LeaguesRecord, UInteger> IDENTITY_RFRMGR_LEAGUES = Identities0.IDENTITY_RFRMGR_LEAGUES;
    public static final Identity<LeagueGamesRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_GAMES = Identities0.IDENTITY_RFRMGR_LEAGUE_GAMES;
    public static final Identity<LeagueGameTeamsRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_GAME_TEAMS = Identities0.IDENTITY_RFRMGR_LEAGUE_GAME_TEAMS;
    public static final Identity<LeagueGameTeamTypesRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_GAME_TEAM_TYPES = Identities0.IDENTITY_RFRMGR_LEAGUE_GAME_TEAM_TYPES;
    public static final Identity<LeaguePlannedRefereesRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_PLANNED_REFEREES = Identities0.IDENTITY_RFRMGR_LEAGUE_PLANNED_REFEREES;
    public static final Identity<LeagueTypesRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_TYPES = Identities0.IDENTITY_RFRMGR_LEAGUE_TYPES;
    public static final Identity<PeopleRecord, UInteger> IDENTITY_RFRMGR_PEOPLE = Identities0.IDENTITY_RFRMGR_PEOPLE;
    public static final Identity<PersonPreferencesRecord, UInteger> IDENTITY_RFRMGR_PERSON_PREFERENCES = Identities0.IDENTITY_RFRMGR_PERSON_PREFERENCES;
    public static final Identity<PhoneNumbersRecord, UInteger> IDENTITY_RFRMGR_PHONE_NUMBERS = Identities0.IDENTITY_RFRMGR_PHONE_NUMBERS;
    public static final Identity<PicturesRecord, UInteger> IDENTITY_RFRMGR_PICTURES = Identities0.IDENTITY_RFRMGR_PICTURES;
    public static final Identity<RefereesRecord, UInteger> IDENTITY_RFRMGR_REFEREES = Identities0.IDENTITY_RFRMGR_REFEREES;
    public static final Identity<RefereeAssignmentsRecord, UInteger> IDENTITY_RFRMGR_REFEREE_ASSIGNMENTS = Identities0.IDENTITY_RFRMGR_REFEREE_ASSIGNMENTS;
    public static final Identity<RefereeAssignmentRemarkTypesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES = Identities0.IDENTITY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES;
    public static final Identity<RefereeAssignmentStatusTypesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES = Identities0.IDENTITY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES;
    public static final Identity<RefereeAssignmentTypesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_ASSIGNMENT_TYPES = Identities0.IDENTITY_RFRMGR_REFEREE_ASSIGNMENT_TYPES;
    public static final Identity<RefereeRelationsRecord, UInteger> IDENTITY_RFRMGR_REFEREE_RELATIONS = Identities0.IDENTITY_RFRMGR_REFEREE_RELATIONS;
    public static final Identity<RefereeRelationTypesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_RELATION_TYPES = Identities0.IDENTITY_RFRMGR_REFEREE_RELATION_TYPES;
    public static final Identity<RefereeReportsRecord, UInteger> IDENTITY_RFRMGR_REFEREE_REPORTS = Identities0.IDENTITY_RFRMGR_REFEREE_REPORTS;
    public static final Identity<RefereeReportRecipientsRecord, UInteger> IDENTITY_RFRMGR_REFEREE_REPORT_RECIPIENTS = Identities0.IDENTITY_RFRMGR_REFEREE_REPORT_RECIPIENTS;
    public static final Identity<RefereeStatusesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_STATUSES = Identities0.IDENTITY_RFRMGR_REFEREE_STATUSES;
    public static final Identity<SeasonsRecord, UInteger> IDENTITY_RFRMGR_SEASONS = Identities0.IDENTITY_RFRMGR_SEASONS;
    public static final Identity<SexTypesRecord, UInteger> IDENTITY_RFRMGR_SEX_TYPES = Identities0.IDENTITY_RFRMGR_SEX_TYPES;
    public static final Identity<SpokespeopleRecord, UInteger> IDENTITY_RFRMGR_SPOKESPEOPLE = Identities0.IDENTITY_RFRMGR_SPOKESPEOPLE;
    public static final Identity<StatusTypesRecord, UInteger> IDENTITY_RFRMGR_STATUS_TYPES = Identities0.IDENTITY_RFRMGR_STATUS_TYPES;
    public static final Identity<TeamsRecord, UInteger> IDENTITY_RFRMGR_TEAMS = Identities0.IDENTITY_RFRMGR_TEAMS;
    public static final Identity<TeamSeasonsRecord, UInteger> IDENTITY_RFRMGR_TEAM_SEASONS = Identities0.IDENTITY_RFRMGR_TEAM_SEASONS;
    public static final Identity<TeamVenuesRecord, UInteger> IDENTITY_RFRMGR_TEAM_VENUES = Identities0.IDENTITY_RFRMGR_TEAM_VENUES;
    public static final Identity<TournamentsRecord, UInteger> IDENTITY_RFRMGR_TOURNAMENTS = Identities0.IDENTITY_RFRMGR_TOURNAMENTS;
    public static final Identity<TournamentGamesRecord, UInteger> IDENTITY_RFRMGR_TOURNAMENT_GAMES = Identities0.IDENTITY_RFRMGR_TOURNAMENT_GAMES;
    public static final Identity<TournamentVenuesRecord, UInteger> IDENTITY_RFRMGR_TOURNAMENT_VENUES = Identities0.IDENTITY_RFRMGR_TOURNAMENT_VENUES;
    public static final Identity<TrainingLevelsRecord, UInteger> IDENTITY_RFRMGR_TRAINING_LEVELS = Identities0.IDENTITY_RFRMGR_TRAINING_LEVELS;
    public static final Identity<TrainingLevelTypesRecord, UInteger> IDENTITY_RFRMGR_TRAINING_LEVEL_TYPES = Identities0.IDENTITY_RFRMGR_TRAINING_LEVEL_TYPES;
    public static final Identity<TrainingUpdatesRecord, UInteger> IDENTITY_RFRMGR_TRAINING_UPDATES = Identities0.IDENTITY_RFRMGR_TRAINING_UPDATES;
    public static final Identity<UrlsRecord, UInteger> IDENTITY_RFRMGR_URLS = Identities0.IDENTITY_RFRMGR_URLS;
    public static final Identity<UsersRecord, UInteger> IDENTITY_RFRMGR_USERS = Identities0.IDENTITY_RFRMGR_USERS;
    public static final Identity<UserRolesRecord, UInteger> IDENTITY_RFRMGR_USER_ROLES = Identities0.IDENTITY_RFRMGR_USER_ROLES;
    public static final Identity<WishesRecord, UInteger> IDENTITY_RFRMGR_WISHES = Identities0.IDENTITY_RFRMGR_WISHES;
    public static final Identity<WishTypesRecord, UInteger> IDENTITY_RFRMGR_WISH_TYPES = Identities0.IDENTITY_RFRMGR_WISH_TYPES;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ActivityLogsRecord> KEY_RFRMGR_ACTIVITY_LOGS_PRIMARY = UniqueKeys0.KEY_RFRMGR_ACTIVITY_LOGS_PRIMARY;
    public static final UniqueKey<ActivityLogsRecord> KEY_RFRMGR_ACTIVITY_LOGS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_ACTIVITY_LOGS_ID_UNIQUE;
    public static final UniqueKey<AddressesRecord> KEY_RFRMGR_ADDRESSES_PRIMARY = UniqueKeys0.KEY_RFRMGR_ADDRESSES_PRIMARY;
    public static final UniqueKey<AddressesRecord> KEY_RFRMGR_ADDRESSES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_ADDRESSES_ID_UNIQUE;
    public static final UniqueKey<AssignmentsRecord> KEY_RFRMGR_ASSIGNMENTS_PRIMARY = UniqueKeys0.KEY_RFRMGR_ASSIGNMENTS_PRIMARY;
    public static final UniqueKey<AssignmentsRecord> KEY_RFRMGR_ASSIGNMENTS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_ASSIGNMENTS_ID_UNIQUE;
    public static final UniqueKey<ClubsRecord> KEY_RFRMGR_CLUBS_PRIMARY = UniqueKeys0.KEY_RFRMGR_CLUBS_PRIMARY;
    public static final UniqueKey<ClubsRecord> KEY_RFRMGR_CLUBS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_CLUBS_ID_UNIQUE;
    public static final UniqueKey<ContactsRecord> KEY_RFRMGR_CONTACTS_PRIMARY = UniqueKeys0.KEY_RFRMGR_CONTACTS_PRIMARY;
    public static final UniqueKey<ContactsRecord> KEY_RFRMGR_CONTACTS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_CONTACTS_ID_UNIQUE;
    public static final UniqueKey<ContactTypesRecord> KEY_RFRMGR_CONTACT_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_CONTACT_TYPES_PRIMARY;
    public static final UniqueKey<ContactTypesRecord> KEY_RFRMGR_CONTACT_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_CONTACT_TYPES_ID_UNIQUE;
    public static final UniqueKey<ContactTypesRecord> KEY_RFRMGR_CONTACT_TYPES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_CONTACT_TYPES_SID_UNIQUE;
    public static final UniqueKey<DatabaseColumnsRecord> KEY_RFRMGR_DATABASE_COLUMNS_PRIMARY = UniqueKeys0.KEY_RFRMGR_DATABASE_COLUMNS_PRIMARY;
    public static final UniqueKey<DatabaseColumnsRecord> KEY_RFRMGR_DATABASE_COLUMNS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_DATABASE_COLUMNS_ID_UNIQUE;
    public static final UniqueKey<DatabaseColumnsRecord> KEY_RFRMGR_DATABASE_COLUMNS_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_DATABASE_COLUMNS_SID_UNIQUE;
    public static final UniqueKey<DatabaseTablesRecord> KEY_RFRMGR_DATABASE_TABLES_PRIMARY = UniqueKeys0.KEY_RFRMGR_DATABASE_TABLES_PRIMARY;
    public static final UniqueKey<DatabaseTablesRecord> KEY_RFRMGR_DATABASE_TABLES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_DATABASE_TABLES_ID_UNIQUE;
    public static final UniqueKey<DatabaseTablesRecord> KEY_RFRMGR_DATABASE_TABLES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_DATABASE_TABLES_SID_UNIQUE;
    public static final UniqueKey<EmailsRecord> KEY_RFRMGR_EMAILS_PRIMARY = UniqueKeys0.KEY_RFRMGR_EMAILS_PRIMARY;
    public static final UniqueKey<EmailsRecord> KEY_RFRMGR_EMAILS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_EMAILS_ID_UNIQUE;
    public static final UniqueKey<LeaguesRecord> KEY_RFRMGR_LEAGUES_PRIMARY = UniqueKeys0.KEY_RFRMGR_LEAGUES_PRIMARY;
    public static final UniqueKey<LeaguesRecord> KEY_RFRMGR_LEAGUES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUES_ID_UNIQUE;
    public static final UniqueKey<LeagueGamesRecord> KEY_RFRMGR_LEAGUE_GAMES_PRIMARY = UniqueKeys0.KEY_RFRMGR_LEAGUE_GAMES_PRIMARY;
    public static final UniqueKey<LeagueGamesRecord> KEY_RFRMGR_LEAGUE_GAMES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUE_GAMES_ID_UNIQUE;
    public static final UniqueKey<LeagueGameTeamsRecord> KEY_RFRMGR_LEAGUE_GAME_TEAMS_PRIMARY = UniqueKeys0.KEY_RFRMGR_LEAGUE_GAME_TEAMS_PRIMARY;
    public static final UniqueKey<LeagueGameTeamsRecord> KEY_RFRMGR_LEAGUE_GAME_TEAMS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUE_GAME_TEAMS_ID_UNIQUE;
    public static final UniqueKey<LeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_PRIMARY;
    public static final UniqueKey<LeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_ID_UNIQUE;
    public static final UniqueKey<LeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_SID_UNIQUE;
    public static final UniqueKey<LeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_TITLE_UNIQUE;
    public static final UniqueKey<LeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_ABBREVIATION_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_ABBREVIATION_UNIQUE;
    public static final UniqueKey<LeaguePlannedRefereesRecord> KEY_RFRMGR_LEAGUE_PLANNED_REFEREES_PRIMARY = UniqueKeys0.KEY_RFRMGR_LEAGUE_PLANNED_REFEREES_PRIMARY;
    public static final UniqueKey<LeaguePlannedRefereesRecord> KEY_RFRMGR_LEAGUE_PLANNED_REFEREES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUE_PLANNED_REFEREES_ID_UNIQUE;
    public static final UniqueKey<LeagueTypesRecord> KEY_RFRMGR_LEAGUE_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_LEAGUE_TYPES_PRIMARY;
    public static final UniqueKey<LeagueTypesRecord> KEY_RFRMGR_LEAGUE_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUE_TYPES_ID_UNIQUE;
    public static final UniqueKey<LeagueTypesRecord> KEY_RFRMGR_LEAGUE_TYPES_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUE_TYPES_TITLE_UNIQUE;
    public static final UniqueKey<PeopleRecord> KEY_RFRMGR_PEOPLE_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_PEOPLE_ID_UNIQUE;
    public static final UniqueKey<PersonPreferencesRecord> KEY_RFRMGR_PERSON_PREFERENCES_PRIMARY = UniqueKeys0.KEY_RFRMGR_PERSON_PREFERENCES_PRIMARY;
    public static final UniqueKey<PersonPreferencesRecord> KEY_RFRMGR_PERSON_PREFERENCES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_PERSON_PREFERENCES_ID_UNIQUE;
    public static final UniqueKey<PersonPreferencesRecord> KEY_RFRMGR_PERSON_PREFERENCES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_PERSON_PREFERENCES_SID_UNIQUE;
    public static final UniqueKey<PhoneNumbersRecord> KEY_RFRMGR_PHONE_NUMBERS_PRIMARY = UniqueKeys0.KEY_RFRMGR_PHONE_NUMBERS_PRIMARY;
    public static final UniqueKey<PhoneNumbersRecord> KEY_RFRMGR_PHONE_NUMBERS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_PHONE_NUMBERS_ID_UNIQUE;
    public static final UniqueKey<PicturesRecord> KEY_RFRMGR_PICTURES_PRIMARY = UniqueKeys0.KEY_RFRMGR_PICTURES_PRIMARY;
    public static final UniqueKey<PicturesRecord> KEY_RFRMGR_PICTURES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_PICTURES_ID_UNIQUE;
    public static final UniqueKey<RefereesRecord> KEY_RFRMGR_REFEREES_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREES_PRIMARY;
    public static final UniqueKey<RefereesRecord> KEY_RFRMGR_REFEREES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREES_ID_UNIQUE;
    public static final UniqueKey<RefereeAssignmentsRecord> KEY_RFRMGR_REFEREE_ASSIGNMENTS_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENTS_PRIMARY;
    public static final UniqueKey<RefereeAssignmentsRecord> KEY_RFRMGR_REFEREE_ASSIGNMENTS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENTS_ID_UNIQUE;
    public static final UniqueKey<RefereeAssignmentRemarkTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES_PRIMARY;
    public static final UniqueKey<RefereeAssignmentRemarkTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES_ID_UNIQUE;
    public static final UniqueKey<RefereeAssignmentRemarkTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES_TITLE_UNIQUE;
    public static final UniqueKey<RefereeAssignmentStatusTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES_PRIMARY;
    public static final UniqueKey<RefereeAssignmentStatusTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES_ID_UNIQUE;
    public static final UniqueKey<RefereeAssignmentStatusTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES_TITLE_UNIQUE;
    public static final UniqueKey<RefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_PRIMARY;
    public static final UniqueKey<RefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_ID_UNIQUE;
    public static final UniqueKey<RefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_SID_UNIQUE;
    public static final UniqueKey<RefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_TITLE_UNIQUE;
    public static final UniqueKey<RefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_ABBREVIATION_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_ABBREVIATION_UNIQUE;
    public static final UniqueKey<RefereeRelationsRecord> KEY_RFRMGR_REFEREE_RELATIONS_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREE_RELATIONS_PRIMARY;
    public static final UniqueKey<RefereeRelationsRecord> KEY_RFRMGR_REFEREE_RELATIONS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_RELATIONS_ID_UNIQUE;
    public static final UniqueKey<RefereeRelationTypesRecord> KEY_RFRMGR_REFEREE_RELATION_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREE_RELATION_TYPES_PRIMARY;
    public static final UniqueKey<RefereeRelationTypesRecord> KEY_RFRMGR_REFEREE_RELATION_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_RELATION_TYPES_ID_UNIQUE;
    public static final UniqueKey<RefereeRelationTypesRecord> KEY_RFRMGR_REFEREE_RELATION_TYPES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_RELATION_TYPES_SID_UNIQUE;
    public static final UniqueKey<RefereeRelationTypesRecord> KEY_RFRMGR_REFEREE_RELATION_TYPES_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_RELATION_TYPES_TITLE_UNIQUE;
    public static final UniqueKey<RefereeReportsRecord> KEY_RFRMGR_REFEREE_REPORTS_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREE_REPORTS_PRIMARY;
    public static final UniqueKey<RefereeReportsRecord> KEY_RFRMGR_REFEREE_REPORTS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_REPORTS_ID_UNIQUE;
    public static final UniqueKey<RefereeReportRecipientsRecord> KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_PRIMARY;
    public static final UniqueKey<RefereeReportRecipientsRecord> KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_ID_UNIQUE;
    public static final UniqueKey<RefereeReportRecipientsRecord> KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_TITLE_UNIQUE;
    public static final UniqueKey<RefereeReportRecipientsRecord> KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_PERSON_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_PERSON_ID_UNIQUE;
    public static final UniqueKey<RefereeStatusesRecord> KEY_RFRMGR_REFEREE_STATUSES_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREE_STATUSES_PRIMARY;
    public static final UniqueKey<RefereeStatusesRecord> KEY_RFRMGR_REFEREE_STATUSES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_STATUSES_ID_UNIQUE;
    public static final UniqueKey<SeasonsRecord> KEY_RFRMGR_SEASONS_PRIMARY = UniqueKeys0.KEY_RFRMGR_SEASONS_PRIMARY;
    public static final UniqueKey<SeasonsRecord> KEY_RFRMGR_SEASONS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_SEASONS_ID_UNIQUE;
    public static final UniqueKey<SeasonsRecord> KEY_RFRMGR_SEASONS_YEAR_START_UNIQUE = UniqueKeys0.KEY_RFRMGR_SEASONS_YEAR_START_UNIQUE;
    public static final UniqueKey<SexTypesRecord> KEY_RFRMGR_SEX_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_SEX_TYPES_PRIMARY;
    public static final UniqueKey<SexTypesRecord> KEY_RFRMGR_SEX_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_SEX_TYPES_ID_UNIQUE;
    public static final UniqueKey<SexTypesRecord> KEY_RFRMGR_SEX_TYPES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_SEX_TYPES_SID_UNIQUE;
    public static final UniqueKey<SpokespeopleRecord> KEY_RFRMGR_SPOKESPEOPLE_PRIMARY = UniqueKeys0.KEY_RFRMGR_SPOKESPEOPLE_PRIMARY;
    public static final UniqueKey<SpokespeopleRecord> KEY_RFRMGR_SPOKESPEOPLE_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_SPOKESPEOPLE_ID_UNIQUE;
    public static final UniqueKey<StatusTypesRecord> KEY_RFRMGR_STATUS_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_STATUS_TYPES_PRIMARY;
    public static final UniqueKey<StatusTypesRecord> KEY_RFRMGR_STATUS_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_STATUS_TYPES_ID_UNIQUE;
    public static final UniqueKey<StatusTypesRecord> KEY_RFRMGR_STATUS_TYPES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_STATUS_TYPES_SID_UNIQUE;
    public static final UniqueKey<StatusTypesRecord> KEY_RFRMGR_STATUS_TYPES_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_STATUS_TYPES_TITLE_UNIQUE;
    public static final UniqueKey<TeamsRecord> KEY_RFRMGR_TEAMS_PRIMARY = UniqueKeys0.KEY_RFRMGR_TEAMS_PRIMARY;
    public static final UniqueKey<TeamsRecord> KEY_RFRMGR_TEAMS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TEAMS_ID_UNIQUE;
    public static final UniqueKey<TeamSeasonsRecord> KEY_RFRMGR_TEAM_SEASONS_PRIMARY = UniqueKeys0.KEY_RFRMGR_TEAM_SEASONS_PRIMARY;
    public static final UniqueKey<TeamSeasonsRecord> KEY_RFRMGR_TEAM_SEASONS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TEAM_SEASONS_ID_UNIQUE;
    public static final UniqueKey<TeamVenuesRecord> KEY_RFRMGR_TEAM_VENUES_PRIMARY = UniqueKeys0.KEY_RFRMGR_TEAM_VENUES_PRIMARY;
    public static final UniqueKey<TeamVenuesRecord> KEY_RFRMGR_TEAM_VENUES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TEAM_VENUES_ID_UNIQUE;
    public static final UniqueKey<TournamentsRecord> KEY_RFRMGR_TOURNAMENTS_PRIMARY = UniqueKeys0.KEY_RFRMGR_TOURNAMENTS_PRIMARY;
    public static final UniqueKey<TournamentsRecord> KEY_RFRMGR_TOURNAMENTS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TOURNAMENTS_ID_UNIQUE;
    public static final UniqueKey<TournamentsRecord> KEY_RFRMGR_TOURNAMENTS_ABBREVIATION_UNIQUE = UniqueKeys0.KEY_RFRMGR_TOURNAMENTS_ABBREVIATION_UNIQUE;
    public static final UniqueKey<TournamentGamesRecord> KEY_RFRMGR_TOURNAMENT_GAMES_PRIMARY = UniqueKeys0.KEY_RFRMGR_TOURNAMENT_GAMES_PRIMARY;
    public static final UniqueKey<TournamentGamesRecord> KEY_RFRMGR_TOURNAMENT_GAMES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TOURNAMENT_GAMES_ID_UNIQUE;
    public static final UniqueKey<TournamentVenuesRecord> KEY_RFRMGR_TOURNAMENT_VENUES_PRIMARY = UniqueKeys0.KEY_RFRMGR_TOURNAMENT_VENUES_PRIMARY;
    public static final UniqueKey<TournamentVenuesRecord> KEY_RFRMGR_TOURNAMENT_VENUES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TOURNAMENT_VENUES_ID_UNIQUE;
    public static final UniqueKey<TrainingLevelsRecord> KEY_RFRMGR_TRAINING_LEVELS_PRIMARY = UniqueKeys0.KEY_RFRMGR_TRAINING_LEVELS_PRIMARY;
    public static final UniqueKey<TrainingLevelsRecord> KEY_RFRMGR_TRAINING_LEVELS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TRAINING_LEVELS_ID_UNIQUE;
    public static final UniqueKey<TrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_TRAINING_LEVEL_TYPES_PRIMARY;
    public static final UniqueKey<TrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TRAINING_LEVEL_TYPES_ID_UNIQUE;
    public static final UniqueKey<TrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TRAINING_LEVEL_TYPES_SID_UNIQUE;
    public static final UniqueKey<TrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_RANK_UNIQUE = UniqueKeys0.KEY_RFRMGR_TRAINING_LEVEL_TYPES_RANK_UNIQUE;
    public static final UniqueKey<TrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_TRAINING_LEVEL_TYPES_TITLE_UNIQUE;
    public static final UniqueKey<TrainingUpdatesRecord> KEY_RFRMGR_TRAINING_UPDATES_PRIMARY = UniqueKeys0.KEY_RFRMGR_TRAINING_UPDATES_PRIMARY;
    public static final UniqueKey<TrainingUpdatesRecord> KEY_RFRMGR_TRAINING_UPDATES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TRAINING_UPDATES_ID_UNIQUE;
    public static final UniqueKey<UrlsRecord> KEY_RFRMGR_URLS_PRIMARY = UniqueKeys0.KEY_RFRMGR_URLS_PRIMARY;
    public static final UniqueKey<UrlsRecord> KEY_RFRMGR_URLS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_URLS_ID_UNIQUE;
    public static final UniqueKey<UsersRecord> KEY_RFRMGR_USERS_PRIMARY = UniqueKeys0.KEY_RFRMGR_USERS_PRIMARY;
    public static final UniqueKey<UsersRecord> KEY_RFRMGR_USERS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_USERS_ID_UNIQUE;
    public static final UniqueKey<UsersRecord> KEY_RFRMGR_USERS_USERNAME_UNIQUE = UniqueKeys0.KEY_RFRMGR_USERS_USERNAME_UNIQUE;
    public static final UniqueKey<UserRolesRecord> KEY_RFRMGR_USER_ROLES_PRIMARY = UniqueKeys0.KEY_RFRMGR_USER_ROLES_PRIMARY;
    public static final UniqueKey<UserRolesRecord> KEY_RFRMGR_USER_ROLES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_USER_ROLES_ID_UNIQUE;
    public static final UniqueKey<UserRolesRecord> KEY_RFRMGR_USER_ROLES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_USER_ROLES_SID_UNIQUE;
    public static final UniqueKey<WishesRecord> KEY_RFRMGR_WISHES_PRIMARY = UniqueKeys0.KEY_RFRMGR_WISHES_PRIMARY;
    public static final UniqueKey<WishesRecord> KEY_RFRMGR_WISHES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_WISHES_ID_UNIQUE;
    public static final UniqueKey<WishTypesRecord> KEY_RFRMGR_WISH_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_WISH_TYPES_PRIMARY;
    public static final UniqueKey<WishTypesRecord> KEY_RFRMGR_WISH_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_WISH_TYPES_ID_UNIQUE;
    public static final UniqueKey<WishTypesRecord> KEY_RFRMGR_WISH_TYPES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_WISH_TYPES_SID_UNIQUE;
    public static final UniqueKey<WishTypesRecord> KEY_RFRMGR_WISH_TYPES_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_WISH_TYPES_TITLE_UNIQUE;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<ActivityLogsRecord, UInteger> IDENTITY_RFRMGR_ACTIVITY_LOGS = createIdentity(ActivityLogs.RFRMGR_ACTIVITY_LOGS, ActivityLogs.RFRMGR_ACTIVITY_LOGS.ID);
        public static Identity<AddressesRecord, UInteger> IDENTITY_RFRMGR_ADDRESSES = createIdentity(Addresses.RFRMGR_ADDRESSES, Addresses.RFRMGR_ADDRESSES.ID);
        public static Identity<AssignmentsRecord, UInteger> IDENTITY_RFRMGR_ASSIGNMENTS = createIdentity(Assignments.RFRMGR_ASSIGNMENTS, Assignments.RFRMGR_ASSIGNMENTS.ID);
        public static Identity<ClubsRecord, UInteger> IDENTITY_RFRMGR_CLUBS = createIdentity(Clubs.RFRMGR_CLUBS, Clubs.RFRMGR_CLUBS.ID);
        public static Identity<ContactsRecord, UInteger> IDENTITY_RFRMGR_CONTACTS = createIdentity(Contacts.RFRMGR_CONTACTS, Contacts.RFRMGR_CONTACTS.ID);
        public static Identity<ContactTypesRecord, UInteger> IDENTITY_RFRMGR_CONTACT_TYPES = createIdentity(ContactTypes.RFRMGR_CONTACT_TYPES, ContactTypes.RFRMGR_CONTACT_TYPES.ID);
        public static Identity<DatabaseColumnsRecord, UInteger> IDENTITY_RFRMGR_DATABASE_COLUMNS = createIdentity(DatabaseColumns.RFRMGR_DATABASE_COLUMNS, DatabaseColumns.RFRMGR_DATABASE_COLUMNS.ID);
        public static Identity<DatabaseTablesRecord, UInteger> IDENTITY_RFRMGR_DATABASE_TABLES = createIdentity(DatabaseTables.RFRMGR_DATABASE_TABLES, DatabaseTables.RFRMGR_DATABASE_TABLES.ID);
        public static Identity<EmailsRecord, UInteger> IDENTITY_RFRMGR_EMAILS = createIdentity(Emails.RFRMGR_EMAILS, Emails.RFRMGR_EMAILS.ID);
        public static Identity<LeaguesRecord, UInteger> IDENTITY_RFRMGR_LEAGUES = createIdentity(Leagues.RFRMGR_LEAGUES, Leagues.RFRMGR_LEAGUES.ID);
        public static Identity<LeagueGamesRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_GAMES = createIdentity(LeagueGames.RFRMGR_LEAGUE_GAMES, LeagueGames.RFRMGR_LEAGUE_GAMES.ID);
        public static Identity<LeagueGameTeamsRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_GAME_TEAMS = createIdentity(LeagueGameTeams.RFRMGR_LEAGUE_GAME_TEAMS, LeagueGameTeams.RFRMGR_LEAGUE_GAME_TEAMS.ID);
        public static Identity<LeagueGameTeamTypesRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_GAME_TEAM_TYPES = createIdentity(LeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES, LeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES.ID);
        public static Identity<LeaguePlannedRefereesRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_PLANNED_REFEREES = createIdentity(LeaguePlannedReferees.RFRMGR_LEAGUE_PLANNED_REFEREES, LeaguePlannedReferees.RFRMGR_LEAGUE_PLANNED_REFEREES.ID);
        public static Identity<LeagueTypesRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_TYPES = createIdentity(LeagueTypes.RFRMGR_LEAGUE_TYPES, LeagueTypes.RFRMGR_LEAGUE_TYPES.ID);
        public static Identity<PeopleRecord, UInteger> IDENTITY_RFRMGR_PEOPLE = createIdentity(People.RFRMGR_PEOPLE, People.RFRMGR_PEOPLE.ID);
        public static Identity<PersonPreferencesRecord, UInteger> IDENTITY_RFRMGR_PERSON_PREFERENCES = createIdentity(PersonPreferences.RFRMGR_PERSON_PREFERENCES, PersonPreferences.RFRMGR_PERSON_PREFERENCES.ID);
        public static Identity<PhoneNumbersRecord, UInteger> IDENTITY_RFRMGR_PHONE_NUMBERS = createIdentity(PhoneNumbers.RFRMGR_PHONE_NUMBERS, PhoneNumbers.RFRMGR_PHONE_NUMBERS.ID);
        public static Identity<PicturesRecord, UInteger> IDENTITY_RFRMGR_PICTURES = createIdentity(Pictures.RFRMGR_PICTURES, Pictures.RFRMGR_PICTURES.ID);
        public static Identity<RefereesRecord, UInteger> IDENTITY_RFRMGR_REFEREES = createIdentity(Referees.RFRMGR_REFEREES, Referees.RFRMGR_REFEREES.ID);
        public static Identity<RefereeAssignmentsRecord, UInteger> IDENTITY_RFRMGR_REFEREE_ASSIGNMENTS = createIdentity(RefereeAssignments.RFRMGR_REFEREE_ASSIGNMENTS, RefereeAssignments.RFRMGR_REFEREE_ASSIGNMENTS.ID);
        public static Identity<RefereeAssignmentRemarkTypesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES = createIdentity(RefereeAssignmentRemarkTypes.RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES, RefereeAssignmentRemarkTypes.RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES.ID);
        public static Identity<RefereeAssignmentStatusTypesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES = createIdentity(RefereeAssignmentStatusTypes.RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES, RefereeAssignmentStatusTypes.RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES.ID);
        public static Identity<RefereeAssignmentTypesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_ASSIGNMENT_TYPES = createIdentity(RefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES, RefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES.ID);
        public static Identity<RefereeRelationsRecord, UInteger> IDENTITY_RFRMGR_REFEREE_RELATIONS = createIdentity(RefereeRelations.RFRMGR_REFEREE_RELATIONS, RefereeRelations.RFRMGR_REFEREE_RELATIONS.ID);
        public static Identity<RefereeRelationTypesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_RELATION_TYPES = createIdentity(RefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES, RefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES.ID);
        public static Identity<RefereeReportsRecord, UInteger> IDENTITY_RFRMGR_REFEREE_REPORTS = createIdentity(RefereeReports.RFRMGR_REFEREE_REPORTS, RefereeReports.RFRMGR_REFEREE_REPORTS.ID);
        public static Identity<RefereeReportRecipientsRecord, UInteger> IDENTITY_RFRMGR_REFEREE_REPORT_RECIPIENTS = createIdentity(RefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS, RefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS.ID);
        public static Identity<RefereeStatusesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_STATUSES = createIdentity(RefereeStatuses.RFRMGR_REFEREE_STATUSES, RefereeStatuses.RFRMGR_REFEREE_STATUSES.ID);
        public static Identity<SeasonsRecord, UInteger> IDENTITY_RFRMGR_SEASONS = createIdentity(Seasons.RFRMGR_SEASONS, Seasons.RFRMGR_SEASONS.ID);
        public static Identity<SexTypesRecord, UInteger> IDENTITY_RFRMGR_SEX_TYPES = createIdentity(SexTypes.RFRMGR_SEX_TYPES, SexTypes.RFRMGR_SEX_TYPES.ID);
        public static Identity<SpokespeopleRecord, UInteger> IDENTITY_RFRMGR_SPOKESPEOPLE = createIdentity(Spokespeople.RFRMGR_SPOKESPEOPLE, Spokespeople.RFRMGR_SPOKESPEOPLE.ID);
        public static Identity<StatusTypesRecord, UInteger> IDENTITY_RFRMGR_STATUS_TYPES = createIdentity(StatusTypes.RFRMGR_STATUS_TYPES, StatusTypes.RFRMGR_STATUS_TYPES.ID);
        public static Identity<TeamsRecord, UInteger> IDENTITY_RFRMGR_TEAMS = createIdentity(Teams.RFRMGR_TEAMS, Teams.RFRMGR_TEAMS.ID);
        public static Identity<TeamSeasonsRecord, UInteger> IDENTITY_RFRMGR_TEAM_SEASONS = createIdentity(TeamSeasons.RFRMGR_TEAM_SEASONS, TeamSeasons.RFRMGR_TEAM_SEASONS.ID);
        public static Identity<TeamVenuesRecord, UInteger> IDENTITY_RFRMGR_TEAM_VENUES = createIdentity(TeamVenues.RFRMGR_TEAM_VENUES, TeamVenues.RFRMGR_TEAM_VENUES.ID);
        public static Identity<TournamentsRecord, UInteger> IDENTITY_RFRMGR_TOURNAMENTS = createIdentity(Tournaments.RFRMGR_TOURNAMENTS, Tournaments.RFRMGR_TOURNAMENTS.ID);
        public static Identity<TournamentGamesRecord, UInteger> IDENTITY_RFRMGR_TOURNAMENT_GAMES = createIdentity(TournamentGames.RFRMGR_TOURNAMENT_GAMES, TournamentGames.RFRMGR_TOURNAMENT_GAMES.ID);
        public static Identity<TournamentVenuesRecord, UInteger> IDENTITY_RFRMGR_TOURNAMENT_VENUES = createIdentity(TournamentVenues.RFRMGR_TOURNAMENT_VENUES, TournamentVenues.RFRMGR_TOURNAMENT_VENUES.ID);
        public static Identity<TrainingLevelsRecord, UInteger> IDENTITY_RFRMGR_TRAINING_LEVELS = createIdentity(TrainingLevels.RFRMGR_TRAINING_LEVELS, TrainingLevels.RFRMGR_TRAINING_LEVELS.ID);
        public static Identity<TrainingLevelTypesRecord, UInteger> IDENTITY_RFRMGR_TRAINING_LEVEL_TYPES = createIdentity(TrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES, TrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES.ID);
        public static Identity<TrainingUpdatesRecord, UInteger> IDENTITY_RFRMGR_TRAINING_UPDATES = createIdentity(TrainingUpdates.RFRMGR_TRAINING_UPDATES, TrainingUpdates.RFRMGR_TRAINING_UPDATES.ID);
        public static Identity<UrlsRecord, UInteger> IDENTITY_RFRMGR_URLS = createIdentity(Urls.RFRMGR_URLS, Urls.RFRMGR_URLS.ID);
        public static Identity<UsersRecord, UInteger> IDENTITY_RFRMGR_USERS = createIdentity(Users.RFRMGR_USERS, Users.RFRMGR_USERS.ID);
        public static Identity<UserRolesRecord, UInteger> IDENTITY_RFRMGR_USER_ROLES = createIdentity(UserRoles.RFRMGR_USER_ROLES, UserRoles.RFRMGR_USER_ROLES.ID);
        public static Identity<WishesRecord, UInteger> IDENTITY_RFRMGR_WISHES = createIdentity(Wishes.RFRMGR_WISHES, Wishes.RFRMGR_WISHES.ID);
        public static Identity<WishTypesRecord, UInteger> IDENTITY_RFRMGR_WISH_TYPES = createIdentity(WishTypes.RFRMGR_WISH_TYPES, WishTypes.RFRMGR_WISH_TYPES.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ActivityLogsRecord> KEY_RFRMGR_ACTIVITY_LOGS_PRIMARY = createUniqueKey(ActivityLogs.RFRMGR_ACTIVITY_LOGS, "KEY_rfrmgr_activity_logs_PRIMARY", ActivityLogs.RFRMGR_ACTIVITY_LOGS.ID);
        public static final UniqueKey<ActivityLogsRecord> KEY_RFRMGR_ACTIVITY_LOGS_ID_UNIQUE = createUniqueKey(ActivityLogs.RFRMGR_ACTIVITY_LOGS, "KEY_rfrmgr_activity_logs_id_UNIQUE", ActivityLogs.RFRMGR_ACTIVITY_LOGS.ID);
        public static final UniqueKey<AddressesRecord> KEY_RFRMGR_ADDRESSES_PRIMARY = createUniqueKey(Addresses.RFRMGR_ADDRESSES, "KEY_rfrmgr_addresses_PRIMARY", Addresses.RFRMGR_ADDRESSES.ID);
        public static final UniqueKey<AddressesRecord> KEY_RFRMGR_ADDRESSES_ID_UNIQUE = createUniqueKey(Addresses.RFRMGR_ADDRESSES, "KEY_rfrmgr_addresses_id_UNIQUE", Addresses.RFRMGR_ADDRESSES.ID);
        public static final UniqueKey<AssignmentsRecord> KEY_RFRMGR_ASSIGNMENTS_PRIMARY = createUniqueKey(Assignments.RFRMGR_ASSIGNMENTS, "KEY_rfrmgr_assignments_PRIMARY", Assignments.RFRMGR_ASSIGNMENTS.ID);
        public static final UniqueKey<AssignmentsRecord> KEY_RFRMGR_ASSIGNMENTS_ID_UNIQUE = createUniqueKey(Assignments.RFRMGR_ASSIGNMENTS, "KEY_rfrmgr_assignments_id_UNIQUE", Assignments.RFRMGR_ASSIGNMENTS.ID);
        public static final UniqueKey<ClubsRecord> KEY_RFRMGR_CLUBS_PRIMARY = createUniqueKey(Clubs.RFRMGR_CLUBS, "KEY_rfrmgr_clubs_PRIMARY", Clubs.RFRMGR_CLUBS.ID);
        public static final UniqueKey<ClubsRecord> KEY_RFRMGR_CLUBS_ID_UNIQUE = createUniqueKey(Clubs.RFRMGR_CLUBS, "KEY_rfrmgr_clubs_id_UNIQUE", Clubs.RFRMGR_CLUBS.ID);
        public static final UniqueKey<ContactsRecord> KEY_RFRMGR_CONTACTS_PRIMARY = createUniqueKey(Contacts.RFRMGR_CONTACTS, "KEY_rfrmgr_contacts_PRIMARY", Contacts.RFRMGR_CONTACTS.ID);
        public static final UniqueKey<ContactsRecord> KEY_RFRMGR_CONTACTS_ID_UNIQUE = createUniqueKey(Contacts.RFRMGR_CONTACTS, "KEY_rfrmgr_contacts_id_UNIQUE", Contacts.RFRMGR_CONTACTS.ID);
        public static final UniqueKey<ContactTypesRecord> KEY_RFRMGR_CONTACT_TYPES_PRIMARY = createUniqueKey(ContactTypes.RFRMGR_CONTACT_TYPES, "KEY_rfrmgr_contact_types_PRIMARY", ContactTypes.RFRMGR_CONTACT_TYPES.ID);
        public static final UniqueKey<ContactTypesRecord> KEY_RFRMGR_CONTACT_TYPES_ID_UNIQUE = createUniqueKey(ContactTypes.RFRMGR_CONTACT_TYPES, "KEY_rfrmgr_contact_types_id_UNIQUE", ContactTypes.RFRMGR_CONTACT_TYPES.ID);
        public static final UniqueKey<ContactTypesRecord> KEY_RFRMGR_CONTACT_TYPES_SID_UNIQUE = createUniqueKey(ContactTypes.RFRMGR_CONTACT_TYPES, "KEY_rfrmgr_contact_types_sid_UNIQUE", ContactTypes.RFRMGR_CONTACT_TYPES.TITLE);
        public static final UniqueKey<DatabaseColumnsRecord> KEY_RFRMGR_DATABASE_COLUMNS_PRIMARY = createUniqueKey(DatabaseColumns.RFRMGR_DATABASE_COLUMNS, "KEY_rfrmgr_database_columns_PRIMARY", DatabaseColumns.RFRMGR_DATABASE_COLUMNS.ID);
        public static final UniqueKey<DatabaseColumnsRecord> KEY_RFRMGR_DATABASE_COLUMNS_ID_UNIQUE = createUniqueKey(DatabaseColumns.RFRMGR_DATABASE_COLUMNS, "KEY_rfrmgr_database_columns_id_UNIQUE", DatabaseColumns.RFRMGR_DATABASE_COLUMNS.ID);
        public static final UniqueKey<DatabaseColumnsRecord> KEY_RFRMGR_DATABASE_COLUMNS_SID_UNIQUE = createUniqueKey(DatabaseColumns.RFRMGR_DATABASE_COLUMNS, "KEY_rfrmgr_database_columns_sid_UNIQUE", DatabaseColumns.RFRMGR_DATABASE_COLUMNS.COLUMN_NAME);
        public static final UniqueKey<DatabaseTablesRecord> KEY_RFRMGR_DATABASE_TABLES_PRIMARY = createUniqueKey(DatabaseTables.RFRMGR_DATABASE_TABLES, "KEY_rfrmgr_database_tables_PRIMARY", DatabaseTables.RFRMGR_DATABASE_TABLES.ID);
        public static final UniqueKey<DatabaseTablesRecord> KEY_RFRMGR_DATABASE_TABLES_ID_UNIQUE = createUniqueKey(DatabaseTables.RFRMGR_DATABASE_TABLES, "KEY_rfrmgr_database_tables_id_UNIQUE", DatabaseTables.RFRMGR_DATABASE_TABLES.ID);
        public static final UniqueKey<DatabaseTablesRecord> KEY_RFRMGR_DATABASE_TABLES_SID_UNIQUE = createUniqueKey(DatabaseTables.RFRMGR_DATABASE_TABLES, "KEY_rfrmgr_database_tables_sid_UNIQUE", DatabaseTables.RFRMGR_DATABASE_TABLES.TABLE_NAME);
        public static final UniqueKey<EmailsRecord> KEY_RFRMGR_EMAILS_PRIMARY = createUniqueKey(Emails.RFRMGR_EMAILS, "KEY_rfrmgr_emails_PRIMARY", Emails.RFRMGR_EMAILS.ID);
        public static final UniqueKey<EmailsRecord> KEY_RFRMGR_EMAILS_ID_UNIQUE = createUniqueKey(Emails.RFRMGR_EMAILS, "KEY_rfrmgr_emails_id_UNIQUE", Emails.RFRMGR_EMAILS.ID);
        public static final UniqueKey<LeaguesRecord> KEY_RFRMGR_LEAGUES_PRIMARY = createUniqueKey(Leagues.RFRMGR_LEAGUES, "KEY_rfrmgr_leagues_PRIMARY", Leagues.RFRMGR_LEAGUES.ID);
        public static final UniqueKey<LeaguesRecord> KEY_RFRMGR_LEAGUES_ID_UNIQUE = createUniqueKey(Leagues.RFRMGR_LEAGUES, "KEY_rfrmgr_leagues_id_UNIQUE", Leagues.RFRMGR_LEAGUES.ID);
        public static final UniqueKey<LeagueGamesRecord> KEY_RFRMGR_LEAGUE_GAMES_PRIMARY = createUniqueKey(LeagueGames.RFRMGR_LEAGUE_GAMES, "KEY_rfrmgr_league_games_PRIMARY", LeagueGames.RFRMGR_LEAGUE_GAMES.ID);
        public static final UniqueKey<LeagueGamesRecord> KEY_RFRMGR_LEAGUE_GAMES_ID_UNIQUE = createUniqueKey(LeagueGames.RFRMGR_LEAGUE_GAMES, "KEY_rfrmgr_league_games_id_UNIQUE", LeagueGames.RFRMGR_LEAGUE_GAMES.ID);
        public static final UniqueKey<LeagueGameTeamsRecord> KEY_RFRMGR_LEAGUE_GAME_TEAMS_PRIMARY = createUniqueKey(LeagueGameTeams.RFRMGR_LEAGUE_GAME_TEAMS, "KEY_rfrmgr_league_game_teams_PRIMARY", LeagueGameTeams.RFRMGR_LEAGUE_GAME_TEAMS.ID);
        public static final UniqueKey<LeagueGameTeamsRecord> KEY_RFRMGR_LEAGUE_GAME_TEAMS_ID_UNIQUE = createUniqueKey(LeagueGameTeams.RFRMGR_LEAGUE_GAME_TEAMS, "KEY_rfrmgr_league_game_teams_id_UNIQUE", LeagueGameTeams.RFRMGR_LEAGUE_GAME_TEAMS.ID);
        public static final UniqueKey<LeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_PRIMARY = createUniqueKey(LeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES, "KEY_rfrmgr_league_game_team_types_PRIMARY", LeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES.ID);
        public static final UniqueKey<LeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_ID_UNIQUE = createUniqueKey(LeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES, "KEY_rfrmgr_league_game_team_types_id_UNIQUE", LeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES.ID);
        public static final UniqueKey<LeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_SID_UNIQUE = createUniqueKey(LeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES, "KEY_rfrmgr_league_game_team_types_sid_UNIQUE", LeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES.SID);
        public static final UniqueKey<LeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_TITLE_UNIQUE = createUniqueKey(LeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES, "KEY_rfrmgr_league_game_team_types_title_UNIQUE", LeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES.TITLE);
        public static final UniqueKey<LeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_ABBREVIATION_UNIQUE = createUniqueKey(LeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES, "KEY_rfrmgr_league_game_team_types_abbreviation_UNIQUE", LeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES.ABBREVIATION);
        public static final UniqueKey<LeaguePlannedRefereesRecord> KEY_RFRMGR_LEAGUE_PLANNED_REFEREES_PRIMARY = createUniqueKey(LeaguePlannedReferees.RFRMGR_LEAGUE_PLANNED_REFEREES, "KEY_rfrmgr_league_planned_referees_PRIMARY", LeaguePlannedReferees.RFRMGR_LEAGUE_PLANNED_REFEREES.ID);
        public static final UniqueKey<LeaguePlannedRefereesRecord> KEY_RFRMGR_LEAGUE_PLANNED_REFEREES_ID_UNIQUE = createUniqueKey(LeaguePlannedReferees.RFRMGR_LEAGUE_PLANNED_REFEREES, "KEY_rfrmgr_league_planned_referees_id_UNIQUE", LeaguePlannedReferees.RFRMGR_LEAGUE_PLANNED_REFEREES.ID);
        public static final UniqueKey<LeagueTypesRecord> KEY_RFRMGR_LEAGUE_TYPES_PRIMARY = createUniqueKey(LeagueTypes.RFRMGR_LEAGUE_TYPES, "KEY_rfrmgr_league_types_PRIMARY", LeagueTypes.RFRMGR_LEAGUE_TYPES.ID);
        public static final UniqueKey<LeagueTypesRecord> KEY_RFRMGR_LEAGUE_TYPES_ID_UNIQUE = createUniqueKey(LeagueTypes.RFRMGR_LEAGUE_TYPES, "KEY_rfrmgr_league_types_id_UNIQUE", LeagueTypes.RFRMGR_LEAGUE_TYPES.ID);
        public static final UniqueKey<LeagueTypesRecord> KEY_RFRMGR_LEAGUE_TYPES_TITLE_UNIQUE = createUniqueKey(LeagueTypes.RFRMGR_LEAGUE_TYPES, "KEY_rfrmgr_league_types_title_UNIQUE", LeagueTypes.RFRMGR_LEAGUE_TYPES.TITLE);
        public static final UniqueKey<PeopleRecord> KEY_RFRMGR_PEOPLE_ID_UNIQUE = createUniqueKey(People.RFRMGR_PEOPLE, "KEY_rfrmgr_people_id_UNIQUE", People.RFRMGR_PEOPLE.ID);
        public static final UniqueKey<PersonPreferencesRecord> KEY_RFRMGR_PERSON_PREFERENCES_PRIMARY = createUniqueKey(PersonPreferences.RFRMGR_PERSON_PREFERENCES, "KEY_rfrmgr_person_preferences_PRIMARY", PersonPreferences.RFRMGR_PERSON_PREFERENCES.ID);
        public static final UniqueKey<PersonPreferencesRecord> KEY_RFRMGR_PERSON_PREFERENCES_ID_UNIQUE = createUniqueKey(PersonPreferences.RFRMGR_PERSON_PREFERENCES, "KEY_rfrmgr_person_preferences_id_UNIQUE", PersonPreferences.RFRMGR_PERSON_PREFERENCES.ID);
        public static final UniqueKey<PersonPreferencesRecord> KEY_RFRMGR_PERSON_PREFERENCES_SID_UNIQUE = createUniqueKey(PersonPreferences.RFRMGR_PERSON_PREFERENCES, "KEY_rfrmgr_person_preferences_sid_UNIQUE", PersonPreferences.RFRMGR_PERSON_PREFERENCES.PERSON_ID);
        public static final UniqueKey<PhoneNumbersRecord> KEY_RFRMGR_PHONE_NUMBERS_PRIMARY = createUniqueKey(PhoneNumbers.RFRMGR_PHONE_NUMBERS, "KEY_rfrmgr_phone_numbers_PRIMARY", PhoneNumbers.RFRMGR_PHONE_NUMBERS.ID);
        public static final UniqueKey<PhoneNumbersRecord> KEY_RFRMGR_PHONE_NUMBERS_ID_UNIQUE = createUniqueKey(PhoneNumbers.RFRMGR_PHONE_NUMBERS, "KEY_rfrmgr_phone_numbers_id_UNIQUE", PhoneNumbers.RFRMGR_PHONE_NUMBERS.ID);
        public static final UniqueKey<PicturesRecord> KEY_RFRMGR_PICTURES_PRIMARY = createUniqueKey(Pictures.RFRMGR_PICTURES, "KEY_rfrmgr_pictures_PRIMARY", Pictures.RFRMGR_PICTURES.ID);
        public static final UniqueKey<PicturesRecord> KEY_RFRMGR_PICTURES_ID_UNIQUE = createUniqueKey(Pictures.RFRMGR_PICTURES, "KEY_rfrmgr_pictures_id_UNIQUE", Pictures.RFRMGR_PICTURES.ID);
        public static final UniqueKey<RefereesRecord> KEY_RFRMGR_REFEREES_PRIMARY = createUniqueKey(Referees.RFRMGR_REFEREES, "KEY_rfrmgr_referees_PRIMARY", Referees.RFRMGR_REFEREES.ID);
        public static final UniqueKey<RefereesRecord> KEY_RFRMGR_REFEREES_ID_UNIQUE = createUniqueKey(Referees.RFRMGR_REFEREES, "KEY_rfrmgr_referees_id_UNIQUE", Referees.RFRMGR_REFEREES.ID);
        public static final UniqueKey<RefereeAssignmentsRecord> KEY_RFRMGR_REFEREE_ASSIGNMENTS_PRIMARY = createUniqueKey(RefereeAssignments.RFRMGR_REFEREE_ASSIGNMENTS, "KEY_rfrmgr_referee_assignments_PRIMARY", RefereeAssignments.RFRMGR_REFEREE_ASSIGNMENTS.ID);
        public static final UniqueKey<RefereeAssignmentsRecord> KEY_RFRMGR_REFEREE_ASSIGNMENTS_ID_UNIQUE = createUniqueKey(RefereeAssignments.RFRMGR_REFEREE_ASSIGNMENTS, "KEY_rfrmgr_referee_assignments_id_UNIQUE", RefereeAssignments.RFRMGR_REFEREE_ASSIGNMENTS.ID);
        public static final UniqueKey<RefereeAssignmentRemarkTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES_PRIMARY = createUniqueKey(RefereeAssignmentRemarkTypes.RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES, "KEY_rfrmgr_referee_assignment_remark_types_PRIMARY", RefereeAssignmentRemarkTypes.RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES.ID);
        public static final UniqueKey<RefereeAssignmentRemarkTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES_ID_UNIQUE = createUniqueKey(RefereeAssignmentRemarkTypes.RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES, "KEY_rfrmgr_referee_assignment_remark_types_id_UNIQUE", RefereeAssignmentRemarkTypes.RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES.ID);
        public static final UniqueKey<RefereeAssignmentRemarkTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES_TITLE_UNIQUE = createUniqueKey(RefereeAssignmentRemarkTypes.RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES, "KEY_rfrmgr_referee_assignment_remark_types_title_UNIQUE", RefereeAssignmentRemarkTypes.RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES.TITLE);
        public static final UniqueKey<RefereeAssignmentStatusTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES_PRIMARY = createUniqueKey(RefereeAssignmentStatusTypes.RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES, "KEY_rfrmgr_referee_assignment_status_types_PRIMARY", RefereeAssignmentStatusTypes.RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES.ID);
        public static final UniqueKey<RefereeAssignmentStatusTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES_ID_UNIQUE = createUniqueKey(RefereeAssignmentStatusTypes.RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES, "KEY_rfrmgr_referee_assignment_status_types_id_UNIQUE", RefereeAssignmentStatusTypes.RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES.ID);
        public static final UniqueKey<RefereeAssignmentStatusTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES_TITLE_UNIQUE = createUniqueKey(RefereeAssignmentStatusTypes.RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES, "KEY_rfrmgr_referee_assignment_status_types_title_UNIQUE", RefereeAssignmentStatusTypes.RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES.SID);
        public static final UniqueKey<RefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_PRIMARY = createUniqueKey(RefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES, "KEY_rfrmgr_referee_assignment_types_PRIMARY", RefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES.ID);
        public static final UniqueKey<RefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_ID_UNIQUE = createUniqueKey(RefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES, "KEY_rfrmgr_referee_assignment_types_id_UNIQUE", RefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES.ID);
        public static final UniqueKey<RefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_SID_UNIQUE = createUniqueKey(RefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES, "KEY_rfrmgr_referee_assignment_types_sid_UNIQUE", RefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES.SID);
        public static final UniqueKey<RefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_TITLE_UNIQUE = createUniqueKey(RefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES, "KEY_rfrmgr_referee_assignment_types_title_UNIQUE", RefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES.TITLE);
        public static final UniqueKey<RefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_ABBREVIATION_UNIQUE = createUniqueKey(RefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES, "KEY_rfrmgr_referee_assignment_types_abbreviation_UNIQUE", RefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES.ABBREVIATION);
        public static final UniqueKey<RefereeRelationsRecord> KEY_RFRMGR_REFEREE_RELATIONS_PRIMARY = createUniqueKey(RefereeRelations.RFRMGR_REFEREE_RELATIONS, "KEY_rfrmgr_referee_relations_PRIMARY", RefereeRelations.RFRMGR_REFEREE_RELATIONS.ID);
        public static final UniqueKey<RefereeRelationsRecord> KEY_RFRMGR_REFEREE_RELATIONS_ID_UNIQUE = createUniqueKey(RefereeRelations.RFRMGR_REFEREE_RELATIONS, "KEY_rfrmgr_referee_relations_id_UNIQUE", RefereeRelations.RFRMGR_REFEREE_RELATIONS.ID);
        public static final UniqueKey<RefereeRelationTypesRecord> KEY_RFRMGR_REFEREE_RELATION_TYPES_PRIMARY = createUniqueKey(RefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES, "KEY_rfrmgr_referee_relation_types_PRIMARY", RefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES.ID);
        public static final UniqueKey<RefereeRelationTypesRecord> KEY_RFRMGR_REFEREE_RELATION_TYPES_ID_UNIQUE = createUniqueKey(RefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES, "KEY_rfrmgr_referee_relation_types_id_UNIQUE", RefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES.ID);
        public static final UniqueKey<RefereeRelationTypesRecord> KEY_RFRMGR_REFEREE_RELATION_TYPES_SID_UNIQUE = createUniqueKey(RefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES, "KEY_rfrmgr_referee_relation_types_sid_UNIQUE", RefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES.SID);
        public static final UniqueKey<RefereeRelationTypesRecord> KEY_RFRMGR_REFEREE_RELATION_TYPES_TITLE_UNIQUE = createUniqueKey(RefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES, "KEY_rfrmgr_referee_relation_types_title_UNIQUE", RefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES.TITLE);
        public static final UniqueKey<RefereeReportsRecord> KEY_RFRMGR_REFEREE_REPORTS_PRIMARY = createUniqueKey(RefereeReports.RFRMGR_REFEREE_REPORTS, "KEY_rfrmgr_referee_reports_PRIMARY", RefereeReports.RFRMGR_REFEREE_REPORTS.ID);
        public static final UniqueKey<RefereeReportsRecord> KEY_RFRMGR_REFEREE_REPORTS_ID_UNIQUE = createUniqueKey(RefereeReports.RFRMGR_REFEREE_REPORTS, "KEY_rfrmgr_referee_reports_id_UNIQUE", RefereeReports.RFRMGR_REFEREE_REPORTS.ID);
        public static final UniqueKey<RefereeReportRecipientsRecord> KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_PRIMARY = createUniqueKey(RefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS, "KEY_rfrmgr_referee_report_recipients_PRIMARY", RefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS.ID);
        public static final UniqueKey<RefereeReportRecipientsRecord> KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_ID_UNIQUE = createUniqueKey(RefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS, "KEY_rfrmgr_referee_report_recipients_id_UNIQUE", RefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS.ID);
        public static final UniqueKey<RefereeReportRecipientsRecord> KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_TITLE_UNIQUE = createUniqueKey(RefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS, "KEY_rfrmgr_referee_report_recipients_title_UNIQUE", RefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS.REFEREE_REPORT_ID);
        public static final UniqueKey<RefereeReportRecipientsRecord> KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_PERSON_ID_UNIQUE = createUniqueKey(RefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS, "KEY_rfrmgr_referee_report_recipients_person_id_UNIQUE", RefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS.PERSON_ID);
        public static final UniqueKey<RefereeStatusesRecord> KEY_RFRMGR_REFEREE_STATUSES_PRIMARY = createUniqueKey(RefereeStatuses.RFRMGR_REFEREE_STATUSES, "KEY_rfrmgr_referee_statuses_PRIMARY", RefereeStatuses.RFRMGR_REFEREE_STATUSES.ID);
        public static final UniqueKey<RefereeStatusesRecord> KEY_RFRMGR_REFEREE_STATUSES_ID_UNIQUE = createUniqueKey(RefereeStatuses.RFRMGR_REFEREE_STATUSES, "KEY_rfrmgr_referee_statuses_id_UNIQUE", RefereeStatuses.RFRMGR_REFEREE_STATUSES.ID);
        public static final UniqueKey<SeasonsRecord> KEY_RFRMGR_SEASONS_PRIMARY = createUniqueKey(Seasons.RFRMGR_SEASONS, "KEY_rfrmgr_seasons_PRIMARY", Seasons.RFRMGR_SEASONS.ID);
        public static final UniqueKey<SeasonsRecord> KEY_RFRMGR_SEASONS_ID_UNIQUE = createUniqueKey(Seasons.RFRMGR_SEASONS, "KEY_rfrmgr_seasons_id_UNIQUE", Seasons.RFRMGR_SEASONS.ID);
        public static final UniqueKey<SeasonsRecord> KEY_RFRMGR_SEASONS_YEAR_START_UNIQUE = createUniqueKey(Seasons.RFRMGR_SEASONS, "KEY_rfrmgr_seasons_year_start_UNIQUE", Seasons.RFRMGR_SEASONS.YEAR_START);
        public static final UniqueKey<SexTypesRecord> KEY_RFRMGR_SEX_TYPES_PRIMARY = createUniqueKey(SexTypes.RFRMGR_SEX_TYPES, "KEY_rfrmgr_sex_types_PRIMARY", SexTypes.RFRMGR_SEX_TYPES.ID);
        public static final UniqueKey<SexTypesRecord> KEY_RFRMGR_SEX_TYPES_ID_UNIQUE = createUniqueKey(SexTypes.RFRMGR_SEX_TYPES, "KEY_rfrmgr_sex_types_id_UNIQUE", SexTypes.RFRMGR_SEX_TYPES.ID);
        public static final UniqueKey<SexTypesRecord> KEY_RFRMGR_SEX_TYPES_SID_UNIQUE = createUniqueKey(SexTypes.RFRMGR_SEX_TYPES, "KEY_rfrmgr_sex_types_sid_UNIQUE", SexTypes.RFRMGR_SEX_TYPES.SID);
        public static final UniqueKey<SpokespeopleRecord> KEY_RFRMGR_SPOKESPEOPLE_PRIMARY = createUniqueKey(Spokespeople.RFRMGR_SPOKESPEOPLE, "KEY_rfrmgr_spokespeople_PRIMARY", Spokespeople.RFRMGR_SPOKESPEOPLE.ID);
        public static final UniqueKey<SpokespeopleRecord> KEY_RFRMGR_SPOKESPEOPLE_ID_UNIQUE = createUniqueKey(Spokespeople.RFRMGR_SPOKESPEOPLE, "KEY_rfrmgr_spokespeople_id_UNIQUE", Spokespeople.RFRMGR_SPOKESPEOPLE.ID);
        public static final UniqueKey<StatusTypesRecord> KEY_RFRMGR_STATUS_TYPES_PRIMARY = createUniqueKey(StatusTypes.RFRMGR_STATUS_TYPES, "KEY_rfrmgr_status_types_PRIMARY", StatusTypes.RFRMGR_STATUS_TYPES.ID);
        public static final UniqueKey<StatusTypesRecord> KEY_RFRMGR_STATUS_TYPES_ID_UNIQUE = createUniqueKey(StatusTypes.RFRMGR_STATUS_TYPES, "KEY_rfrmgr_status_types_id_UNIQUE", StatusTypes.RFRMGR_STATUS_TYPES.ID);
        public static final UniqueKey<StatusTypesRecord> KEY_RFRMGR_STATUS_TYPES_SID_UNIQUE = createUniqueKey(StatusTypes.RFRMGR_STATUS_TYPES, "KEY_rfrmgr_status_types_sid_UNIQUE", StatusTypes.RFRMGR_STATUS_TYPES.SID);
        public static final UniqueKey<StatusTypesRecord> KEY_RFRMGR_STATUS_TYPES_TITLE_UNIQUE = createUniqueKey(StatusTypes.RFRMGR_STATUS_TYPES, "KEY_rfrmgr_status_types_title_UNIQUE", StatusTypes.RFRMGR_STATUS_TYPES.TITLE);
        public static final UniqueKey<TeamsRecord> KEY_RFRMGR_TEAMS_PRIMARY = createUniqueKey(Teams.RFRMGR_TEAMS, "KEY_rfrmgr_teams_PRIMARY", Teams.RFRMGR_TEAMS.ID);
        public static final UniqueKey<TeamsRecord> KEY_RFRMGR_TEAMS_ID_UNIQUE = createUniqueKey(Teams.RFRMGR_TEAMS, "KEY_rfrmgr_teams_id_UNIQUE", Teams.RFRMGR_TEAMS.ID);
        public static final UniqueKey<TeamSeasonsRecord> KEY_RFRMGR_TEAM_SEASONS_PRIMARY = createUniqueKey(TeamSeasons.RFRMGR_TEAM_SEASONS, "KEY_rfrmgr_team_seasons_PRIMARY", TeamSeasons.RFRMGR_TEAM_SEASONS.ID);
        public static final UniqueKey<TeamSeasonsRecord> KEY_RFRMGR_TEAM_SEASONS_ID_UNIQUE = createUniqueKey(TeamSeasons.RFRMGR_TEAM_SEASONS, "KEY_rfrmgr_team_seasons_id_UNIQUE", TeamSeasons.RFRMGR_TEAM_SEASONS.ID);
        public static final UniqueKey<TeamVenuesRecord> KEY_RFRMGR_TEAM_VENUES_PRIMARY = createUniqueKey(TeamVenues.RFRMGR_TEAM_VENUES, "KEY_rfrmgr_team_venues_PRIMARY", TeamVenues.RFRMGR_TEAM_VENUES.ID);
        public static final UniqueKey<TeamVenuesRecord> KEY_RFRMGR_TEAM_VENUES_ID_UNIQUE = createUniqueKey(TeamVenues.RFRMGR_TEAM_VENUES, "KEY_rfrmgr_team_venues_id_UNIQUE", TeamVenues.RFRMGR_TEAM_VENUES.ID);
        public static final UniqueKey<TournamentsRecord> KEY_RFRMGR_TOURNAMENTS_PRIMARY = createUniqueKey(Tournaments.RFRMGR_TOURNAMENTS, "KEY_rfrmgr_tournaments_PRIMARY", Tournaments.RFRMGR_TOURNAMENTS.ID);
        public static final UniqueKey<TournamentsRecord> KEY_RFRMGR_TOURNAMENTS_ID_UNIQUE = createUniqueKey(Tournaments.RFRMGR_TOURNAMENTS, "KEY_rfrmgr_tournaments_id_UNIQUE", Tournaments.RFRMGR_TOURNAMENTS.ID);
        public static final UniqueKey<TournamentsRecord> KEY_RFRMGR_TOURNAMENTS_ABBREVIATION_UNIQUE = createUniqueKey(Tournaments.RFRMGR_TOURNAMENTS, "KEY_rfrmgr_tournaments_abbreviation_UNIQUE", Tournaments.RFRMGR_TOURNAMENTS.NAME);
        public static final UniqueKey<TournamentGamesRecord> KEY_RFRMGR_TOURNAMENT_GAMES_PRIMARY = createUniqueKey(TournamentGames.RFRMGR_TOURNAMENT_GAMES, "KEY_rfrmgr_tournament_games_PRIMARY", TournamentGames.RFRMGR_TOURNAMENT_GAMES.ID);
        public static final UniqueKey<TournamentGamesRecord> KEY_RFRMGR_TOURNAMENT_GAMES_ID_UNIQUE = createUniqueKey(TournamentGames.RFRMGR_TOURNAMENT_GAMES, "KEY_rfrmgr_tournament_games_id_UNIQUE", TournamentGames.RFRMGR_TOURNAMENT_GAMES.ID);
        public static final UniqueKey<TournamentVenuesRecord> KEY_RFRMGR_TOURNAMENT_VENUES_PRIMARY = createUniqueKey(TournamentVenues.RFRMGR_TOURNAMENT_VENUES, "KEY_rfrmgr_tournament_venues_PRIMARY", TournamentVenues.RFRMGR_TOURNAMENT_VENUES.ID);
        public static final UniqueKey<TournamentVenuesRecord> KEY_RFRMGR_TOURNAMENT_VENUES_ID_UNIQUE = createUniqueKey(TournamentVenues.RFRMGR_TOURNAMENT_VENUES, "KEY_rfrmgr_tournament_venues_id_UNIQUE", TournamentVenues.RFRMGR_TOURNAMENT_VENUES.ID);
        public static final UniqueKey<TrainingLevelsRecord> KEY_RFRMGR_TRAINING_LEVELS_PRIMARY = createUniqueKey(TrainingLevels.RFRMGR_TRAINING_LEVELS, "KEY_rfrmgr_training_levels_PRIMARY", TrainingLevels.RFRMGR_TRAINING_LEVELS.ID);
        public static final UniqueKey<TrainingLevelsRecord> KEY_RFRMGR_TRAINING_LEVELS_ID_UNIQUE = createUniqueKey(TrainingLevels.RFRMGR_TRAINING_LEVELS, "KEY_rfrmgr_training_levels_id_UNIQUE", TrainingLevels.RFRMGR_TRAINING_LEVELS.ID);
        public static final UniqueKey<TrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_PRIMARY = createUniqueKey(TrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES, "KEY_rfrmgr_training_level_types_PRIMARY", TrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES.ID);
        public static final UniqueKey<TrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_ID_UNIQUE = createUniqueKey(TrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES, "KEY_rfrmgr_training_level_types_id_UNIQUE", TrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES.ID);
        public static final UniqueKey<TrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_SID_UNIQUE = createUniqueKey(TrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES, "KEY_rfrmgr_training_level_types_sid_UNIQUE", TrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES.SID);
        public static final UniqueKey<TrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_RANK_UNIQUE = createUniqueKey(TrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES, "KEY_rfrmgr_training_level_types_rank_UNIQUE", TrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES.RANK);
        public static final UniqueKey<TrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_TITLE_UNIQUE = createUniqueKey(TrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES, "KEY_rfrmgr_training_level_types_title_UNIQUE", TrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES.TITLE);
        public static final UniqueKey<TrainingUpdatesRecord> KEY_RFRMGR_TRAINING_UPDATES_PRIMARY = createUniqueKey(TrainingUpdates.RFRMGR_TRAINING_UPDATES, "KEY_rfrmgr_training_updates_PRIMARY", TrainingUpdates.RFRMGR_TRAINING_UPDATES.ID);
        public static final UniqueKey<TrainingUpdatesRecord> KEY_RFRMGR_TRAINING_UPDATES_ID_UNIQUE = createUniqueKey(TrainingUpdates.RFRMGR_TRAINING_UPDATES, "KEY_rfrmgr_training_updates_id_UNIQUE", TrainingUpdates.RFRMGR_TRAINING_UPDATES.ID);
        public static final UniqueKey<UrlsRecord> KEY_RFRMGR_URLS_PRIMARY = createUniqueKey(Urls.RFRMGR_URLS, "KEY_rfrmgr_urls_PRIMARY", Urls.RFRMGR_URLS.ID);
        public static final UniqueKey<UrlsRecord> KEY_RFRMGR_URLS_ID_UNIQUE = createUniqueKey(Urls.RFRMGR_URLS, "KEY_rfrmgr_urls_id_UNIQUE", Urls.RFRMGR_URLS.ID);
        public static final UniqueKey<UsersRecord> KEY_RFRMGR_USERS_PRIMARY = createUniqueKey(Users.RFRMGR_USERS, "KEY_rfrmgr_users_PRIMARY", Users.RFRMGR_USERS.ID);
        public static final UniqueKey<UsersRecord> KEY_RFRMGR_USERS_ID_UNIQUE = createUniqueKey(Users.RFRMGR_USERS, "KEY_rfrmgr_users_id_UNIQUE", Users.RFRMGR_USERS.ID);
        public static final UniqueKey<UsersRecord> KEY_RFRMGR_USERS_USERNAME_UNIQUE = createUniqueKey(Users.RFRMGR_USERS, "KEY_rfrmgr_users_username_UNIQUE", Users.RFRMGR_USERS.USERNAME);
        public static final UniqueKey<UserRolesRecord> KEY_RFRMGR_USER_ROLES_PRIMARY = createUniqueKey(UserRoles.RFRMGR_USER_ROLES, "KEY_rfrmgr_user_roles_PRIMARY", UserRoles.RFRMGR_USER_ROLES.ID);
        public static final UniqueKey<UserRolesRecord> KEY_RFRMGR_USER_ROLES_ID_UNIQUE = createUniqueKey(UserRoles.RFRMGR_USER_ROLES, "KEY_rfrmgr_user_roles_id_UNIQUE", UserRoles.RFRMGR_USER_ROLES.ID);
        public static final UniqueKey<UserRolesRecord> KEY_RFRMGR_USER_ROLES_SID_UNIQUE = createUniqueKey(UserRoles.RFRMGR_USER_ROLES, "KEY_rfrmgr_user_roles_sid_UNIQUE", UserRoles.RFRMGR_USER_ROLES.SID);
        public static final UniqueKey<WishesRecord> KEY_RFRMGR_WISHES_PRIMARY = createUniqueKey(Wishes.RFRMGR_WISHES, "KEY_rfrmgr_wishes_PRIMARY", Wishes.RFRMGR_WISHES.ID);
        public static final UniqueKey<WishesRecord> KEY_RFRMGR_WISHES_ID_UNIQUE = createUniqueKey(Wishes.RFRMGR_WISHES, "KEY_rfrmgr_wishes_id_UNIQUE", Wishes.RFRMGR_WISHES.ID);
        public static final UniqueKey<WishTypesRecord> KEY_RFRMGR_WISH_TYPES_PRIMARY = createUniqueKey(WishTypes.RFRMGR_WISH_TYPES, "KEY_rfrmgr_wish_types_PRIMARY", WishTypes.RFRMGR_WISH_TYPES.ID);
        public static final UniqueKey<WishTypesRecord> KEY_RFRMGR_WISH_TYPES_ID_UNIQUE = createUniqueKey(WishTypes.RFRMGR_WISH_TYPES, "KEY_rfrmgr_wish_types_id_UNIQUE", WishTypes.RFRMGR_WISH_TYPES.ID);
        public static final UniqueKey<WishTypesRecord> KEY_RFRMGR_WISH_TYPES_SID_UNIQUE = createUniqueKey(WishTypes.RFRMGR_WISH_TYPES, "KEY_rfrmgr_wish_types_sid_UNIQUE", WishTypes.RFRMGR_WISH_TYPES.SID);
        public static final UniqueKey<WishTypesRecord> KEY_RFRMGR_WISH_TYPES_TITLE_UNIQUE = createUniqueKey(WishTypes.RFRMGR_WISH_TYPES, "KEY_rfrmgr_wish_types_title_UNIQUE", WishTypes.RFRMGR_WISH_TYPES.TITLE);
    }
}
