/**
 * This class is generated by jOOQ
 */
package de.edgesoft.refereemanager.jooq;


import de.edgesoft.refereemanager.jooq.tables.RfrmgrActivityLogs;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrAddresses;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrAssignments;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrClubs;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrContactTypes;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrContacts;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrDatabaseColumns;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrDatabaseTables;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrEmails;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrLeagueGameTeamTypes;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrLeagueGameTeams;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrLeagueGames;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrLeaguePlannedReferees;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrLeagueTypes;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrLeagues;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrPeople;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrPersonPreferences;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrPhoneNumbers;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrPictures;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrRefereeAssignmentRemarkTypes;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrRefereeAssignmentStatusTypes;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrRefereeAssignmentTypes;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrRefereeAssignments;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrRefereeRelationTypes;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrRefereeRelations;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrRefereeReportRecipients;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrRefereeReports;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrRefereeStatuses;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrReferees;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrSeasons;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrSexTypes;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrSpokespeople;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrStatusTypes;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrTeamSeasons;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrTeamVenues;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrTeams;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrTournamentGames;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrTournamentVenues;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrTournaments;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrTrainingLevelTypes;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrTrainingLevels;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrTrainingUpdates;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrUrls;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrUserRoles;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrUsers;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrWishTypes;
import de.edgesoft.refereemanager.jooq.tables.RfrmgrWishes;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrActivityLogsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrAddressesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrAssignmentsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrClubsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrContactTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrContactsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrDatabaseColumnsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrDatabaseTablesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrEmailsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrLeagueGameTeamTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrLeagueGameTeamsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrLeagueGamesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrLeaguePlannedRefereesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrLeagueTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrLeaguesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrPeopleRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrPersonPreferencesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrPhoneNumbersRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrPicturesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrRefereeAssignmentRemarkTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrRefereeAssignmentStatusTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrRefereeAssignmentTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrRefereeAssignmentsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrRefereeRelationTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrRefereeRelationsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrRefereeReportRecipientsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrRefereeReportsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrRefereeStatusesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrRefereesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrSeasonsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrSexTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrSpokespeopleRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrStatusTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrTeamSeasonsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrTeamVenuesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrTeamsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrTournamentGamesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrTournamentVenuesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrTournamentsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrTrainingLevelTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrTrainingLevelsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrTrainingUpdatesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrUrlsRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrUserRolesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrUsersRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrWishTypesRecord;
import de.edgesoft.refereemanager.jooq.tables.records.RfrmgrWishesRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships between tables of the <code>refereemanager</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RfrmgrActivityLogsRecord, UInteger> IDENTITY_RFRMGR_ACTIVITY_LOGS = Identities0.IDENTITY_RFRMGR_ACTIVITY_LOGS;
    public static final Identity<RfrmgrAddressesRecord, UInteger> IDENTITY_RFRMGR_ADDRESSES = Identities0.IDENTITY_RFRMGR_ADDRESSES;
    public static final Identity<RfrmgrAssignmentsRecord, UInteger> IDENTITY_RFRMGR_ASSIGNMENTS = Identities0.IDENTITY_RFRMGR_ASSIGNMENTS;
    public static final Identity<RfrmgrClubsRecord, UInteger> IDENTITY_RFRMGR_CLUBS = Identities0.IDENTITY_RFRMGR_CLUBS;
    public static final Identity<RfrmgrContactsRecord, UInteger> IDENTITY_RFRMGR_CONTACTS = Identities0.IDENTITY_RFRMGR_CONTACTS;
    public static final Identity<RfrmgrContactTypesRecord, UInteger> IDENTITY_RFRMGR_CONTACT_TYPES = Identities0.IDENTITY_RFRMGR_CONTACT_TYPES;
    public static final Identity<RfrmgrDatabaseColumnsRecord, UInteger> IDENTITY_RFRMGR_DATABASE_COLUMNS = Identities0.IDENTITY_RFRMGR_DATABASE_COLUMNS;
    public static final Identity<RfrmgrDatabaseTablesRecord, UInteger> IDENTITY_RFRMGR_DATABASE_TABLES = Identities0.IDENTITY_RFRMGR_DATABASE_TABLES;
    public static final Identity<RfrmgrEmailsRecord, UInteger> IDENTITY_RFRMGR_EMAILS = Identities0.IDENTITY_RFRMGR_EMAILS;
    public static final Identity<RfrmgrLeaguesRecord, UInteger> IDENTITY_RFRMGR_LEAGUES = Identities0.IDENTITY_RFRMGR_LEAGUES;
    public static final Identity<RfrmgrLeagueGamesRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_GAMES = Identities0.IDENTITY_RFRMGR_LEAGUE_GAMES;
    public static final Identity<RfrmgrLeagueGameTeamsRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_GAME_TEAMS = Identities0.IDENTITY_RFRMGR_LEAGUE_GAME_TEAMS;
    public static final Identity<RfrmgrLeagueGameTeamTypesRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_GAME_TEAM_TYPES = Identities0.IDENTITY_RFRMGR_LEAGUE_GAME_TEAM_TYPES;
    public static final Identity<RfrmgrLeaguePlannedRefereesRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_PLANNED_REFEREES = Identities0.IDENTITY_RFRMGR_LEAGUE_PLANNED_REFEREES;
    public static final Identity<RfrmgrLeagueTypesRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_TYPES = Identities0.IDENTITY_RFRMGR_LEAGUE_TYPES;
    public static final Identity<RfrmgrPeopleRecord, UInteger> IDENTITY_RFRMGR_PEOPLE = Identities0.IDENTITY_RFRMGR_PEOPLE;
    public static final Identity<RfrmgrPersonPreferencesRecord, UInteger> IDENTITY_RFRMGR_PERSON_PREFERENCES = Identities0.IDENTITY_RFRMGR_PERSON_PREFERENCES;
    public static final Identity<RfrmgrPhoneNumbersRecord, UInteger> IDENTITY_RFRMGR_PHONE_NUMBERS = Identities0.IDENTITY_RFRMGR_PHONE_NUMBERS;
    public static final Identity<RfrmgrPicturesRecord, UInteger> IDENTITY_RFRMGR_PICTURES = Identities0.IDENTITY_RFRMGR_PICTURES;
    public static final Identity<RfrmgrRefereesRecord, UInteger> IDENTITY_RFRMGR_REFEREES = Identities0.IDENTITY_RFRMGR_REFEREES;
    public static final Identity<RfrmgrRefereeAssignmentsRecord, UInteger> IDENTITY_RFRMGR_REFEREE_ASSIGNMENTS = Identities0.IDENTITY_RFRMGR_REFEREE_ASSIGNMENTS;
    public static final Identity<RfrmgrRefereeAssignmentRemarkTypesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES = Identities0.IDENTITY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES;
    public static final Identity<RfrmgrRefereeAssignmentStatusTypesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES = Identities0.IDENTITY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES;
    public static final Identity<RfrmgrRefereeAssignmentTypesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_ASSIGNMENT_TYPES = Identities0.IDENTITY_RFRMGR_REFEREE_ASSIGNMENT_TYPES;
    public static final Identity<RfrmgrRefereeRelationsRecord, UInteger> IDENTITY_RFRMGR_REFEREE_RELATIONS = Identities0.IDENTITY_RFRMGR_REFEREE_RELATIONS;
    public static final Identity<RfrmgrRefereeRelationTypesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_RELATION_TYPES = Identities0.IDENTITY_RFRMGR_REFEREE_RELATION_TYPES;
    public static final Identity<RfrmgrRefereeReportsRecord, UInteger> IDENTITY_RFRMGR_REFEREE_REPORTS = Identities0.IDENTITY_RFRMGR_REFEREE_REPORTS;
    public static final Identity<RfrmgrRefereeReportRecipientsRecord, UInteger> IDENTITY_RFRMGR_REFEREE_REPORT_RECIPIENTS = Identities0.IDENTITY_RFRMGR_REFEREE_REPORT_RECIPIENTS;
    public static final Identity<RfrmgrRefereeStatusesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_STATUSES = Identities0.IDENTITY_RFRMGR_REFEREE_STATUSES;
    public static final Identity<RfrmgrSeasonsRecord, UInteger> IDENTITY_RFRMGR_SEASONS = Identities0.IDENTITY_RFRMGR_SEASONS;
    public static final Identity<RfrmgrSexTypesRecord, UInteger> IDENTITY_RFRMGR_SEX_TYPES = Identities0.IDENTITY_RFRMGR_SEX_TYPES;
    public static final Identity<RfrmgrSpokespeopleRecord, UInteger> IDENTITY_RFRMGR_SPOKESPEOPLE = Identities0.IDENTITY_RFRMGR_SPOKESPEOPLE;
    public static final Identity<RfrmgrStatusTypesRecord, UInteger> IDENTITY_RFRMGR_STATUS_TYPES = Identities0.IDENTITY_RFRMGR_STATUS_TYPES;
    public static final Identity<RfrmgrTeamsRecord, UInteger> IDENTITY_RFRMGR_TEAMS = Identities0.IDENTITY_RFRMGR_TEAMS;
    public static final Identity<RfrmgrTeamSeasonsRecord, UInteger> IDENTITY_RFRMGR_TEAM_SEASONS = Identities0.IDENTITY_RFRMGR_TEAM_SEASONS;
    public static final Identity<RfrmgrTeamVenuesRecord, UInteger> IDENTITY_RFRMGR_TEAM_VENUES = Identities0.IDENTITY_RFRMGR_TEAM_VENUES;
    public static final Identity<RfrmgrTournamentsRecord, UInteger> IDENTITY_RFRMGR_TOURNAMENTS = Identities0.IDENTITY_RFRMGR_TOURNAMENTS;
    public static final Identity<RfrmgrTournamentGamesRecord, UInteger> IDENTITY_RFRMGR_TOURNAMENT_GAMES = Identities0.IDENTITY_RFRMGR_TOURNAMENT_GAMES;
    public static final Identity<RfrmgrTournamentVenuesRecord, UInteger> IDENTITY_RFRMGR_TOURNAMENT_VENUES = Identities0.IDENTITY_RFRMGR_TOURNAMENT_VENUES;
    public static final Identity<RfrmgrTrainingLevelsRecord, UInteger> IDENTITY_RFRMGR_TRAINING_LEVELS = Identities0.IDENTITY_RFRMGR_TRAINING_LEVELS;
    public static final Identity<RfrmgrTrainingLevelTypesRecord, UInteger> IDENTITY_RFRMGR_TRAINING_LEVEL_TYPES = Identities0.IDENTITY_RFRMGR_TRAINING_LEVEL_TYPES;
    public static final Identity<RfrmgrTrainingUpdatesRecord, UInteger> IDENTITY_RFRMGR_TRAINING_UPDATES = Identities0.IDENTITY_RFRMGR_TRAINING_UPDATES;
    public static final Identity<RfrmgrUrlsRecord, UInteger> IDENTITY_RFRMGR_URLS = Identities0.IDENTITY_RFRMGR_URLS;
    public static final Identity<RfrmgrUsersRecord, UInteger> IDENTITY_RFRMGR_USERS = Identities0.IDENTITY_RFRMGR_USERS;
    public static final Identity<RfrmgrUserRolesRecord, UInteger> IDENTITY_RFRMGR_USER_ROLES = Identities0.IDENTITY_RFRMGR_USER_ROLES;
    public static final Identity<RfrmgrWishesRecord, UInteger> IDENTITY_RFRMGR_WISHES = Identities0.IDENTITY_RFRMGR_WISHES;
    public static final Identity<RfrmgrWishTypesRecord, UInteger> IDENTITY_RFRMGR_WISH_TYPES = Identities0.IDENTITY_RFRMGR_WISH_TYPES;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RfrmgrActivityLogsRecord> KEY_RFRMGR_ACTIVITY_LOGS_PRIMARY = UniqueKeys0.KEY_RFRMGR_ACTIVITY_LOGS_PRIMARY;
    public static final UniqueKey<RfrmgrActivityLogsRecord> KEY_RFRMGR_ACTIVITY_LOGS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_ACTIVITY_LOGS_ID_UNIQUE;
    public static final UniqueKey<RfrmgrAddressesRecord> KEY_RFRMGR_ADDRESSES_PRIMARY = UniqueKeys0.KEY_RFRMGR_ADDRESSES_PRIMARY;
    public static final UniqueKey<RfrmgrAddressesRecord> KEY_RFRMGR_ADDRESSES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_ADDRESSES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrAssignmentsRecord> KEY_RFRMGR_ASSIGNMENTS_PRIMARY = UniqueKeys0.KEY_RFRMGR_ASSIGNMENTS_PRIMARY;
    public static final UniqueKey<RfrmgrAssignmentsRecord> KEY_RFRMGR_ASSIGNMENTS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_ASSIGNMENTS_ID_UNIQUE;
    public static final UniqueKey<RfrmgrClubsRecord> KEY_RFRMGR_CLUBS_PRIMARY = UniqueKeys0.KEY_RFRMGR_CLUBS_PRIMARY;
    public static final UniqueKey<RfrmgrClubsRecord> KEY_RFRMGR_CLUBS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_CLUBS_ID_UNIQUE;
    public static final UniqueKey<RfrmgrContactsRecord> KEY_RFRMGR_CONTACTS_PRIMARY = UniqueKeys0.KEY_RFRMGR_CONTACTS_PRIMARY;
    public static final UniqueKey<RfrmgrContactsRecord> KEY_RFRMGR_CONTACTS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_CONTACTS_ID_UNIQUE;
    public static final UniqueKey<RfrmgrContactTypesRecord> KEY_RFRMGR_CONTACT_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_CONTACT_TYPES_PRIMARY;
    public static final UniqueKey<RfrmgrContactTypesRecord> KEY_RFRMGR_CONTACT_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_CONTACT_TYPES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrContactTypesRecord> KEY_RFRMGR_CONTACT_TYPES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_CONTACT_TYPES_SID_UNIQUE;
    public static final UniqueKey<RfrmgrDatabaseColumnsRecord> KEY_RFRMGR_DATABASE_COLUMNS_PRIMARY = UniqueKeys0.KEY_RFRMGR_DATABASE_COLUMNS_PRIMARY;
    public static final UniqueKey<RfrmgrDatabaseColumnsRecord> KEY_RFRMGR_DATABASE_COLUMNS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_DATABASE_COLUMNS_ID_UNIQUE;
    public static final UniqueKey<RfrmgrDatabaseColumnsRecord> KEY_RFRMGR_DATABASE_COLUMNS_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_DATABASE_COLUMNS_SID_UNIQUE;
    public static final UniqueKey<RfrmgrDatabaseTablesRecord> KEY_RFRMGR_DATABASE_TABLES_PRIMARY = UniqueKeys0.KEY_RFRMGR_DATABASE_TABLES_PRIMARY;
    public static final UniqueKey<RfrmgrDatabaseTablesRecord> KEY_RFRMGR_DATABASE_TABLES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_DATABASE_TABLES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrDatabaseTablesRecord> KEY_RFRMGR_DATABASE_TABLES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_DATABASE_TABLES_SID_UNIQUE;
    public static final UniqueKey<RfrmgrEmailsRecord> KEY_RFRMGR_EMAILS_PRIMARY = UniqueKeys0.KEY_RFRMGR_EMAILS_PRIMARY;
    public static final UniqueKey<RfrmgrEmailsRecord> KEY_RFRMGR_EMAILS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_EMAILS_ID_UNIQUE;
    public static final UniqueKey<RfrmgrLeaguesRecord> KEY_RFRMGR_LEAGUES_PRIMARY = UniqueKeys0.KEY_RFRMGR_LEAGUES_PRIMARY;
    public static final UniqueKey<RfrmgrLeaguesRecord> KEY_RFRMGR_LEAGUES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrLeagueGamesRecord> KEY_RFRMGR_LEAGUE_GAMES_PRIMARY = UniqueKeys0.KEY_RFRMGR_LEAGUE_GAMES_PRIMARY;
    public static final UniqueKey<RfrmgrLeagueGamesRecord> KEY_RFRMGR_LEAGUE_GAMES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUE_GAMES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrLeagueGameTeamsRecord> KEY_RFRMGR_LEAGUE_GAME_TEAMS_PRIMARY = UniqueKeys0.KEY_RFRMGR_LEAGUE_GAME_TEAMS_PRIMARY;
    public static final UniqueKey<RfrmgrLeagueGameTeamsRecord> KEY_RFRMGR_LEAGUE_GAME_TEAMS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUE_GAME_TEAMS_ID_UNIQUE;
    public static final UniqueKey<RfrmgrLeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_PRIMARY;
    public static final UniqueKey<RfrmgrLeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrLeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_SID_UNIQUE;
    public static final UniqueKey<RfrmgrLeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_TITLE_UNIQUE;
    public static final UniqueKey<RfrmgrLeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_ABBREVIATION_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_ABBREVIATION_UNIQUE;
    public static final UniqueKey<RfrmgrLeaguePlannedRefereesRecord> KEY_RFRMGR_LEAGUE_PLANNED_REFEREES_PRIMARY = UniqueKeys0.KEY_RFRMGR_LEAGUE_PLANNED_REFEREES_PRIMARY;
    public static final UniqueKey<RfrmgrLeaguePlannedRefereesRecord> KEY_RFRMGR_LEAGUE_PLANNED_REFEREES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUE_PLANNED_REFEREES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrLeagueTypesRecord> KEY_RFRMGR_LEAGUE_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_LEAGUE_TYPES_PRIMARY;
    public static final UniqueKey<RfrmgrLeagueTypesRecord> KEY_RFRMGR_LEAGUE_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUE_TYPES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrLeagueTypesRecord> KEY_RFRMGR_LEAGUE_TYPES_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_LEAGUE_TYPES_TITLE_UNIQUE;
    public static final UniqueKey<RfrmgrPeopleRecord> KEY_RFRMGR_PEOPLE_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_PEOPLE_ID_UNIQUE;
    public static final UniqueKey<RfrmgrPersonPreferencesRecord> KEY_RFRMGR_PERSON_PREFERENCES_PRIMARY = UniqueKeys0.KEY_RFRMGR_PERSON_PREFERENCES_PRIMARY;
    public static final UniqueKey<RfrmgrPersonPreferencesRecord> KEY_RFRMGR_PERSON_PREFERENCES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_PERSON_PREFERENCES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrPersonPreferencesRecord> KEY_RFRMGR_PERSON_PREFERENCES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_PERSON_PREFERENCES_SID_UNIQUE;
    public static final UniqueKey<RfrmgrPhoneNumbersRecord> KEY_RFRMGR_PHONE_NUMBERS_PRIMARY = UniqueKeys0.KEY_RFRMGR_PHONE_NUMBERS_PRIMARY;
    public static final UniqueKey<RfrmgrPhoneNumbersRecord> KEY_RFRMGR_PHONE_NUMBERS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_PHONE_NUMBERS_ID_UNIQUE;
    public static final UniqueKey<RfrmgrPicturesRecord> KEY_RFRMGR_PICTURES_PRIMARY = UniqueKeys0.KEY_RFRMGR_PICTURES_PRIMARY;
    public static final UniqueKey<RfrmgrPicturesRecord> KEY_RFRMGR_PICTURES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_PICTURES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrRefereesRecord> KEY_RFRMGR_REFEREES_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREES_PRIMARY;
    public static final UniqueKey<RfrmgrRefereesRecord> KEY_RFRMGR_REFEREES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrRefereeAssignmentsRecord> KEY_RFRMGR_REFEREE_ASSIGNMENTS_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENTS_PRIMARY;
    public static final UniqueKey<RfrmgrRefereeAssignmentsRecord> KEY_RFRMGR_REFEREE_ASSIGNMENTS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENTS_ID_UNIQUE;
    public static final UniqueKey<RfrmgrRefereeAssignmentRemarkTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES_PRIMARY;
    public static final UniqueKey<RfrmgrRefereeAssignmentRemarkTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrRefereeAssignmentRemarkTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES_TITLE_UNIQUE;
    public static final UniqueKey<RfrmgrRefereeAssignmentStatusTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES_PRIMARY;
    public static final UniqueKey<RfrmgrRefereeAssignmentStatusTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrRefereeAssignmentStatusTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES_TITLE_UNIQUE;
    public static final UniqueKey<RfrmgrRefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_PRIMARY;
    public static final UniqueKey<RfrmgrRefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrRefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_SID_UNIQUE;
    public static final UniqueKey<RfrmgrRefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_TITLE_UNIQUE;
    public static final UniqueKey<RfrmgrRefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_ABBREVIATION_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_ABBREVIATION_UNIQUE;
    public static final UniqueKey<RfrmgrRefereeRelationsRecord> KEY_RFRMGR_REFEREE_RELATIONS_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREE_RELATIONS_PRIMARY;
    public static final UniqueKey<RfrmgrRefereeRelationsRecord> KEY_RFRMGR_REFEREE_RELATIONS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_RELATIONS_ID_UNIQUE;
    public static final UniqueKey<RfrmgrRefereeRelationTypesRecord> KEY_RFRMGR_REFEREE_RELATION_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREE_RELATION_TYPES_PRIMARY;
    public static final UniqueKey<RfrmgrRefereeRelationTypesRecord> KEY_RFRMGR_REFEREE_RELATION_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_RELATION_TYPES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrRefereeRelationTypesRecord> KEY_RFRMGR_REFEREE_RELATION_TYPES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_RELATION_TYPES_SID_UNIQUE;
    public static final UniqueKey<RfrmgrRefereeRelationTypesRecord> KEY_RFRMGR_REFEREE_RELATION_TYPES_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_RELATION_TYPES_TITLE_UNIQUE;
    public static final UniqueKey<RfrmgrRefereeReportsRecord> KEY_RFRMGR_REFEREE_REPORTS_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREE_REPORTS_PRIMARY;
    public static final UniqueKey<RfrmgrRefereeReportsRecord> KEY_RFRMGR_REFEREE_REPORTS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_REPORTS_ID_UNIQUE;
    public static final UniqueKey<RfrmgrRefereeReportRecipientsRecord> KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_PRIMARY;
    public static final UniqueKey<RfrmgrRefereeReportRecipientsRecord> KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_ID_UNIQUE;
    public static final UniqueKey<RfrmgrRefereeReportRecipientsRecord> KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_TITLE_UNIQUE;
    public static final UniqueKey<RfrmgrRefereeReportRecipientsRecord> KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_PERSON_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_PERSON_ID_UNIQUE;
    public static final UniqueKey<RfrmgrRefereeStatusesRecord> KEY_RFRMGR_REFEREE_STATUSES_PRIMARY = UniqueKeys0.KEY_RFRMGR_REFEREE_STATUSES_PRIMARY;
    public static final UniqueKey<RfrmgrRefereeStatusesRecord> KEY_RFRMGR_REFEREE_STATUSES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_REFEREE_STATUSES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrSeasonsRecord> KEY_RFRMGR_SEASONS_PRIMARY = UniqueKeys0.KEY_RFRMGR_SEASONS_PRIMARY;
    public static final UniqueKey<RfrmgrSeasonsRecord> KEY_RFRMGR_SEASONS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_SEASONS_ID_UNIQUE;
    public static final UniqueKey<RfrmgrSeasonsRecord> KEY_RFRMGR_SEASONS_YEAR_START_UNIQUE = UniqueKeys0.KEY_RFRMGR_SEASONS_YEAR_START_UNIQUE;
    public static final UniqueKey<RfrmgrSexTypesRecord> KEY_RFRMGR_SEX_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_SEX_TYPES_PRIMARY;
    public static final UniqueKey<RfrmgrSexTypesRecord> KEY_RFRMGR_SEX_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_SEX_TYPES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrSexTypesRecord> KEY_RFRMGR_SEX_TYPES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_SEX_TYPES_SID_UNIQUE;
    public static final UniqueKey<RfrmgrSpokespeopleRecord> KEY_RFRMGR_SPOKESPEOPLE_PRIMARY = UniqueKeys0.KEY_RFRMGR_SPOKESPEOPLE_PRIMARY;
    public static final UniqueKey<RfrmgrSpokespeopleRecord> KEY_RFRMGR_SPOKESPEOPLE_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_SPOKESPEOPLE_ID_UNIQUE;
    public static final UniqueKey<RfrmgrStatusTypesRecord> KEY_RFRMGR_STATUS_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_STATUS_TYPES_PRIMARY;
    public static final UniqueKey<RfrmgrStatusTypesRecord> KEY_RFRMGR_STATUS_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_STATUS_TYPES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrStatusTypesRecord> KEY_RFRMGR_STATUS_TYPES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_STATUS_TYPES_SID_UNIQUE;
    public static final UniqueKey<RfrmgrStatusTypesRecord> KEY_RFRMGR_STATUS_TYPES_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_STATUS_TYPES_TITLE_UNIQUE;
    public static final UniqueKey<RfrmgrTeamsRecord> KEY_RFRMGR_TEAMS_PRIMARY = UniqueKeys0.KEY_RFRMGR_TEAMS_PRIMARY;
    public static final UniqueKey<RfrmgrTeamsRecord> KEY_RFRMGR_TEAMS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TEAMS_ID_UNIQUE;
    public static final UniqueKey<RfrmgrTeamSeasonsRecord> KEY_RFRMGR_TEAM_SEASONS_PRIMARY = UniqueKeys0.KEY_RFRMGR_TEAM_SEASONS_PRIMARY;
    public static final UniqueKey<RfrmgrTeamSeasonsRecord> KEY_RFRMGR_TEAM_SEASONS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TEAM_SEASONS_ID_UNIQUE;
    public static final UniqueKey<RfrmgrTeamVenuesRecord> KEY_RFRMGR_TEAM_VENUES_PRIMARY = UniqueKeys0.KEY_RFRMGR_TEAM_VENUES_PRIMARY;
    public static final UniqueKey<RfrmgrTeamVenuesRecord> KEY_RFRMGR_TEAM_VENUES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TEAM_VENUES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrTournamentsRecord> KEY_RFRMGR_TOURNAMENTS_PRIMARY = UniqueKeys0.KEY_RFRMGR_TOURNAMENTS_PRIMARY;
    public static final UniqueKey<RfrmgrTournamentsRecord> KEY_RFRMGR_TOURNAMENTS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TOURNAMENTS_ID_UNIQUE;
    public static final UniqueKey<RfrmgrTournamentsRecord> KEY_RFRMGR_TOURNAMENTS_ABBREVIATION_UNIQUE = UniqueKeys0.KEY_RFRMGR_TOURNAMENTS_ABBREVIATION_UNIQUE;
    public static final UniqueKey<RfrmgrTournamentGamesRecord> KEY_RFRMGR_TOURNAMENT_GAMES_PRIMARY = UniqueKeys0.KEY_RFRMGR_TOURNAMENT_GAMES_PRIMARY;
    public static final UniqueKey<RfrmgrTournamentGamesRecord> KEY_RFRMGR_TOURNAMENT_GAMES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TOURNAMENT_GAMES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrTournamentVenuesRecord> KEY_RFRMGR_TOURNAMENT_VENUES_PRIMARY = UniqueKeys0.KEY_RFRMGR_TOURNAMENT_VENUES_PRIMARY;
    public static final UniqueKey<RfrmgrTournamentVenuesRecord> KEY_RFRMGR_TOURNAMENT_VENUES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TOURNAMENT_VENUES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrTrainingLevelsRecord> KEY_RFRMGR_TRAINING_LEVELS_PRIMARY = UniqueKeys0.KEY_RFRMGR_TRAINING_LEVELS_PRIMARY;
    public static final UniqueKey<RfrmgrTrainingLevelsRecord> KEY_RFRMGR_TRAINING_LEVELS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TRAINING_LEVELS_ID_UNIQUE;
    public static final UniqueKey<RfrmgrTrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_TRAINING_LEVEL_TYPES_PRIMARY;
    public static final UniqueKey<RfrmgrTrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TRAINING_LEVEL_TYPES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrTrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TRAINING_LEVEL_TYPES_SID_UNIQUE;
    public static final UniqueKey<RfrmgrTrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_RANK_UNIQUE = UniqueKeys0.KEY_RFRMGR_TRAINING_LEVEL_TYPES_RANK_UNIQUE;
    public static final UniqueKey<RfrmgrTrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_TRAINING_LEVEL_TYPES_TITLE_UNIQUE;
    public static final UniqueKey<RfrmgrTrainingUpdatesRecord> KEY_RFRMGR_TRAINING_UPDATES_PRIMARY = UniqueKeys0.KEY_RFRMGR_TRAINING_UPDATES_PRIMARY;
    public static final UniqueKey<RfrmgrTrainingUpdatesRecord> KEY_RFRMGR_TRAINING_UPDATES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_TRAINING_UPDATES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrUrlsRecord> KEY_RFRMGR_URLS_PRIMARY = UniqueKeys0.KEY_RFRMGR_URLS_PRIMARY;
    public static final UniqueKey<RfrmgrUrlsRecord> KEY_RFRMGR_URLS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_URLS_ID_UNIQUE;
    public static final UniqueKey<RfrmgrUsersRecord> KEY_RFRMGR_USERS_PRIMARY = UniqueKeys0.KEY_RFRMGR_USERS_PRIMARY;
    public static final UniqueKey<RfrmgrUsersRecord> KEY_RFRMGR_USERS_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_USERS_ID_UNIQUE;
    public static final UniqueKey<RfrmgrUsersRecord> KEY_RFRMGR_USERS_USERNAME_UNIQUE = UniqueKeys0.KEY_RFRMGR_USERS_USERNAME_UNIQUE;
    public static final UniqueKey<RfrmgrUserRolesRecord> KEY_RFRMGR_USER_ROLES_PRIMARY = UniqueKeys0.KEY_RFRMGR_USER_ROLES_PRIMARY;
    public static final UniqueKey<RfrmgrUserRolesRecord> KEY_RFRMGR_USER_ROLES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_USER_ROLES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrUserRolesRecord> KEY_RFRMGR_USER_ROLES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_USER_ROLES_SID_UNIQUE;
    public static final UniqueKey<RfrmgrWishesRecord> KEY_RFRMGR_WISHES_PRIMARY = UniqueKeys0.KEY_RFRMGR_WISHES_PRIMARY;
    public static final UniqueKey<RfrmgrWishesRecord> KEY_RFRMGR_WISHES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_WISHES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrWishTypesRecord> KEY_RFRMGR_WISH_TYPES_PRIMARY = UniqueKeys0.KEY_RFRMGR_WISH_TYPES_PRIMARY;
    public static final UniqueKey<RfrmgrWishTypesRecord> KEY_RFRMGR_WISH_TYPES_ID_UNIQUE = UniqueKeys0.KEY_RFRMGR_WISH_TYPES_ID_UNIQUE;
    public static final UniqueKey<RfrmgrWishTypesRecord> KEY_RFRMGR_WISH_TYPES_SID_UNIQUE = UniqueKeys0.KEY_RFRMGR_WISH_TYPES_SID_UNIQUE;
    public static final UniqueKey<RfrmgrWishTypesRecord> KEY_RFRMGR_WISH_TYPES_TITLE_UNIQUE = UniqueKeys0.KEY_RFRMGR_WISH_TYPES_TITLE_UNIQUE;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<RfrmgrActivityLogsRecord, UInteger> IDENTITY_RFRMGR_ACTIVITY_LOGS = createIdentity(RfrmgrActivityLogs.RFRMGR_ACTIVITY_LOGS, RfrmgrActivityLogs.RFRMGR_ACTIVITY_LOGS.ID);
        public static Identity<RfrmgrAddressesRecord, UInteger> IDENTITY_RFRMGR_ADDRESSES = createIdentity(RfrmgrAddresses.RFRMGR_ADDRESSES, RfrmgrAddresses.RFRMGR_ADDRESSES.ID);
        public static Identity<RfrmgrAssignmentsRecord, UInteger> IDENTITY_RFRMGR_ASSIGNMENTS = createIdentity(RfrmgrAssignments.RFRMGR_ASSIGNMENTS, RfrmgrAssignments.RFRMGR_ASSIGNMENTS.ID);
        public static Identity<RfrmgrClubsRecord, UInteger> IDENTITY_RFRMGR_CLUBS = createIdentity(RfrmgrClubs.RFRMGR_CLUBS, RfrmgrClubs.RFRMGR_CLUBS.ID);
        public static Identity<RfrmgrContactsRecord, UInteger> IDENTITY_RFRMGR_CONTACTS = createIdentity(RfrmgrContacts.RFRMGR_CONTACTS, RfrmgrContacts.RFRMGR_CONTACTS.ID);
        public static Identity<RfrmgrContactTypesRecord, UInteger> IDENTITY_RFRMGR_CONTACT_TYPES = createIdentity(RfrmgrContactTypes.RFRMGR_CONTACT_TYPES, RfrmgrContactTypes.RFRMGR_CONTACT_TYPES.ID);
        public static Identity<RfrmgrDatabaseColumnsRecord, UInteger> IDENTITY_RFRMGR_DATABASE_COLUMNS = createIdentity(RfrmgrDatabaseColumns.RFRMGR_DATABASE_COLUMNS, RfrmgrDatabaseColumns.RFRMGR_DATABASE_COLUMNS.ID);
        public static Identity<RfrmgrDatabaseTablesRecord, UInteger> IDENTITY_RFRMGR_DATABASE_TABLES = createIdentity(RfrmgrDatabaseTables.RFRMGR_DATABASE_TABLES, RfrmgrDatabaseTables.RFRMGR_DATABASE_TABLES.ID);
        public static Identity<RfrmgrEmailsRecord, UInteger> IDENTITY_RFRMGR_EMAILS = createIdentity(RfrmgrEmails.RFRMGR_EMAILS, RfrmgrEmails.RFRMGR_EMAILS.ID);
        public static Identity<RfrmgrLeaguesRecord, UInteger> IDENTITY_RFRMGR_LEAGUES = createIdentity(RfrmgrLeagues.RFRMGR_LEAGUES, RfrmgrLeagues.RFRMGR_LEAGUES.ID);
        public static Identity<RfrmgrLeagueGamesRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_GAMES = createIdentity(RfrmgrLeagueGames.RFRMGR_LEAGUE_GAMES, RfrmgrLeagueGames.RFRMGR_LEAGUE_GAMES.ID);
        public static Identity<RfrmgrLeagueGameTeamsRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_GAME_TEAMS = createIdentity(RfrmgrLeagueGameTeams.RFRMGR_LEAGUE_GAME_TEAMS, RfrmgrLeagueGameTeams.RFRMGR_LEAGUE_GAME_TEAMS.ID);
        public static Identity<RfrmgrLeagueGameTeamTypesRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_GAME_TEAM_TYPES = createIdentity(RfrmgrLeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES, RfrmgrLeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES.ID);
        public static Identity<RfrmgrLeaguePlannedRefereesRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_PLANNED_REFEREES = createIdentity(RfrmgrLeaguePlannedReferees.RFRMGR_LEAGUE_PLANNED_REFEREES, RfrmgrLeaguePlannedReferees.RFRMGR_LEAGUE_PLANNED_REFEREES.ID);
        public static Identity<RfrmgrLeagueTypesRecord, UInteger> IDENTITY_RFRMGR_LEAGUE_TYPES = createIdentity(RfrmgrLeagueTypes.RFRMGR_LEAGUE_TYPES, RfrmgrLeagueTypes.RFRMGR_LEAGUE_TYPES.ID);
        public static Identity<RfrmgrPeopleRecord, UInteger> IDENTITY_RFRMGR_PEOPLE = createIdentity(RfrmgrPeople.RFRMGR_PEOPLE, RfrmgrPeople.RFRMGR_PEOPLE.ID);
        public static Identity<RfrmgrPersonPreferencesRecord, UInteger> IDENTITY_RFRMGR_PERSON_PREFERENCES = createIdentity(RfrmgrPersonPreferences.RFRMGR_PERSON_PREFERENCES, RfrmgrPersonPreferences.RFRMGR_PERSON_PREFERENCES.ID);
        public static Identity<RfrmgrPhoneNumbersRecord, UInteger> IDENTITY_RFRMGR_PHONE_NUMBERS = createIdentity(RfrmgrPhoneNumbers.RFRMGR_PHONE_NUMBERS, RfrmgrPhoneNumbers.RFRMGR_PHONE_NUMBERS.ID);
        public static Identity<RfrmgrPicturesRecord, UInteger> IDENTITY_RFRMGR_PICTURES = createIdentity(RfrmgrPictures.RFRMGR_PICTURES, RfrmgrPictures.RFRMGR_PICTURES.ID);
        public static Identity<RfrmgrRefereesRecord, UInteger> IDENTITY_RFRMGR_REFEREES = createIdentity(RfrmgrReferees.RFRMGR_REFEREES, RfrmgrReferees.RFRMGR_REFEREES.ID);
        public static Identity<RfrmgrRefereeAssignmentsRecord, UInteger> IDENTITY_RFRMGR_REFEREE_ASSIGNMENTS = createIdentity(RfrmgrRefereeAssignments.RFRMGR_REFEREE_ASSIGNMENTS, RfrmgrRefereeAssignments.RFRMGR_REFEREE_ASSIGNMENTS.ID);
        public static Identity<RfrmgrRefereeAssignmentRemarkTypesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES = createIdentity(RfrmgrRefereeAssignmentRemarkTypes.RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES, RfrmgrRefereeAssignmentRemarkTypes.RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES.ID);
        public static Identity<RfrmgrRefereeAssignmentStatusTypesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES = createIdentity(RfrmgrRefereeAssignmentStatusTypes.RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES, RfrmgrRefereeAssignmentStatusTypes.RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES.ID);
        public static Identity<RfrmgrRefereeAssignmentTypesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_ASSIGNMENT_TYPES = createIdentity(RfrmgrRefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES, RfrmgrRefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES.ID);
        public static Identity<RfrmgrRefereeRelationsRecord, UInteger> IDENTITY_RFRMGR_REFEREE_RELATIONS = createIdentity(RfrmgrRefereeRelations.RFRMGR_REFEREE_RELATIONS, RfrmgrRefereeRelations.RFRMGR_REFEREE_RELATIONS.ID);
        public static Identity<RfrmgrRefereeRelationTypesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_RELATION_TYPES = createIdentity(RfrmgrRefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES, RfrmgrRefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES.ID);
        public static Identity<RfrmgrRefereeReportsRecord, UInteger> IDENTITY_RFRMGR_REFEREE_REPORTS = createIdentity(RfrmgrRefereeReports.RFRMGR_REFEREE_REPORTS, RfrmgrRefereeReports.RFRMGR_REFEREE_REPORTS.ID);
        public static Identity<RfrmgrRefereeReportRecipientsRecord, UInteger> IDENTITY_RFRMGR_REFEREE_REPORT_RECIPIENTS = createIdentity(RfrmgrRefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS, RfrmgrRefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS.ID);
        public static Identity<RfrmgrRefereeStatusesRecord, UInteger> IDENTITY_RFRMGR_REFEREE_STATUSES = createIdentity(RfrmgrRefereeStatuses.RFRMGR_REFEREE_STATUSES, RfrmgrRefereeStatuses.RFRMGR_REFEREE_STATUSES.ID);
        public static Identity<RfrmgrSeasonsRecord, UInteger> IDENTITY_RFRMGR_SEASONS = createIdentity(RfrmgrSeasons.RFRMGR_SEASONS, RfrmgrSeasons.RFRMGR_SEASONS.ID);
        public static Identity<RfrmgrSexTypesRecord, UInteger> IDENTITY_RFRMGR_SEX_TYPES = createIdentity(RfrmgrSexTypes.RFRMGR_SEX_TYPES, RfrmgrSexTypes.RFRMGR_SEX_TYPES.ID);
        public static Identity<RfrmgrSpokespeopleRecord, UInteger> IDENTITY_RFRMGR_SPOKESPEOPLE = createIdentity(RfrmgrSpokespeople.RFRMGR_SPOKESPEOPLE, RfrmgrSpokespeople.RFRMGR_SPOKESPEOPLE.ID);
        public static Identity<RfrmgrStatusTypesRecord, UInteger> IDENTITY_RFRMGR_STATUS_TYPES = createIdentity(RfrmgrStatusTypes.RFRMGR_STATUS_TYPES, RfrmgrStatusTypes.RFRMGR_STATUS_TYPES.ID);
        public static Identity<RfrmgrTeamsRecord, UInteger> IDENTITY_RFRMGR_TEAMS = createIdentity(RfrmgrTeams.RFRMGR_TEAMS, RfrmgrTeams.RFRMGR_TEAMS.ID);
        public static Identity<RfrmgrTeamSeasonsRecord, UInteger> IDENTITY_RFRMGR_TEAM_SEASONS = createIdentity(RfrmgrTeamSeasons.RFRMGR_TEAM_SEASONS, RfrmgrTeamSeasons.RFRMGR_TEAM_SEASONS.ID);
        public static Identity<RfrmgrTeamVenuesRecord, UInteger> IDENTITY_RFRMGR_TEAM_VENUES = createIdentity(RfrmgrTeamVenues.RFRMGR_TEAM_VENUES, RfrmgrTeamVenues.RFRMGR_TEAM_VENUES.ID);
        public static Identity<RfrmgrTournamentsRecord, UInteger> IDENTITY_RFRMGR_TOURNAMENTS = createIdentity(RfrmgrTournaments.RFRMGR_TOURNAMENTS, RfrmgrTournaments.RFRMGR_TOURNAMENTS.ID);
        public static Identity<RfrmgrTournamentGamesRecord, UInteger> IDENTITY_RFRMGR_TOURNAMENT_GAMES = createIdentity(RfrmgrTournamentGames.RFRMGR_TOURNAMENT_GAMES, RfrmgrTournamentGames.RFRMGR_TOURNAMENT_GAMES.ID);
        public static Identity<RfrmgrTournamentVenuesRecord, UInteger> IDENTITY_RFRMGR_TOURNAMENT_VENUES = createIdentity(RfrmgrTournamentVenues.RFRMGR_TOURNAMENT_VENUES, RfrmgrTournamentVenues.RFRMGR_TOURNAMENT_VENUES.ID);
        public static Identity<RfrmgrTrainingLevelsRecord, UInteger> IDENTITY_RFRMGR_TRAINING_LEVELS = createIdentity(RfrmgrTrainingLevels.RFRMGR_TRAINING_LEVELS, RfrmgrTrainingLevels.RFRMGR_TRAINING_LEVELS.ID);
        public static Identity<RfrmgrTrainingLevelTypesRecord, UInteger> IDENTITY_RFRMGR_TRAINING_LEVEL_TYPES = createIdentity(RfrmgrTrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES, RfrmgrTrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES.ID);
        public static Identity<RfrmgrTrainingUpdatesRecord, UInteger> IDENTITY_RFRMGR_TRAINING_UPDATES = createIdentity(RfrmgrTrainingUpdates.RFRMGR_TRAINING_UPDATES, RfrmgrTrainingUpdates.RFRMGR_TRAINING_UPDATES.ID);
        public static Identity<RfrmgrUrlsRecord, UInteger> IDENTITY_RFRMGR_URLS = createIdentity(RfrmgrUrls.RFRMGR_URLS, RfrmgrUrls.RFRMGR_URLS.ID);
        public static Identity<RfrmgrUsersRecord, UInteger> IDENTITY_RFRMGR_USERS = createIdentity(RfrmgrUsers.RFRMGR_USERS, RfrmgrUsers.RFRMGR_USERS.ID);
        public static Identity<RfrmgrUserRolesRecord, UInteger> IDENTITY_RFRMGR_USER_ROLES = createIdentity(RfrmgrUserRoles.RFRMGR_USER_ROLES, RfrmgrUserRoles.RFRMGR_USER_ROLES.ID);
        public static Identity<RfrmgrWishesRecord, UInteger> IDENTITY_RFRMGR_WISHES = createIdentity(RfrmgrWishes.RFRMGR_WISHES, RfrmgrWishes.RFRMGR_WISHES.ID);
        public static Identity<RfrmgrWishTypesRecord, UInteger> IDENTITY_RFRMGR_WISH_TYPES = createIdentity(RfrmgrWishTypes.RFRMGR_WISH_TYPES, RfrmgrWishTypes.RFRMGR_WISH_TYPES.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<RfrmgrActivityLogsRecord> KEY_RFRMGR_ACTIVITY_LOGS_PRIMARY = createUniqueKey(RfrmgrActivityLogs.RFRMGR_ACTIVITY_LOGS, "KEY_rfrmgr_activity_logs_PRIMARY", RfrmgrActivityLogs.RFRMGR_ACTIVITY_LOGS.ID);
        public static final UniqueKey<RfrmgrActivityLogsRecord> KEY_RFRMGR_ACTIVITY_LOGS_ID_UNIQUE = createUniqueKey(RfrmgrActivityLogs.RFRMGR_ACTIVITY_LOGS, "KEY_rfrmgr_activity_logs_id_UNIQUE", RfrmgrActivityLogs.RFRMGR_ACTIVITY_LOGS.ID);
        public static final UniqueKey<RfrmgrAddressesRecord> KEY_RFRMGR_ADDRESSES_PRIMARY = createUniqueKey(RfrmgrAddresses.RFRMGR_ADDRESSES, "KEY_rfrmgr_addresses_PRIMARY", RfrmgrAddresses.RFRMGR_ADDRESSES.ID);
        public static final UniqueKey<RfrmgrAddressesRecord> KEY_RFRMGR_ADDRESSES_ID_UNIQUE = createUniqueKey(RfrmgrAddresses.RFRMGR_ADDRESSES, "KEY_rfrmgr_addresses_id_UNIQUE", RfrmgrAddresses.RFRMGR_ADDRESSES.ID);
        public static final UniqueKey<RfrmgrAssignmentsRecord> KEY_RFRMGR_ASSIGNMENTS_PRIMARY = createUniqueKey(RfrmgrAssignments.RFRMGR_ASSIGNMENTS, "KEY_rfrmgr_assignments_PRIMARY", RfrmgrAssignments.RFRMGR_ASSIGNMENTS.ID);
        public static final UniqueKey<RfrmgrAssignmentsRecord> KEY_RFRMGR_ASSIGNMENTS_ID_UNIQUE = createUniqueKey(RfrmgrAssignments.RFRMGR_ASSIGNMENTS, "KEY_rfrmgr_assignments_id_UNIQUE", RfrmgrAssignments.RFRMGR_ASSIGNMENTS.ID);
        public static final UniqueKey<RfrmgrClubsRecord> KEY_RFRMGR_CLUBS_PRIMARY = createUniqueKey(RfrmgrClubs.RFRMGR_CLUBS, "KEY_rfrmgr_clubs_PRIMARY", RfrmgrClubs.RFRMGR_CLUBS.ID);
        public static final UniqueKey<RfrmgrClubsRecord> KEY_RFRMGR_CLUBS_ID_UNIQUE = createUniqueKey(RfrmgrClubs.RFRMGR_CLUBS, "KEY_rfrmgr_clubs_id_UNIQUE", RfrmgrClubs.RFRMGR_CLUBS.ID);
        public static final UniqueKey<RfrmgrContactsRecord> KEY_RFRMGR_CONTACTS_PRIMARY = createUniqueKey(RfrmgrContacts.RFRMGR_CONTACTS, "KEY_rfrmgr_contacts_PRIMARY", RfrmgrContacts.RFRMGR_CONTACTS.ID);
        public static final UniqueKey<RfrmgrContactsRecord> KEY_RFRMGR_CONTACTS_ID_UNIQUE = createUniqueKey(RfrmgrContacts.RFRMGR_CONTACTS, "KEY_rfrmgr_contacts_id_UNIQUE", RfrmgrContacts.RFRMGR_CONTACTS.ID);
        public static final UniqueKey<RfrmgrContactTypesRecord> KEY_RFRMGR_CONTACT_TYPES_PRIMARY = createUniqueKey(RfrmgrContactTypes.RFRMGR_CONTACT_TYPES, "KEY_rfrmgr_contact_types_PRIMARY", RfrmgrContactTypes.RFRMGR_CONTACT_TYPES.ID);
        public static final UniqueKey<RfrmgrContactTypesRecord> KEY_RFRMGR_CONTACT_TYPES_ID_UNIQUE = createUniqueKey(RfrmgrContactTypes.RFRMGR_CONTACT_TYPES, "KEY_rfrmgr_contact_types_id_UNIQUE", RfrmgrContactTypes.RFRMGR_CONTACT_TYPES.ID);
        public static final UniqueKey<RfrmgrContactTypesRecord> KEY_RFRMGR_CONTACT_TYPES_SID_UNIQUE = createUniqueKey(RfrmgrContactTypes.RFRMGR_CONTACT_TYPES, "KEY_rfrmgr_contact_types_sid_UNIQUE", RfrmgrContactTypes.RFRMGR_CONTACT_TYPES.TITLE);
        public static final UniqueKey<RfrmgrDatabaseColumnsRecord> KEY_RFRMGR_DATABASE_COLUMNS_PRIMARY = createUniqueKey(RfrmgrDatabaseColumns.RFRMGR_DATABASE_COLUMNS, "KEY_rfrmgr_database_columns_PRIMARY", RfrmgrDatabaseColumns.RFRMGR_DATABASE_COLUMNS.ID);
        public static final UniqueKey<RfrmgrDatabaseColumnsRecord> KEY_RFRMGR_DATABASE_COLUMNS_ID_UNIQUE = createUniqueKey(RfrmgrDatabaseColumns.RFRMGR_DATABASE_COLUMNS, "KEY_rfrmgr_database_columns_id_UNIQUE", RfrmgrDatabaseColumns.RFRMGR_DATABASE_COLUMNS.ID);
        public static final UniqueKey<RfrmgrDatabaseColumnsRecord> KEY_RFRMGR_DATABASE_COLUMNS_SID_UNIQUE = createUniqueKey(RfrmgrDatabaseColumns.RFRMGR_DATABASE_COLUMNS, "KEY_rfrmgr_database_columns_sid_UNIQUE", RfrmgrDatabaseColumns.RFRMGR_DATABASE_COLUMNS.COLUMN_NAME);
        public static final UniqueKey<RfrmgrDatabaseTablesRecord> KEY_RFRMGR_DATABASE_TABLES_PRIMARY = createUniqueKey(RfrmgrDatabaseTables.RFRMGR_DATABASE_TABLES, "KEY_rfrmgr_database_tables_PRIMARY", RfrmgrDatabaseTables.RFRMGR_DATABASE_TABLES.ID);
        public static final UniqueKey<RfrmgrDatabaseTablesRecord> KEY_RFRMGR_DATABASE_TABLES_ID_UNIQUE = createUniqueKey(RfrmgrDatabaseTables.RFRMGR_DATABASE_TABLES, "KEY_rfrmgr_database_tables_id_UNIQUE", RfrmgrDatabaseTables.RFRMGR_DATABASE_TABLES.ID);
        public static final UniqueKey<RfrmgrDatabaseTablesRecord> KEY_RFRMGR_DATABASE_TABLES_SID_UNIQUE = createUniqueKey(RfrmgrDatabaseTables.RFRMGR_DATABASE_TABLES, "KEY_rfrmgr_database_tables_sid_UNIQUE", RfrmgrDatabaseTables.RFRMGR_DATABASE_TABLES.TABLE_NAME);
        public static final UniqueKey<RfrmgrEmailsRecord> KEY_RFRMGR_EMAILS_PRIMARY = createUniqueKey(RfrmgrEmails.RFRMGR_EMAILS, "KEY_rfrmgr_emails_PRIMARY", RfrmgrEmails.RFRMGR_EMAILS.ID);
        public static final UniqueKey<RfrmgrEmailsRecord> KEY_RFRMGR_EMAILS_ID_UNIQUE = createUniqueKey(RfrmgrEmails.RFRMGR_EMAILS, "KEY_rfrmgr_emails_id_UNIQUE", RfrmgrEmails.RFRMGR_EMAILS.ID);
        public static final UniqueKey<RfrmgrLeaguesRecord> KEY_RFRMGR_LEAGUES_PRIMARY = createUniqueKey(RfrmgrLeagues.RFRMGR_LEAGUES, "KEY_rfrmgr_leagues_PRIMARY", RfrmgrLeagues.RFRMGR_LEAGUES.ID);
        public static final UniqueKey<RfrmgrLeaguesRecord> KEY_RFRMGR_LEAGUES_ID_UNIQUE = createUniqueKey(RfrmgrLeagues.RFRMGR_LEAGUES, "KEY_rfrmgr_leagues_id_UNIQUE", RfrmgrLeagues.RFRMGR_LEAGUES.ID);
        public static final UniqueKey<RfrmgrLeagueGamesRecord> KEY_RFRMGR_LEAGUE_GAMES_PRIMARY = createUniqueKey(RfrmgrLeagueGames.RFRMGR_LEAGUE_GAMES, "KEY_rfrmgr_league_games_PRIMARY", RfrmgrLeagueGames.RFRMGR_LEAGUE_GAMES.ID);
        public static final UniqueKey<RfrmgrLeagueGamesRecord> KEY_RFRMGR_LEAGUE_GAMES_ID_UNIQUE = createUniqueKey(RfrmgrLeagueGames.RFRMGR_LEAGUE_GAMES, "KEY_rfrmgr_league_games_id_UNIQUE", RfrmgrLeagueGames.RFRMGR_LEAGUE_GAMES.ID);
        public static final UniqueKey<RfrmgrLeagueGameTeamsRecord> KEY_RFRMGR_LEAGUE_GAME_TEAMS_PRIMARY = createUniqueKey(RfrmgrLeagueGameTeams.RFRMGR_LEAGUE_GAME_TEAMS, "KEY_rfrmgr_league_game_teams_PRIMARY", RfrmgrLeagueGameTeams.RFRMGR_LEAGUE_GAME_TEAMS.ID);
        public static final UniqueKey<RfrmgrLeagueGameTeamsRecord> KEY_RFRMGR_LEAGUE_GAME_TEAMS_ID_UNIQUE = createUniqueKey(RfrmgrLeagueGameTeams.RFRMGR_LEAGUE_GAME_TEAMS, "KEY_rfrmgr_league_game_teams_id_UNIQUE", RfrmgrLeagueGameTeams.RFRMGR_LEAGUE_GAME_TEAMS.ID);
        public static final UniqueKey<RfrmgrLeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_PRIMARY = createUniqueKey(RfrmgrLeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES, "KEY_rfrmgr_league_game_team_types_PRIMARY", RfrmgrLeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES.ID);
        public static final UniqueKey<RfrmgrLeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_ID_UNIQUE = createUniqueKey(RfrmgrLeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES, "KEY_rfrmgr_league_game_team_types_id_UNIQUE", RfrmgrLeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES.ID);
        public static final UniqueKey<RfrmgrLeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_SID_UNIQUE = createUniqueKey(RfrmgrLeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES, "KEY_rfrmgr_league_game_team_types_sid_UNIQUE", RfrmgrLeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES.SID);
        public static final UniqueKey<RfrmgrLeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_TITLE_UNIQUE = createUniqueKey(RfrmgrLeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES, "KEY_rfrmgr_league_game_team_types_title_UNIQUE", RfrmgrLeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES.TITLE);
        public static final UniqueKey<RfrmgrLeagueGameTeamTypesRecord> KEY_RFRMGR_LEAGUE_GAME_TEAM_TYPES_ABBREVIATION_UNIQUE = createUniqueKey(RfrmgrLeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES, "KEY_rfrmgr_league_game_team_types_abbreviation_UNIQUE", RfrmgrLeagueGameTeamTypes.RFRMGR_LEAGUE_GAME_TEAM_TYPES.ABBREVIATION);
        public static final UniqueKey<RfrmgrLeaguePlannedRefereesRecord> KEY_RFRMGR_LEAGUE_PLANNED_REFEREES_PRIMARY = createUniqueKey(RfrmgrLeaguePlannedReferees.RFRMGR_LEAGUE_PLANNED_REFEREES, "KEY_rfrmgr_league_planned_referees_PRIMARY", RfrmgrLeaguePlannedReferees.RFRMGR_LEAGUE_PLANNED_REFEREES.ID);
        public static final UniqueKey<RfrmgrLeaguePlannedRefereesRecord> KEY_RFRMGR_LEAGUE_PLANNED_REFEREES_ID_UNIQUE = createUniqueKey(RfrmgrLeaguePlannedReferees.RFRMGR_LEAGUE_PLANNED_REFEREES, "KEY_rfrmgr_league_planned_referees_id_UNIQUE", RfrmgrLeaguePlannedReferees.RFRMGR_LEAGUE_PLANNED_REFEREES.ID);
        public static final UniqueKey<RfrmgrLeagueTypesRecord> KEY_RFRMGR_LEAGUE_TYPES_PRIMARY = createUniqueKey(RfrmgrLeagueTypes.RFRMGR_LEAGUE_TYPES, "KEY_rfrmgr_league_types_PRIMARY", RfrmgrLeagueTypes.RFRMGR_LEAGUE_TYPES.ID);
        public static final UniqueKey<RfrmgrLeagueTypesRecord> KEY_RFRMGR_LEAGUE_TYPES_ID_UNIQUE = createUniqueKey(RfrmgrLeagueTypes.RFRMGR_LEAGUE_TYPES, "KEY_rfrmgr_league_types_id_UNIQUE", RfrmgrLeagueTypes.RFRMGR_LEAGUE_TYPES.ID);
        public static final UniqueKey<RfrmgrLeagueTypesRecord> KEY_RFRMGR_LEAGUE_TYPES_TITLE_UNIQUE = createUniqueKey(RfrmgrLeagueTypes.RFRMGR_LEAGUE_TYPES, "KEY_rfrmgr_league_types_title_UNIQUE", RfrmgrLeagueTypes.RFRMGR_LEAGUE_TYPES.TITLE);
        public static final UniqueKey<RfrmgrPeopleRecord> KEY_RFRMGR_PEOPLE_ID_UNIQUE = createUniqueKey(RfrmgrPeople.RFRMGR_PEOPLE, "KEY_rfrmgr_people_id_UNIQUE", RfrmgrPeople.RFRMGR_PEOPLE.ID);
        public static final UniqueKey<RfrmgrPersonPreferencesRecord> KEY_RFRMGR_PERSON_PREFERENCES_PRIMARY = createUniqueKey(RfrmgrPersonPreferences.RFRMGR_PERSON_PREFERENCES, "KEY_rfrmgr_person_preferences_PRIMARY", RfrmgrPersonPreferences.RFRMGR_PERSON_PREFERENCES.ID);
        public static final UniqueKey<RfrmgrPersonPreferencesRecord> KEY_RFRMGR_PERSON_PREFERENCES_ID_UNIQUE = createUniqueKey(RfrmgrPersonPreferences.RFRMGR_PERSON_PREFERENCES, "KEY_rfrmgr_person_preferences_id_UNIQUE", RfrmgrPersonPreferences.RFRMGR_PERSON_PREFERENCES.ID);
        public static final UniqueKey<RfrmgrPersonPreferencesRecord> KEY_RFRMGR_PERSON_PREFERENCES_SID_UNIQUE = createUniqueKey(RfrmgrPersonPreferences.RFRMGR_PERSON_PREFERENCES, "KEY_rfrmgr_person_preferences_sid_UNIQUE", RfrmgrPersonPreferences.RFRMGR_PERSON_PREFERENCES.PERSON_ID);
        public static final UniqueKey<RfrmgrPhoneNumbersRecord> KEY_RFRMGR_PHONE_NUMBERS_PRIMARY = createUniqueKey(RfrmgrPhoneNumbers.RFRMGR_PHONE_NUMBERS, "KEY_rfrmgr_phone_numbers_PRIMARY", RfrmgrPhoneNumbers.RFRMGR_PHONE_NUMBERS.ID);
        public static final UniqueKey<RfrmgrPhoneNumbersRecord> KEY_RFRMGR_PHONE_NUMBERS_ID_UNIQUE = createUniqueKey(RfrmgrPhoneNumbers.RFRMGR_PHONE_NUMBERS, "KEY_rfrmgr_phone_numbers_id_UNIQUE", RfrmgrPhoneNumbers.RFRMGR_PHONE_NUMBERS.ID);
        public static final UniqueKey<RfrmgrPicturesRecord> KEY_RFRMGR_PICTURES_PRIMARY = createUniqueKey(RfrmgrPictures.RFRMGR_PICTURES, "KEY_rfrmgr_pictures_PRIMARY", RfrmgrPictures.RFRMGR_PICTURES.ID);
        public static final UniqueKey<RfrmgrPicturesRecord> KEY_RFRMGR_PICTURES_ID_UNIQUE = createUniqueKey(RfrmgrPictures.RFRMGR_PICTURES, "KEY_rfrmgr_pictures_id_UNIQUE", RfrmgrPictures.RFRMGR_PICTURES.ID);
        public static final UniqueKey<RfrmgrRefereesRecord> KEY_RFRMGR_REFEREES_PRIMARY = createUniqueKey(RfrmgrReferees.RFRMGR_REFEREES, "KEY_rfrmgr_referees_PRIMARY", RfrmgrReferees.RFRMGR_REFEREES.ID);
        public static final UniqueKey<RfrmgrRefereesRecord> KEY_RFRMGR_REFEREES_ID_UNIQUE = createUniqueKey(RfrmgrReferees.RFRMGR_REFEREES, "KEY_rfrmgr_referees_id_UNIQUE", RfrmgrReferees.RFRMGR_REFEREES.ID);
        public static final UniqueKey<RfrmgrRefereeAssignmentsRecord> KEY_RFRMGR_REFEREE_ASSIGNMENTS_PRIMARY = createUniqueKey(RfrmgrRefereeAssignments.RFRMGR_REFEREE_ASSIGNMENTS, "KEY_rfrmgr_referee_assignments_PRIMARY", RfrmgrRefereeAssignments.RFRMGR_REFEREE_ASSIGNMENTS.ID);
        public static final UniqueKey<RfrmgrRefereeAssignmentsRecord> KEY_RFRMGR_REFEREE_ASSIGNMENTS_ID_UNIQUE = createUniqueKey(RfrmgrRefereeAssignments.RFRMGR_REFEREE_ASSIGNMENTS, "KEY_rfrmgr_referee_assignments_id_UNIQUE", RfrmgrRefereeAssignments.RFRMGR_REFEREE_ASSIGNMENTS.ID);
        public static final UniqueKey<RfrmgrRefereeAssignmentRemarkTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES_PRIMARY = createUniqueKey(RfrmgrRefereeAssignmentRemarkTypes.RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES, "KEY_rfrmgr_referee_assignment_remark_types_PRIMARY", RfrmgrRefereeAssignmentRemarkTypes.RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES.ID);
        public static final UniqueKey<RfrmgrRefereeAssignmentRemarkTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES_ID_UNIQUE = createUniqueKey(RfrmgrRefereeAssignmentRemarkTypes.RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES, "KEY_rfrmgr_referee_assignment_remark_types_id_UNIQUE", RfrmgrRefereeAssignmentRemarkTypes.RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES.ID);
        public static final UniqueKey<RfrmgrRefereeAssignmentRemarkTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES_TITLE_UNIQUE = createUniqueKey(RfrmgrRefereeAssignmentRemarkTypes.RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES, "KEY_rfrmgr_referee_assignment_remark_types_title_UNIQUE", RfrmgrRefereeAssignmentRemarkTypes.RFRMGR_REFEREE_ASSIGNMENT_REMARK_TYPES.TITLE);
        public static final UniqueKey<RfrmgrRefereeAssignmentStatusTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES_PRIMARY = createUniqueKey(RfrmgrRefereeAssignmentStatusTypes.RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES, "KEY_rfrmgr_referee_assignment_status_types_PRIMARY", RfrmgrRefereeAssignmentStatusTypes.RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES.ID);
        public static final UniqueKey<RfrmgrRefereeAssignmentStatusTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES_ID_UNIQUE = createUniqueKey(RfrmgrRefereeAssignmentStatusTypes.RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES, "KEY_rfrmgr_referee_assignment_status_types_id_UNIQUE", RfrmgrRefereeAssignmentStatusTypes.RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES.ID);
        public static final UniqueKey<RfrmgrRefereeAssignmentStatusTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES_TITLE_UNIQUE = createUniqueKey(RfrmgrRefereeAssignmentStatusTypes.RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES, "KEY_rfrmgr_referee_assignment_status_types_title_UNIQUE", RfrmgrRefereeAssignmentStatusTypes.RFRMGR_REFEREE_ASSIGNMENT_STATUS_TYPES.SID);
        public static final UniqueKey<RfrmgrRefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_PRIMARY = createUniqueKey(RfrmgrRefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES, "KEY_rfrmgr_referee_assignment_types_PRIMARY", RfrmgrRefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES.ID);
        public static final UniqueKey<RfrmgrRefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_ID_UNIQUE = createUniqueKey(RfrmgrRefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES, "KEY_rfrmgr_referee_assignment_types_id_UNIQUE", RfrmgrRefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES.ID);
        public static final UniqueKey<RfrmgrRefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_SID_UNIQUE = createUniqueKey(RfrmgrRefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES, "KEY_rfrmgr_referee_assignment_types_sid_UNIQUE", RfrmgrRefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES.SID);
        public static final UniqueKey<RfrmgrRefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_TITLE_UNIQUE = createUniqueKey(RfrmgrRefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES, "KEY_rfrmgr_referee_assignment_types_title_UNIQUE", RfrmgrRefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES.TITLE);
        public static final UniqueKey<RfrmgrRefereeAssignmentTypesRecord> KEY_RFRMGR_REFEREE_ASSIGNMENT_TYPES_ABBREVIATION_UNIQUE = createUniqueKey(RfrmgrRefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES, "KEY_rfrmgr_referee_assignment_types_abbreviation_UNIQUE", RfrmgrRefereeAssignmentTypes.RFRMGR_REFEREE_ASSIGNMENT_TYPES.ABBREVIATION);
        public static final UniqueKey<RfrmgrRefereeRelationsRecord> KEY_RFRMGR_REFEREE_RELATIONS_PRIMARY = createUniqueKey(RfrmgrRefereeRelations.RFRMGR_REFEREE_RELATIONS, "KEY_rfrmgr_referee_relations_PRIMARY", RfrmgrRefereeRelations.RFRMGR_REFEREE_RELATIONS.ID);
        public static final UniqueKey<RfrmgrRefereeRelationsRecord> KEY_RFRMGR_REFEREE_RELATIONS_ID_UNIQUE = createUniqueKey(RfrmgrRefereeRelations.RFRMGR_REFEREE_RELATIONS, "KEY_rfrmgr_referee_relations_id_UNIQUE", RfrmgrRefereeRelations.RFRMGR_REFEREE_RELATIONS.ID);
        public static final UniqueKey<RfrmgrRefereeRelationTypesRecord> KEY_RFRMGR_REFEREE_RELATION_TYPES_PRIMARY = createUniqueKey(RfrmgrRefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES, "KEY_rfrmgr_referee_relation_types_PRIMARY", RfrmgrRefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES.ID);
        public static final UniqueKey<RfrmgrRefereeRelationTypesRecord> KEY_RFRMGR_REFEREE_RELATION_TYPES_ID_UNIQUE = createUniqueKey(RfrmgrRefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES, "KEY_rfrmgr_referee_relation_types_id_UNIQUE", RfrmgrRefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES.ID);
        public static final UniqueKey<RfrmgrRefereeRelationTypesRecord> KEY_RFRMGR_REFEREE_RELATION_TYPES_SID_UNIQUE = createUniqueKey(RfrmgrRefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES, "KEY_rfrmgr_referee_relation_types_sid_UNIQUE", RfrmgrRefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES.SID);
        public static final UniqueKey<RfrmgrRefereeRelationTypesRecord> KEY_RFRMGR_REFEREE_RELATION_TYPES_TITLE_UNIQUE = createUniqueKey(RfrmgrRefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES, "KEY_rfrmgr_referee_relation_types_title_UNIQUE", RfrmgrRefereeRelationTypes.RFRMGR_REFEREE_RELATION_TYPES.TITLE);
        public static final UniqueKey<RfrmgrRefereeReportsRecord> KEY_RFRMGR_REFEREE_REPORTS_PRIMARY = createUniqueKey(RfrmgrRefereeReports.RFRMGR_REFEREE_REPORTS, "KEY_rfrmgr_referee_reports_PRIMARY", RfrmgrRefereeReports.RFRMGR_REFEREE_REPORTS.ID);
        public static final UniqueKey<RfrmgrRefereeReportsRecord> KEY_RFRMGR_REFEREE_REPORTS_ID_UNIQUE = createUniqueKey(RfrmgrRefereeReports.RFRMGR_REFEREE_REPORTS, "KEY_rfrmgr_referee_reports_id_UNIQUE", RfrmgrRefereeReports.RFRMGR_REFEREE_REPORTS.ID);
        public static final UniqueKey<RfrmgrRefereeReportRecipientsRecord> KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_PRIMARY = createUniqueKey(RfrmgrRefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS, "KEY_rfrmgr_referee_report_recipients_PRIMARY", RfrmgrRefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS.ID);
        public static final UniqueKey<RfrmgrRefereeReportRecipientsRecord> KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_ID_UNIQUE = createUniqueKey(RfrmgrRefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS, "KEY_rfrmgr_referee_report_recipients_id_UNIQUE", RfrmgrRefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS.ID);
        public static final UniqueKey<RfrmgrRefereeReportRecipientsRecord> KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_TITLE_UNIQUE = createUniqueKey(RfrmgrRefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS, "KEY_rfrmgr_referee_report_recipients_title_UNIQUE", RfrmgrRefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS.REFEREE_REPORT_ID);
        public static final UniqueKey<RfrmgrRefereeReportRecipientsRecord> KEY_RFRMGR_REFEREE_REPORT_RECIPIENTS_PERSON_ID_UNIQUE = createUniqueKey(RfrmgrRefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS, "KEY_rfrmgr_referee_report_recipients_person_id_UNIQUE", RfrmgrRefereeReportRecipients.RFRMGR_REFEREE_REPORT_RECIPIENTS.PERSON_ID);
        public static final UniqueKey<RfrmgrRefereeStatusesRecord> KEY_RFRMGR_REFEREE_STATUSES_PRIMARY = createUniqueKey(RfrmgrRefereeStatuses.RFRMGR_REFEREE_STATUSES, "KEY_rfrmgr_referee_statuses_PRIMARY", RfrmgrRefereeStatuses.RFRMGR_REFEREE_STATUSES.ID);
        public static final UniqueKey<RfrmgrRefereeStatusesRecord> KEY_RFRMGR_REFEREE_STATUSES_ID_UNIQUE = createUniqueKey(RfrmgrRefereeStatuses.RFRMGR_REFEREE_STATUSES, "KEY_rfrmgr_referee_statuses_id_UNIQUE", RfrmgrRefereeStatuses.RFRMGR_REFEREE_STATUSES.ID);
        public static final UniqueKey<RfrmgrSeasonsRecord> KEY_RFRMGR_SEASONS_PRIMARY = createUniqueKey(RfrmgrSeasons.RFRMGR_SEASONS, "KEY_rfrmgr_seasons_PRIMARY", RfrmgrSeasons.RFRMGR_SEASONS.ID);
        public static final UniqueKey<RfrmgrSeasonsRecord> KEY_RFRMGR_SEASONS_ID_UNIQUE = createUniqueKey(RfrmgrSeasons.RFRMGR_SEASONS, "KEY_rfrmgr_seasons_id_UNIQUE", RfrmgrSeasons.RFRMGR_SEASONS.ID);
        public static final UniqueKey<RfrmgrSeasonsRecord> KEY_RFRMGR_SEASONS_YEAR_START_UNIQUE = createUniqueKey(RfrmgrSeasons.RFRMGR_SEASONS, "KEY_rfrmgr_seasons_year_start_UNIQUE", RfrmgrSeasons.RFRMGR_SEASONS.YEAR_START);
        public static final UniqueKey<RfrmgrSexTypesRecord> KEY_RFRMGR_SEX_TYPES_PRIMARY = createUniqueKey(RfrmgrSexTypes.RFRMGR_SEX_TYPES, "KEY_rfrmgr_sex_types_PRIMARY", RfrmgrSexTypes.RFRMGR_SEX_TYPES.ID);
        public static final UniqueKey<RfrmgrSexTypesRecord> KEY_RFRMGR_SEX_TYPES_ID_UNIQUE = createUniqueKey(RfrmgrSexTypes.RFRMGR_SEX_TYPES, "KEY_rfrmgr_sex_types_id_UNIQUE", RfrmgrSexTypes.RFRMGR_SEX_TYPES.ID);
        public static final UniqueKey<RfrmgrSexTypesRecord> KEY_RFRMGR_SEX_TYPES_SID_UNIQUE = createUniqueKey(RfrmgrSexTypes.RFRMGR_SEX_TYPES, "KEY_rfrmgr_sex_types_sid_UNIQUE", RfrmgrSexTypes.RFRMGR_SEX_TYPES.SID);
        public static final UniqueKey<RfrmgrSpokespeopleRecord> KEY_RFRMGR_SPOKESPEOPLE_PRIMARY = createUniqueKey(RfrmgrSpokespeople.RFRMGR_SPOKESPEOPLE, "KEY_rfrmgr_spokespeople_PRIMARY", RfrmgrSpokespeople.RFRMGR_SPOKESPEOPLE.ID);
        public static final UniqueKey<RfrmgrSpokespeopleRecord> KEY_RFRMGR_SPOKESPEOPLE_ID_UNIQUE = createUniqueKey(RfrmgrSpokespeople.RFRMGR_SPOKESPEOPLE, "KEY_rfrmgr_spokespeople_id_UNIQUE", RfrmgrSpokespeople.RFRMGR_SPOKESPEOPLE.ID);
        public static final UniqueKey<RfrmgrStatusTypesRecord> KEY_RFRMGR_STATUS_TYPES_PRIMARY = createUniqueKey(RfrmgrStatusTypes.RFRMGR_STATUS_TYPES, "KEY_rfrmgr_status_types_PRIMARY", RfrmgrStatusTypes.RFRMGR_STATUS_TYPES.ID);
        public static final UniqueKey<RfrmgrStatusTypesRecord> KEY_RFRMGR_STATUS_TYPES_ID_UNIQUE = createUniqueKey(RfrmgrStatusTypes.RFRMGR_STATUS_TYPES, "KEY_rfrmgr_status_types_id_UNIQUE", RfrmgrStatusTypes.RFRMGR_STATUS_TYPES.ID);
        public static final UniqueKey<RfrmgrStatusTypesRecord> KEY_RFRMGR_STATUS_TYPES_SID_UNIQUE = createUniqueKey(RfrmgrStatusTypes.RFRMGR_STATUS_TYPES, "KEY_rfrmgr_status_types_sid_UNIQUE", RfrmgrStatusTypes.RFRMGR_STATUS_TYPES.SID);
        public static final UniqueKey<RfrmgrStatusTypesRecord> KEY_RFRMGR_STATUS_TYPES_TITLE_UNIQUE = createUniqueKey(RfrmgrStatusTypes.RFRMGR_STATUS_TYPES, "KEY_rfrmgr_status_types_title_UNIQUE", RfrmgrStatusTypes.RFRMGR_STATUS_TYPES.TITLE);
        public static final UniqueKey<RfrmgrTeamsRecord> KEY_RFRMGR_TEAMS_PRIMARY = createUniqueKey(RfrmgrTeams.RFRMGR_TEAMS, "KEY_rfrmgr_teams_PRIMARY", RfrmgrTeams.RFRMGR_TEAMS.ID);
        public static final UniqueKey<RfrmgrTeamsRecord> KEY_RFRMGR_TEAMS_ID_UNIQUE = createUniqueKey(RfrmgrTeams.RFRMGR_TEAMS, "KEY_rfrmgr_teams_id_UNIQUE", RfrmgrTeams.RFRMGR_TEAMS.ID);
        public static final UniqueKey<RfrmgrTeamSeasonsRecord> KEY_RFRMGR_TEAM_SEASONS_PRIMARY = createUniqueKey(RfrmgrTeamSeasons.RFRMGR_TEAM_SEASONS, "KEY_rfrmgr_team_seasons_PRIMARY", RfrmgrTeamSeasons.RFRMGR_TEAM_SEASONS.ID);
        public static final UniqueKey<RfrmgrTeamSeasonsRecord> KEY_RFRMGR_TEAM_SEASONS_ID_UNIQUE = createUniqueKey(RfrmgrTeamSeasons.RFRMGR_TEAM_SEASONS, "KEY_rfrmgr_team_seasons_id_UNIQUE", RfrmgrTeamSeasons.RFRMGR_TEAM_SEASONS.ID);
        public static final UniqueKey<RfrmgrTeamVenuesRecord> KEY_RFRMGR_TEAM_VENUES_PRIMARY = createUniqueKey(RfrmgrTeamVenues.RFRMGR_TEAM_VENUES, "KEY_rfrmgr_team_venues_PRIMARY", RfrmgrTeamVenues.RFRMGR_TEAM_VENUES.ID);
        public static final UniqueKey<RfrmgrTeamVenuesRecord> KEY_RFRMGR_TEAM_VENUES_ID_UNIQUE = createUniqueKey(RfrmgrTeamVenues.RFRMGR_TEAM_VENUES, "KEY_rfrmgr_team_venues_id_UNIQUE", RfrmgrTeamVenues.RFRMGR_TEAM_VENUES.ID);
        public static final UniqueKey<RfrmgrTournamentsRecord> KEY_RFRMGR_TOURNAMENTS_PRIMARY = createUniqueKey(RfrmgrTournaments.RFRMGR_TOURNAMENTS, "KEY_rfrmgr_tournaments_PRIMARY", RfrmgrTournaments.RFRMGR_TOURNAMENTS.ID);
        public static final UniqueKey<RfrmgrTournamentsRecord> KEY_RFRMGR_TOURNAMENTS_ID_UNIQUE = createUniqueKey(RfrmgrTournaments.RFRMGR_TOURNAMENTS, "KEY_rfrmgr_tournaments_id_UNIQUE", RfrmgrTournaments.RFRMGR_TOURNAMENTS.ID);
        public static final UniqueKey<RfrmgrTournamentsRecord> KEY_RFRMGR_TOURNAMENTS_ABBREVIATION_UNIQUE = createUniqueKey(RfrmgrTournaments.RFRMGR_TOURNAMENTS, "KEY_rfrmgr_tournaments_abbreviation_UNIQUE", RfrmgrTournaments.RFRMGR_TOURNAMENTS.NAME);
        public static final UniqueKey<RfrmgrTournamentGamesRecord> KEY_RFRMGR_TOURNAMENT_GAMES_PRIMARY = createUniqueKey(RfrmgrTournamentGames.RFRMGR_TOURNAMENT_GAMES, "KEY_rfrmgr_tournament_games_PRIMARY", RfrmgrTournamentGames.RFRMGR_TOURNAMENT_GAMES.ID);
        public static final UniqueKey<RfrmgrTournamentGamesRecord> KEY_RFRMGR_TOURNAMENT_GAMES_ID_UNIQUE = createUniqueKey(RfrmgrTournamentGames.RFRMGR_TOURNAMENT_GAMES, "KEY_rfrmgr_tournament_games_id_UNIQUE", RfrmgrTournamentGames.RFRMGR_TOURNAMENT_GAMES.ID);
        public static final UniqueKey<RfrmgrTournamentVenuesRecord> KEY_RFRMGR_TOURNAMENT_VENUES_PRIMARY = createUniqueKey(RfrmgrTournamentVenues.RFRMGR_TOURNAMENT_VENUES, "KEY_rfrmgr_tournament_venues_PRIMARY", RfrmgrTournamentVenues.RFRMGR_TOURNAMENT_VENUES.ID);
        public static final UniqueKey<RfrmgrTournamentVenuesRecord> KEY_RFRMGR_TOURNAMENT_VENUES_ID_UNIQUE = createUniqueKey(RfrmgrTournamentVenues.RFRMGR_TOURNAMENT_VENUES, "KEY_rfrmgr_tournament_venues_id_UNIQUE", RfrmgrTournamentVenues.RFRMGR_TOURNAMENT_VENUES.ID);
        public static final UniqueKey<RfrmgrTrainingLevelsRecord> KEY_RFRMGR_TRAINING_LEVELS_PRIMARY = createUniqueKey(RfrmgrTrainingLevels.RFRMGR_TRAINING_LEVELS, "KEY_rfrmgr_training_levels_PRIMARY", RfrmgrTrainingLevels.RFRMGR_TRAINING_LEVELS.ID);
        public static final UniqueKey<RfrmgrTrainingLevelsRecord> KEY_RFRMGR_TRAINING_LEVELS_ID_UNIQUE = createUniqueKey(RfrmgrTrainingLevels.RFRMGR_TRAINING_LEVELS, "KEY_rfrmgr_training_levels_id_UNIQUE", RfrmgrTrainingLevels.RFRMGR_TRAINING_LEVELS.ID);
        public static final UniqueKey<RfrmgrTrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_PRIMARY = createUniqueKey(RfrmgrTrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES, "KEY_rfrmgr_training_level_types_PRIMARY", RfrmgrTrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES.ID);
        public static final UniqueKey<RfrmgrTrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_ID_UNIQUE = createUniqueKey(RfrmgrTrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES, "KEY_rfrmgr_training_level_types_id_UNIQUE", RfrmgrTrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES.ID);
        public static final UniqueKey<RfrmgrTrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_SID_UNIQUE = createUniqueKey(RfrmgrTrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES, "KEY_rfrmgr_training_level_types_sid_UNIQUE", RfrmgrTrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES.SID);
        public static final UniqueKey<RfrmgrTrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_RANK_UNIQUE = createUniqueKey(RfrmgrTrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES, "KEY_rfrmgr_training_level_types_rank_UNIQUE", RfrmgrTrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES.RANK);
        public static final UniqueKey<RfrmgrTrainingLevelTypesRecord> KEY_RFRMGR_TRAINING_LEVEL_TYPES_TITLE_UNIQUE = createUniqueKey(RfrmgrTrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES, "KEY_rfrmgr_training_level_types_title_UNIQUE", RfrmgrTrainingLevelTypes.RFRMGR_TRAINING_LEVEL_TYPES.TITLE);
        public static final UniqueKey<RfrmgrTrainingUpdatesRecord> KEY_RFRMGR_TRAINING_UPDATES_PRIMARY = createUniqueKey(RfrmgrTrainingUpdates.RFRMGR_TRAINING_UPDATES, "KEY_rfrmgr_training_updates_PRIMARY", RfrmgrTrainingUpdates.RFRMGR_TRAINING_UPDATES.ID);
        public static final UniqueKey<RfrmgrTrainingUpdatesRecord> KEY_RFRMGR_TRAINING_UPDATES_ID_UNIQUE = createUniqueKey(RfrmgrTrainingUpdates.RFRMGR_TRAINING_UPDATES, "KEY_rfrmgr_training_updates_id_UNIQUE", RfrmgrTrainingUpdates.RFRMGR_TRAINING_UPDATES.ID);
        public static final UniqueKey<RfrmgrUrlsRecord> KEY_RFRMGR_URLS_PRIMARY = createUniqueKey(RfrmgrUrls.RFRMGR_URLS, "KEY_rfrmgr_urls_PRIMARY", RfrmgrUrls.RFRMGR_URLS.ID);
        public static final UniqueKey<RfrmgrUrlsRecord> KEY_RFRMGR_URLS_ID_UNIQUE = createUniqueKey(RfrmgrUrls.RFRMGR_URLS, "KEY_rfrmgr_urls_id_UNIQUE", RfrmgrUrls.RFRMGR_URLS.ID);
        public static final UniqueKey<RfrmgrUsersRecord> KEY_RFRMGR_USERS_PRIMARY = createUniqueKey(RfrmgrUsers.RFRMGR_USERS, "KEY_rfrmgr_users_PRIMARY", RfrmgrUsers.RFRMGR_USERS.ID);
        public static final UniqueKey<RfrmgrUsersRecord> KEY_RFRMGR_USERS_ID_UNIQUE = createUniqueKey(RfrmgrUsers.RFRMGR_USERS, "KEY_rfrmgr_users_id_UNIQUE", RfrmgrUsers.RFRMGR_USERS.ID);
        public static final UniqueKey<RfrmgrUsersRecord> KEY_RFRMGR_USERS_USERNAME_UNIQUE = createUniqueKey(RfrmgrUsers.RFRMGR_USERS, "KEY_rfrmgr_users_username_UNIQUE", RfrmgrUsers.RFRMGR_USERS.USERNAME);
        public static final UniqueKey<RfrmgrUserRolesRecord> KEY_RFRMGR_USER_ROLES_PRIMARY = createUniqueKey(RfrmgrUserRoles.RFRMGR_USER_ROLES, "KEY_rfrmgr_user_roles_PRIMARY", RfrmgrUserRoles.RFRMGR_USER_ROLES.ID);
        public static final UniqueKey<RfrmgrUserRolesRecord> KEY_RFRMGR_USER_ROLES_ID_UNIQUE = createUniqueKey(RfrmgrUserRoles.RFRMGR_USER_ROLES, "KEY_rfrmgr_user_roles_id_UNIQUE", RfrmgrUserRoles.RFRMGR_USER_ROLES.ID);
        public static final UniqueKey<RfrmgrUserRolesRecord> KEY_RFRMGR_USER_ROLES_SID_UNIQUE = createUniqueKey(RfrmgrUserRoles.RFRMGR_USER_ROLES, "KEY_rfrmgr_user_roles_sid_UNIQUE", RfrmgrUserRoles.RFRMGR_USER_ROLES.SID);
        public static final UniqueKey<RfrmgrWishesRecord> KEY_RFRMGR_WISHES_PRIMARY = createUniqueKey(RfrmgrWishes.RFRMGR_WISHES, "KEY_rfrmgr_wishes_PRIMARY", RfrmgrWishes.RFRMGR_WISHES.ID);
        public static final UniqueKey<RfrmgrWishesRecord> KEY_RFRMGR_WISHES_ID_UNIQUE = createUniqueKey(RfrmgrWishes.RFRMGR_WISHES, "KEY_rfrmgr_wishes_id_UNIQUE", RfrmgrWishes.RFRMGR_WISHES.ID);
        public static final UniqueKey<RfrmgrWishTypesRecord> KEY_RFRMGR_WISH_TYPES_PRIMARY = createUniqueKey(RfrmgrWishTypes.RFRMGR_WISH_TYPES, "KEY_rfrmgr_wish_types_PRIMARY", RfrmgrWishTypes.RFRMGR_WISH_TYPES.ID);
        public static final UniqueKey<RfrmgrWishTypesRecord> KEY_RFRMGR_WISH_TYPES_ID_UNIQUE = createUniqueKey(RfrmgrWishTypes.RFRMGR_WISH_TYPES, "KEY_rfrmgr_wish_types_id_UNIQUE", RfrmgrWishTypes.RFRMGR_WISH_TYPES.ID);
        public static final UniqueKey<RfrmgrWishTypesRecord> KEY_RFRMGR_WISH_TYPES_SID_UNIQUE = createUniqueKey(RfrmgrWishTypes.RFRMGR_WISH_TYPES, "KEY_rfrmgr_wish_types_sid_UNIQUE", RfrmgrWishTypes.RFRMGR_WISH_TYPES.SID);
        public static final UniqueKey<RfrmgrWishTypesRecord> KEY_RFRMGR_WISH_TYPES_TITLE_UNIQUE = createUniqueKey(RfrmgrWishTypes.RFRMGR_WISH_TYPES, "KEY_rfrmgr_wish_types_title_UNIQUE", RfrmgrWishTypes.RFRMGR_WISH_TYPES.TITLE);
    }
}
