Quotes Language:		german
Base Header Level:	3
latex input:				kleinod-mmd-scrartcl
MyOptions:					author=schiri, font=droid, notitlepage, noauthor, orientation=landscape, pagestyle=fuss
latex input:				kleinod-mmd-style
Title:							Aktive Verbandsschiedsrichter
MySubTitle:					BTTV, Saison **generated season:title**
Date:								Stand: **generated info:modified:date:long**
latex input:				kleinod-mmd-begin-doc

<!-- \maketitle -->

<!--

\footnotesize

\tabulinesep=_.5\parskip^.5\parskip

\begin{longtabu}[l]{@{}>{\RaggedRight}p{.18\textwidth}@{\hspace{.01\textwidth}}>{\RaggedRight}p{.18\textwidth}@{\hspace{.01\textwidth}}%
				>{\RaggedRight}p{.05\textwidth}@{\hspace{.01\textwidth}}>{\RaggedRight}p{.18\textwidth}@{\hspace{.01\textwidth}}>{\RaggedRight}p{.18\textwidth}@{\hspace{.01\textwidth}}>{\RaggedRight}p{.18\textwidth}@{}}
		\toprule
		\textbf{\scriptsize Name} & \textbf{\scriptsize Mitglied\newline\textsl{Schiedst für}} & \textbf{\scriptsize Ausb.} & \textbf{\scriptsize Adresse} & \textbf{\scriptsize Bevorzugt schiedsen} & \textbf{\scriptsize Nicht schiedsen}\\
		\midrule
	\endhead
		\midrule
		\multicolumn{6}{@{}r@{}}{\emph{\scriptsize weiter auf der nächsten Seite\dots}}\\
		\bottomrule
	\endfoot
		\bottomrule
	\endlastfoot

**foreach referee**
**if even referee**\rowcolor{white}**end if even referee****if odd referee**\rowcolor{Linen}**end if odd referee**
-->**generated referee:status:mmdmarkupstart****generated referee:tablename****generated referee:status:mmdmarkupend**<!-- &
-->**generated referee:status:mmdmarkupstart****generated referee:member:displaytitle****generated referee:status:mmdmarkupend****if notempty referee:reffor**<!--\newline\textsl{-->**generated referee:status:mmdmarkupstart****generated referee:reffor:displaytitle****generated referee:status:mmdmarkupend**<!--}-->**end if notempty referee:reffor**<!-- &
-->**generated referee:status:mmdmarkupstart****generated referee:highesttraininglevel:type:shorttitle****generated referee:status:mmdmarkupend**<!-- &
-->**generated referee:status:mmdmarkupstart****if notempty referee:primaryaddress****generated referee:primaryaddress:displaytitle****end if notempty referee:primaryaddress****generated referee:status:mmdmarkupend**<!-- &
-->**foreach referee:prefer:****generated referee:status:mmdmarkupstart****generated referee:prefer:displaytitle****generated referee:status:mmdmarkupend****end foreach referee:prefer:**<!-- &
-->**foreach referee:avoid:****generated referee:status:mmdmarkupstart****generated referee:avoid:displaytitle****generated referee:status:mmdmarkupend****end foreach referee:avoid:**<!--
\\
**if notempty referee:remark****if even referee**\rowcolor{white}**end if even referee****if odd referee**\rowcolor{Linen}**end if odd referee**&&&&\multicolumn{2}{@{}>{\RaggedRight}p{.37\textwidth}@{}}{-->**generated referee:status:mmdmarkupstart*****generated referee:remark*****generated referee:status:mmdmarkupend**<!--}\\**end if notempty referee:remark**
**end foreach referee**

\end{longtabu}


-->

**Legende:**

**foreach statustype**
- **generated statustype:mmdmarkupstart****if notempty statustype:remark****generated statustype:remark****end if notempty statustype:remark****if empty statustype:remark****generated statustype:title****end if empty statustype:remark****generated statustype:mmdmarkupend**
**end foreach statustype**

