Quotes Language:		german
Base Header Level:	3
latex input:				kleinod-mmd-scrartcl
MyOptions:					author=schiri, font=droid, notitlepage, noauthor, orientation=landscape, pagestyle=fuss
latex input:				kleinod-mmd-style
Title:							Verbandsschiedsrichter des BTTV
MySubTitle:					Saison **generated season:title**
Date:								Stand: **generated info:modified:date:long**
latex input:				kleinod-mmd-begin-doc

<!-- \maketitle -->

<!--

{\footnotesize
\tabulinesep=_.5\parskip^.5\parskip

\begin{longtabu}[l]{@{}>{\RaggedRight}p{.18\textwidth}@{\hspace{.01\textwidth}}>{\RaggedRight}p{.18\textwidth}@{\hspace{.01\textwidth}}%
				>{\RaggedRight}p{.05\textwidth}@{\hspace{.01\textwidth}}>{\RaggedRight}p{.18\textwidth}@{\hspace{.01\textwidth}}>{\RaggedRight}p{.18\textwidth}@{\hspace{.01\textwidth}}>{\RaggedRight}p{.18\textwidth}@{}}
		\toprule
		\textbf{\scriptsize Name} & \textbf{\scriptsize Mitglied\newline\textsl{Schiedst für}} & \textbf{\scriptsize Ausb.} & \textbf{\scriptsize Adresse} & \textbf{\scriptsize Bevorzugt schiedsen} & \textbf{\scriptsize Nicht schiedsen}\\
		\midrule
	\endhead
		\midrule
		\multicolumn{6}{@{}r@{}}{\emph{\scriptsize weiter auf der nächsten Seite\dots}}\\
		\bottomrule
	\endfoot
		\bottomrule
	\endlastfoot

**foreach referee**
**if even referee**\rowcolor{white}**endif even referee****if odd referee**\rowcolor{Linen}**endif odd referee**
-->**generated referee:tablename**<!-- &
-->**generated referee:member:displaytitle****if notempty referee:reffor**<!--\newline\textsl{-->**generated referee:reffor:displaytitle**<!--}-->**endif notempty referee:reffor**<!-- &
-->**generated referee:highesttraininglevel:type:shorttitle**<!-- &
-->**if notempty referee:primaryaddress****generated referee:primaryaddress:displaytitle****endif notempty referee:primaryaddress**<!-- &
-->**foreach referee:prefer:****generated referee:prefer:displaytitle****endforeach referee:prefer:**<!-- &
-->**foreach referee:avoid:****generated referee:avoid:displaytitle****endforeach referee:avoid:**<!--
\\
**if notempty referee:remark****if even referee**\rowcolor{white}**endif even referee****if odd referee**\rowcolor{Linen}**endif odd referee**&\multicolumn{5}{@{}>{\RaggedRight}p{.81\textwidth}@{}}{-->***generated referee:remark***<!--}\\**endif notempty referee:remark**
**endforeach referee**

\end{longtabu}
}

-->

**Legende:**

**foreach statustype**
- **if notempty statustype:remark****generated statustype:remark****endif notempty statustype:remark****if empty statustype:remark****generated statustype:title****endif empty statustype:remark**
**endforeach statustype**
