Title:							Referee Manager Developer Documentation
Author:							Ekkart Kleinod
Date:								21.04.2013
Base Header Level:	3

# Preface

This documentation focuses on the development aspect of the referee manager.
Thus, there is no description for setting up the referee manager in a production environment.
This is part of the user documentation.

Therefor be aware, that your passwords etc. are not secured during development, if you don't secure them yourselves.
The same goes for other security aspects.

I develop the referee manager in a virtual machine with no access from the internet, or on a laptop with no reading access from the internet.
I urge you to do so yourselves, unless you know what you are doing.

## Used Language

The developer's documentation is in English, because I think more people understand English than German and thus more people can use the referee manager.
As I am a German native speaker, you can ask German questions every time.

Die Dokumentation ist auf Englisch, damit mehr Leute die Schiedsrichterverwaltung nutzen können.
Da ich Deutsch als Mutterspreche spreche, können Sie natürlich jederzeit auch deutsche Fragen stellen.

# Structure and git repositories

There are three git sources used for development:

- CakePHP ([Homepage][url:cake], [Git][url:cake:git])
- phpMyAdmin ([Homepage][url:pma], [Git][url:pma:git])
- Referee Manager ([Homepage][url:refman], [Git][url:refman:git])

The first two are read-only, the third, referee manager is read/write if you watn to develop.

During the development process, several files have to be locatede in directories of CakePHP and phpMyAdmin resp.
In order to avoid having several files mixed up, therefore making it difficult to seperate referee manager files from original files, the development directories are separated from the git sources.

This means: updates of CakePHP and/or phpMyAdmin have to be copied to the development directories.
In order to avoid cluttering, in this case the development directories are deleted first.
After updates the referee manager files have to be copied to the development directories.



# Software

You will need at least:

- Git
- Apache (incl. mysql module)
- PHP
- Referee Manager

# Code and CakePHP

It is a bit difficult to set up the code and cakephp.
Maybe I provide an ant script for this task, for now you have to do this by hand.
It is not "impossible" difficult, but nonetheless, follow the instruction given below.

- clone the code of the referee manager (example with ssh access, for other possibilities see [http://sourceforge.net/projects/refereemanager/](http://sourceforge.net/projects/refereemanager/))

	$ git clone ssh://git.code.sf.net/p/refereemanager/code refereemanager-code

- rename the folder `app` in `cakephp/app` to `app.xyz`
	- explanation: we will copy the `app` folder of CakePHP here, so this folder has to be out of the way for now
- download the latest version of CakePHP http://cakephp.org/
- extract the files
- copy all files to the `cakephp` folder of the referee manager
	- do not forget the *hidden* files (ctrl+h in most file managers)
- copy the content of the `app.xyz` folder to `app`
	- choose overwrite for existing files
- ready

Now some folder have to be given more access rights in order for the application to work nicely.

- all folders that are referenced by apache have to be given read rights for apache
	- the whole path has to be readable, especially the home folder
- in `refereemanager-code/cakephp/` the following folders have to be writeable for apache:
	- `app/tmp` and all its subfolders

	$ cd <...>/refereemanager-code/cakephp/app/
	$ chmod 777 tmp
	$ cd tmp
	$ find -type d -exec chmod 777 {} \;

# Apache

Sometimes apache did not start when the file `default` was linked into the directory `sites-available` (see below).
In that case, restart apache as stated below.
I did not research if this is a bug or a feature or an error on my side.

After each change restart apache
	$ sudo apachectl -k restart

## Include referee manager code and phpmyadmin

Create a symbolic link to the two needed directories.
The links have to be created in

	/var/www/

	/var/www/$ sudo ln -s <...>/refereemanager-code/cakephp/
	/var/www/$ sudo ln -s <...>/phpmyadmin

## Access restrictions

In standard configuration, all sites in apache2 have access restrictions.
You have to allow access explicitely.

Handle this situation with care if you are on a live system.
In my test system that is working local in a VM, I can allow access to all sites withour having to consider security issues.

After the changes, check if [http://localhost/](http://localhost/) (still) works.

### apache2.conf

For some reason in newer apache installations the file `apache2.conf` does not lin to `httpd.conf` anymore.
I don't know if this is a bug, a feature, a security thing or else.
In that case, add the following line to `apache2.conf`

	# Include all the user configurations:
	Include httpd.conf

Add the line before

	Include ports.conf

The file is provided in git too, check if a link is needed or the changes are made faster by hand.

### httpd.conf

Add the file `httpd.conf` to the directory `/etc/apache2` or link the given `httpd.conf` file from git.
Check if the file exists first, merge existing files if you have to.

Important changes content of `httpd.conf` in section `Directory /`:

	Options FollowSymLinks
	AllowOverride All

At the end of the file:

	LoadModule rewrite_module /usr/lib/apache2/modules/mod_rewrite.so

Or (the linking solution):

	$ cd /etc/apache2/
	$ sudo ln -s <...>/refereemanager-code/configuration/apache2/httpd.conf

In both cases it is important to allow the following of symbolic links and the override.

### default

Change `default` in `/etc/apache2/sites-available/` (to be tested if this change is needed).
Here too allow override and following of symbolic links in sections `Directory /` and `Directory /var/www`.

You can link to the git-stored file as well:

	$ cd /etc/apache2/sites-available/
	$ sudo ln -s <...>/refereemanager-code/configuration/apache2/sites-available/default

Sometimes apache did not start with a linked `default`.
In that case restart apache by hand, see explanation above.

# Setup database

Now we are ready to set up the database.
First, link the phpmyadmin configuration file to your PHPMyAdmin folder:

	$ cd <...>/phpmyadmin
	$ ln -s <...>/refereemanager-code/configuration/phpmyadmin/config.inc.php

Now you should be able to access your database with:

	https://localhost/phpmyadmin/

Now create a database called "refereemanager".

Create the database tables using the code of

	<...>/refereemanager-code/database/refereemanager.sql

Fill the database with your data if you have some.

[url:refman]: http://sourceforge.net/projects/refereemanager/ "Referee Manager Sourceforge Home"
[url:refman:wiki]: http://sourceforge.net/p/refereemanager/wiki/Home/ "Referee Manager Sourceforge Wiki"
[url:refman:git]: http://git.code.sf.net/p/refereemanager/code "Referee Manager Sourceforge Git Access"
[url:cake]: http://cakephp.org/ "CakePHP Homepage"
[url:cake:git]: git://github.com/cakephp/cakephp.git "CakePHP Git Access"
[url:pma]: http://www.phpmyadmin.net/ "phpMyAdmin Homepage"
[url:pma:git]: git://github.com/phpmyadmin/phpmyadmin.git "phpMyAdmin Git Access"

